<?xml version="1.0" encoding="UTF-8"?>

<schema targetNamespace="http://www.fawry-eg.com/ebpp/IFXMessages/"
	xmlns="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://www.fawry-eg.com/ebpp/IFXMessages/">

	<include schemaLocation="CoreLib.xsd"></include>

	<complexType name="GenerateOTPRqType">
		<sequence>
			<element name="OTPInfo" type="tns:OTPInfoType" minOccurs="1"
				maxOccurs="1" />
			<element name="AcctInfo" type="tns:AcctInfoType" maxOccurs="1" minOccurs="0"></element>
			
		</sequence>
	</complexType>


	<complexType name="GenerateOTPRsType">

		<sequence>
			<element name="OTPInfo" type="tns:OTPInfoType" minOccurs="0"
				maxOccurs="1" />
			<element name="AcctInfo" type="tns:AcctInfoType" maxOccurs="1" minOccurs="0"></element>
			
			<element name="Password" minOccurs="0" maxOccurs="1">
				<simpleType>
					<restriction base="string">
						<maxLength value="100"></maxLength>
					</restriction>
				</simpleType>
			</element>
		</sequence>

	</complexType>



	<complexType name="OTPInfoType">

		<sequence>
			<element name="CustIds" type="tns:CustIdsType" minOccurs="0"
				maxOccurs="1" />
			<element name="CSP" minOccurs="1"
				type="tns:Identifier_Type">
			</element>
			<element name="BusinessID" minOccurs="1" maxOccurs="1"
				type="tns:C128_Type" />

			<element name="ExtraBusinessIDs"
				type="tns:ExtraBusinessIDsType" minOccurs="0" maxOccurs="1">
			</element>

			<element name="MobileNumber" minOccurs="0" maxOccurs="1">
				<simpleType>
					<restriction base="string">
						<maxLength value="20"></maxLength>
					</restriction>
				</simpleType>
			</element>

			<element name="SvcType" type="tns:SvcTypeOpenEnum"
				minOccurs="0" maxOccurs="1">
			</element>
			<element name="BillTypeCode" type="long" maxOccurs="1" minOccurs="0"></element>
			<element name="ChannelTypeCode" type="tns:DeliveryMethodOpenEnum" maxOccurs="1" minOccurs="1"></element>
		</sequence>
	</complexType>



	<complexType name="ExtraBusinessIDsType">
		<sequence>
			<element name="ExtraBusinessID" type="tns:ExtraBusinessIDType"
				minOccurs="1" maxOccurs="unbounded"></element>
		</sequence>
	</complexType>

	<complexType name="ExtraBusinessIDType">
		<sequence>

			<element name="Key" minOccurs="1" maxOccurs="1"
				type="tns:ExtraBillingAcctKeyTypeOpenEnum">

			</element>

			<element name="Value" minOccurs="1" maxOccurs="1">
				<simpleType>
					<restriction base="string">
						<maxLength value="128"></maxLength>
					</restriction>
				</simpleType>
			</element>
		</sequence>
	</complexType>

</schema>