<?xml version="1.0" encoding="UTF-8"?>
<xs:schema targetNamespace="http://ejb.sof.ebpp.fawryis.com/"
           version="1.0" xmlns:ns1="http://www.fawry-eg.com/ebpp/IFXMessages/"
           xmlns:tns="http://ejb.sof.ebpp.fawryis.com/" xmlns:xs="http://www.w3.org/2001/XMLSchema">


    <xs:import namespace="http://www.fawry-eg.com/ebpp/IFXMessages/" schemaLocation="FAWRY_IFX.xsd"/>

    <xs:element name="process">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" name="arg0" type="ns1:FAWRYType"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="processResponse">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" name="return" type="ns1:FAWRYType"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>
