//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.fawry.adapter_template.model.fawryType;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AcctInputMethodEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>{@code
 * <simpleType name="AcctInputMethodEnum">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <enumeration value="KP"/>
 *     <enumeration value="CR"/>
 *     <enumeration value="KC"/>
 *     <enumeration value="SC"/>
 *     <enumeration value="NI"/>
 *     <enumeration value="SK"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "AcctInputMethodEnum")
@XmlEnum
public enum AcctInputMethodEnum {

    KP,
    CR,
    KC,
    SC,
    NI,
    SK;

    public String value() {
        return name();
    }

    public static AcctInputMethodEnum fromValue(String v) {
        return valueOf(v);
    }

}
