//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.fawry.adapter_template.model.fawryType;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AlertSubscriptionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="AlertSubscriptionType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="NotificationPoint" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}NotificationPointType"/>
 *         <element name="BillTypeNotification" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}BillTypeNotificationMethodsType" minOccurs="0"/>
 *         <element name="EnrollmentNotification" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}EnrollmentNotificationMethodsType" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AlertSubscriptionType", propOrder = {
    "notificationPoint",
    "billTypeNotification",
    "enrollmentNotification"
})
public class AlertSubscriptionType {

    @XmlElement(name = "NotificationPoint", required = true)
    protected NotificationPointType notificationPoint;
    @XmlElement(name = "BillTypeNotification")
    protected BillTypeNotificationMethodsType billTypeNotification;
    @XmlElement(name = "EnrollmentNotification")
    protected EnrollmentNotificationMethodsType enrollmentNotification;

    /**
     * Gets the value of the notificationPoint property.
     * 
     * @return
     *     possible object is
     *     {@link NotificationPointType }
     *     
     */
    public NotificationPointType getNotificationPoint() {
        return notificationPoint;
    }

    /**
     * Sets the value of the notificationPoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link NotificationPointType }
     *     
     */
    public void setNotificationPoint(NotificationPointType value) {
        this.notificationPoint = value;
    }

    /**
     * Gets the value of the billTypeNotification property.
     * 
     * @return
     *     possible object is
     *     {@link BillTypeNotificationMethodsType }
     *     
     */
    public BillTypeNotificationMethodsType getBillTypeNotification() {
        return billTypeNotification;
    }

    /**
     * Sets the value of the billTypeNotification property.
     * 
     * @param value
     *     allowed object is
     *     {@link BillTypeNotificationMethodsType }
     *     
     */
    public void setBillTypeNotification(BillTypeNotificationMethodsType value) {
        this.billTypeNotification = value;
    }

    /**
     * Gets the value of the enrollmentNotification property.
     * 
     * @return
     *     possible object is
     *     {@link EnrollmentNotificationMethodsType }
     *     
     */
    public EnrollmentNotificationMethodsType getEnrollmentNotification() {
        return enrollmentNotification;
    }

    /**
     * Sets the value of the enrollmentNotification property.
     * 
     * @param value
     *     allowed object is
     *     {@link EnrollmentNotificationMethodsType }
     *     
     */
    public void setEnrollmentNotification(EnrollmentNotificationMethodsType value) {
        this.enrollmentNotification = value;
    }

}
