//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.fawry.adapter_template.model.fawryType;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for APaySvcRsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="APaySvcRsType">
 *   <complexContent>
 *     <extension base="{http://www.fawry-eg.com/ebpp/IFXMessages/}SvcRsCommonType">
 *       <sequence>
 *         <choice>
 *           <element name="PayMandRs" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}PayMandRsType"/>
 *           <element name="GetEnrRs" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}GetEnrRsType"/>
 *           <element name="BillEnrRs" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}BillEnrRsType"/>
 *           <element name="PmtHistoryRs" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}PmtHistoryRsType"/>
 *           <element name="PayCenterRs" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}PayCenterRsType"/>
 *           <element name="GetAlertsRs" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}GetAlertsRsType"/>
 *           <element name="MngAlertSubRs" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}MngAlertSubRsType"/>
 *           <element name="CategoryDetailsRs" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}CategoryDetailsRsType"/>
 *           <element name="GetAcctTypeSchemeRs" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}GetAcctTypeSchemeRsType"/>
 *           <element name="AccountTypeDetailsRs" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}AccountTypeDetailsRsType"/>
 *           <element name="EStatementRs" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}EStatementRsType"/>
 *         </choice>
 *       </sequence>
 *     </extension>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "APaySvcRsType", propOrder = {
    "payMandRs",
    "getEnrRs",
    "billEnrRs",
    "pmtHistoryRs",
    "payCenterRs",
    "getAlertsRs",
    "mngAlertSubRs",
    "categoryDetailsRs",
    "getAcctTypeSchemeRs",
    "accountTypeDetailsRs",
    "eStatementRs"
})
public class APaySvcRsType
    extends SvcRsCommonType
{

    @XmlElement(name = "PayMandRs")
    protected PayMandRsType payMandRs;
    @XmlElement(name = "GetEnrRs")
    protected GetEnrRsType getEnrRs;
    @XmlElement(name = "BillEnrRs")
    protected BillEnrRsType billEnrRs;
    @XmlElement(name = "PmtHistoryRs")
    protected PmtHistoryRsType pmtHistoryRs;
    @XmlElement(name = "PayCenterRs")
    protected PayCenterRsType payCenterRs;
    @XmlElement(name = "GetAlertsRs")
    protected GetAlertsRsType getAlertsRs;
    @XmlElement(name = "MngAlertSubRs")
    protected MngAlertSubRsType mngAlertSubRs;
    @XmlElement(name = "CategoryDetailsRs")
    protected CategoryDetailsRsType categoryDetailsRs;
    @XmlElement(name = "GetAcctTypeSchemeRs")
    protected GetAcctTypeSchemeRsType getAcctTypeSchemeRs;
    @XmlElement(name = "AccountTypeDetailsRs")
    protected AccountTypeDetailsRsType accountTypeDetailsRs;
    @XmlElement(name = "EStatementRs")
    protected EStatementRsType eStatementRs;

    /**
     * Gets the value of the payMandRs property.
     * 
     * @return
     *     possible object is
     *     {@link PayMandRsType }
     *     
     */
    public PayMandRsType getPayMandRs() {
        return payMandRs;
    }

    /**
     * Sets the value of the payMandRs property.
     * 
     * @param value
     *     allowed object is
     *     {@link PayMandRsType }
     *     
     */
    public void setPayMandRs(PayMandRsType value) {
        this.payMandRs = value;
    }

    /**
     * Gets the value of the getEnrRs property.
     * 
     * @return
     *     possible object is
     *     {@link GetEnrRsType }
     *     
     */
    public GetEnrRsType getGetEnrRs() {
        return getEnrRs;
    }

    /**
     * Sets the value of the getEnrRs property.
     * 
     * @param value
     *     allowed object is
     *     {@link GetEnrRsType }
     *     
     */
    public void setGetEnrRs(GetEnrRsType value) {
        this.getEnrRs = value;
    }

    /**
     * Gets the value of the billEnrRs property.
     * 
     * @return
     *     possible object is
     *     {@link BillEnrRsType }
     *     
     */
    public BillEnrRsType getBillEnrRs() {
        return billEnrRs;
    }

    /**
     * Sets the value of the billEnrRs property.
     * 
     * @param value
     *     allowed object is
     *     {@link BillEnrRsType }
     *     
     */
    public void setBillEnrRs(BillEnrRsType value) {
        this.billEnrRs = value;
    }

    /**
     * Gets the value of the pmtHistoryRs property.
     * 
     * @return
     *     possible object is
     *     {@link PmtHistoryRsType }
     *     
     */
    public PmtHistoryRsType getPmtHistoryRs() {
        return pmtHistoryRs;
    }

    /**
     * Sets the value of the pmtHistoryRs property.
     * 
     * @param value
     *     allowed object is
     *     {@link PmtHistoryRsType }
     *     
     */
    public void setPmtHistoryRs(PmtHistoryRsType value) {
        this.pmtHistoryRs = value;
    }

    /**
     * Gets the value of the payCenterRs property.
     * 
     * @return
     *     possible object is
     *     {@link PayCenterRsType }
     *     
     */
    public PayCenterRsType getPayCenterRs() {
        return payCenterRs;
    }

    /**
     * Sets the value of the payCenterRs property.
     * 
     * @param value
     *     allowed object is
     *     {@link PayCenterRsType }
     *     
     */
    public void setPayCenterRs(PayCenterRsType value) {
        this.payCenterRs = value;
    }

    /**
     * Gets the value of the getAlertsRs property.
     * 
     * @return
     *     possible object is
     *     {@link GetAlertsRsType }
     *     
     */
    public GetAlertsRsType getGetAlertsRs() {
        return getAlertsRs;
    }

    /**
     * Sets the value of the getAlertsRs property.
     * 
     * @param value
     *     allowed object is
     *     {@link GetAlertsRsType }
     *     
     */
    public void setGetAlertsRs(GetAlertsRsType value) {
        this.getAlertsRs = value;
    }

    /**
     * Gets the value of the mngAlertSubRs property.
     * 
     * @return
     *     possible object is
     *     {@link MngAlertSubRsType }
     *     
     */
    public MngAlertSubRsType getMngAlertSubRs() {
        return mngAlertSubRs;
    }

    /**
     * Sets the value of the mngAlertSubRs property.
     * 
     * @param value
     *     allowed object is
     *     {@link MngAlertSubRsType }
     *     
     */
    public void setMngAlertSubRs(MngAlertSubRsType value) {
        this.mngAlertSubRs = value;
    }

    /**
     * Gets the value of the categoryDetailsRs property.
     * 
     * @return
     *     possible object is
     *     {@link CategoryDetailsRsType }
     *     
     */
    public CategoryDetailsRsType getCategoryDetailsRs() {
        return categoryDetailsRs;
    }

    /**
     * Sets the value of the categoryDetailsRs property.
     * 
     * @param value
     *     allowed object is
     *     {@link CategoryDetailsRsType }
     *     
     */
    public void setCategoryDetailsRs(CategoryDetailsRsType value) {
        this.categoryDetailsRs = value;
    }

    /**
     * Gets the value of the getAcctTypeSchemeRs property.
     * 
     * @return
     *     possible object is
     *     {@link GetAcctTypeSchemeRsType }
     *     
     */
    public GetAcctTypeSchemeRsType getGetAcctTypeSchemeRs() {
        return getAcctTypeSchemeRs;
    }

    /**
     * Sets the value of the getAcctTypeSchemeRs property.
     * 
     * @param value
     *     allowed object is
     *     {@link GetAcctTypeSchemeRsType }
     *     
     */
    public void setGetAcctTypeSchemeRs(GetAcctTypeSchemeRsType value) {
        this.getAcctTypeSchemeRs = value;
    }

    /**
     * Gets the value of the accountTypeDetailsRs property.
     * 
     * @return
     *     possible object is
     *     {@link AccountTypeDetailsRsType }
     *     
     */
    public AccountTypeDetailsRsType getAccountTypeDetailsRs() {
        return accountTypeDetailsRs;
    }

    /**
     * Sets the value of the accountTypeDetailsRs property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccountTypeDetailsRsType }
     *     
     */
    public void setAccountTypeDetailsRs(AccountTypeDetailsRsType value) {
        this.accountTypeDetailsRs = value;
    }

    /**
     * Gets the value of the eStatementRs property.
     * 
     * @return
     *     possible object is
     *     {@link EStatementRsType }
     *     
     */
    public EStatementRsType getEStatementRs() {
        return eStatementRs;
    }

    /**
     * Sets the value of the eStatementRs property.
     * 
     * @param value
     *     allowed object is
     *     {@link EStatementRsType }
     *     
     */
    public void setEStatementRs(EStatementRsType value) {
        this.eStatementRs = value;
    }

}
