//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.fawry.adapter_template.model.fawryType;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BalanceDetailsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="BalanceDetailsType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="ActionName" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}ActionNameType" minOccurs="0"/>
 *         <element name="ActionType" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}Identifier_Type"/>
 *         <element name="ActionNature" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}Identifier_Type"/>
 *         <element name="Amount" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         <element name="TotalTrxAmount" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         <element name="MDRAmount" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         <element name="TotalTrxLabel" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         <element name="TotalMDRLabel" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BalanceDetailsType", propOrder = {
    "actionName",
    "actionType",
    "actionNature",
    "amount",
    "totalTrxAmount",
    "mdrAmount",
    "totalTrxLabel",
    "totalMDRLabel"
})
public class BalanceDetailsType {

    @XmlElement(name = "ActionName")
    protected String actionName;
    @XmlElement(name = "ActionType", required = true)
    protected String actionType;
    @XmlElement(name = "ActionNature", required = true)
    protected String actionNature;
    @XmlElement(name = "Amount")
    protected Double amount;
    @XmlElement(name = "TotalTrxAmount")
    protected Double totalTrxAmount;
    @XmlElement(name = "MDRAmount")
    protected Double mdrAmount;
    @XmlElement(name = "TotalTrxLabel")
    protected String totalTrxLabel;
    @XmlElement(name = "TotalMDRLabel")
    protected String totalMDRLabel;

    /**
     * Gets the value of the actionName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActionName() {
        return actionName;
    }

    /**
     * Sets the value of the actionName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActionName(String value) {
        this.actionName = value;
    }

    /**
     * Gets the value of the actionType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActionType() {
        return actionType;
    }

    /**
     * Sets the value of the actionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActionType(String value) {
        this.actionType = value;
    }

    /**
     * Gets the value of the actionNature property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActionNature() {
        return actionNature;
    }

    /**
     * Sets the value of the actionNature property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActionNature(String value) {
        this.actionNature = value;
    }

    /**
     * Gets the value of the amount property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getAmount() {
        return amount;
    }

    /**
     * Sets the value of the amount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setAmount(Double value) {
        this.amount = value;
    }

    /**
     * Gets the value of the totalTrxAmount property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getTotalTrxAmount() {
        return totalTrxAmount;
    }

    /**
     * Sets the value of the totalTrxAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setTotalTrxAmount(Double value) {
        this.totalTrxAmount = value;
    }

    /**
     * Gets the value of the mdrAmount property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getMDRAmount() {
        return mdrAmount;
    }

    /**
     * Sets the value of the mdrAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setMDRAmount(Double value) {
        this.mdrAmount = value;
    }

    /**
     * Gets the value of the totalTrxLabel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTotalTrxLabel() {
        return totalTrxLabel;
    }

    /**
     * Sets the value of the totalTrxLabel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTotalTrxLabel(String value) {
        this.totalTrxLabel = value;
    }

    /**
     * Gets the value of the totalMDRLabel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTotalMDRLabel() {
        return totalMDRLabel;
    }

    /**
     * Sets the value of the totalMDRLabel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTotalMDRLabel(String value) {
        this.totalMDRLabel = value;
    }

}
