//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.fawry.adapter_template.model.fawryType;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;

import java.math.BigDecimal;
import java.math.BigInteger;


/**
 * <p>Java class for BatchDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="BatchDataType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="BatchId" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         <element name="SaleTrxCount" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         <element name="SaleTotalAmt" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         <element name="RefundTrxCount" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         <element name="RefundTotalAmt" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BatchDataType", propOrder = {
    "batchId",
    "saleTrxCount",
    "saleTotalAmt",
    "refundTrxCount",
    "refundTotalAmt"
})
public class BatchDataType {

    @XmlElement(name = "BatchId", required = true)
    protected BigInteger batchId;
    @XmlElement(name = "SaleTrxCount")
    protected BigInteger saleTrxCount;
    @XmlElement(name = "SaleTotalAmt")
    protected BigDecimal saleTotalAmt;
    @XmlElement(name = "RefundTrxCount")
    protected BigInteger refundTrxCount;
    @XmlElement(name = "RefundTotalAmt")
    protected BigDecimal refundTotalAmt;

    /**
     * Gets the value of the batchId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getBatchId() {
        return batchId;
    }

    /**
     * Sets the value of the batchId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setBatchId(BigInteger value) {
        this.batchId = value;
    }

    /**
     * Gets the value of the saleTrxCount property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSaleTrxCount() {
        return saleTrxCount;
    }

    /**
     * Sets the value of the saleTrxCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSaleTrxCount(BigInteger value) {
        this.saleTrxCount = value;
    }

    /**
     * Gets the value of the saleTotalAmt property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSaleTotalAmt() {
        return saleTotalAmt;
    }

    /**
     * Sets the value of the saleTotalAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSaleTotalAmt(BigDecimal value) {
        this.saleTotalAmt = value;
    }

    /**
     * Gets the value of the refundTrxCount property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRefundTrxCount() {
        return refundTrxCount;
    }

    /**
     * Sets the value of the refundTrxCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRefundTrxCount(BigInteger value) {
        this.refundTrxCount = value;
    }

    /**
     * Gets the value of the refundTotalAmt property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getRefundTotalAmt() {
        return refundTotalAmt;
    }

    /**
     * Sets the value of the refundTotalAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setRefundTotalAmt(BigDecimal value) {
        this.refundTotalAmt = value;
    }

}
