//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.fawry.adapter_template.model.fawryType;

import jakarta.xml.bind.annotation.*;


/**
 * <p>Java class for BatchCmnElementType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="BatchCmnElementType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="CustLangPref" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}CustLangPrefOpenEnum" minOccurs="0"/>
 *         <element name="AMessage" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}AMessageType" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BatchCmnElementType", propOrder = {
    "custLangPref",
    "aMessage"
})
@XmlSeeAlso({
    ElementRqDetailsType.class,
    ElementRsDetailsType.class
})
public class BatchCmnElementType {

    @XmlElement(name = "CustLangPref")
    protected String custLangPref;
    @XmlElement(name = "AMessage")
    protected AMessageType aMessage;

    /**
     * Gets the value of the custLangPref property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustLangPref() {
        return custLangPref;
    }

    /**
     * Sets the value of the custLangPref property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustLangPref(String value) {
        this.custLangPref = value;
    }

    /**
     * Gets the value of the aMessage property.
     * 
     * @return
     *     possible object is
     *     {@link AMessageType }
     *     
     */
    public AMessageType getAMessage() {
        return aMessage;
    }

    /**
     * Sets the value of the aMessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link AMessageType }
     *     
     */
    public void setAMessage(AMessageType value) {
        this.aMessage = value;
    }

}
