//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.fawry.adapter_template.model.fawryType;

import jakarta.xml.bind.annotation.*;

import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for BillInstInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="BillInstInfoType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="BillInqDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         <element name="BIRN">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               <maxLength value="36"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="BillInstStatus" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}BillInstStatusOpenEnum"/>
 *         <element name="BillRec" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}BillRecType" minOccurs="0"/>
 *         <element name="BIFailureCode" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BillInstInfoType", propOrder = {
    "billInqDate",
    "birn",
    "billInstStatus",
    "billRec",
    "biFailureCode"
})
public class BillInstInfoType {

    @XmlElement(name = "BillInqDate", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar billInqDate;
    @XmlElement(name = "BIRN", required = true)
    protected String birn;
    @XmlElement(name = "BillInstStatus", required = true)
    protected String billInstStatus;
    @XmlElement(name = "BillRec")
    protected BillRecType billRec;
    @XmlElement(name = "BIFailureCode")
    protected Long biFailureCode;

    /**
     * Gets the value of the billInqDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getBillInqDate() {
        return billInqDate;
    }

    /**
     * Sets the value of the billInqDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setBillInqDate(XMLGregorianCalendar value) {
        this.billInqDate = value;
    }

    /**
     * Gets the value of the birn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBIRN() {
        return birn;
    }

    /**
     * Sets the value of the birn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBIRN(String value) {
        this.birn = value;
    }

    /**
     * Gets the value of the billInstStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillInstStatus() {
        return billInstStatus;
    }

    /**
     * Sets the value of the billInstStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillInstStatus(String value) {
        this.billInstStatus = value;
    }

    /**
     * Gets the value of the billRec property.
     * 
     * @return
     *     possible object is
     *     {@link BillRecType }
     *     
     */
    public BillRecType getBillRec() {
        return billRec;
    }

    /**
     * Sets the value of the billRec property.
     * 
     * @param value
     *     allowed object is
     *     {@link BillRecType }
     *     
     */
    public void setBillRec(BillRecType value) {
        this.billRec = value;
    }

    /**
     * Gets the value of the biFailureCode property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getBIFailureCode() {
        return biFailureCode;
    }

    /**
     * Sets the value of the biFailureCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setBIFailureCode(Long value) {
        this.biFailureCode = value;
    }

}
