//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.fawry.adapter_template.model.fawryType;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BillTypeRefKeyType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="BillTypeRefKeyType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="Key" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}ExtraBillingAcctKeyTypeOpenEnum"/>
 *         <element name="Label">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               <maxLength value="80"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="Required" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         <element name="IsCnfrmRequired" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         <element name="IsPrintKeyPart" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         <element name="IsBAKeyPart" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         <element name="IsEncryptRequired" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         <element name="EncryptKeyProfile" minOccurs="0">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               <maxLength value="256"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="InputMethod" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}AcctInputMethodOpenEnum" minOccurs="0"/>
 *         <element name="IsInputMasked" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         <element name="Description" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}C512_Type" minOccurs="0"/>
 *         <element name="EnumValues" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}EnumValuesType" minOccurs="0"/>
 *         <element name="IsFavKey" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         <element name="RegEX" minOccurs="0">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               <maxLength value="1024"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="KeyHint" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}C40_Type" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BillTypeRefKeyType", propOrder = {
    "key",
    "label",
    "required",
    "isCnfrmRequired",
    "isPrintKeyPart",
    "isBAKeyPart",
    "isEncryptRequired",
    "encryptKeyProfile",
    "inputMethod",
    "isInputMasked",
    "description",
    "enumValues",
    "isFavKey",
    "regEX",
    "keyHint"
})
public class BillTypeRefKeyType {

    @XmlElement(name = "Key", required = true)
    protected String key;
    @XmlElement(name = "Label", required = true)
    protected String label;
    @XmlElement(name = "Required")
    protected Boolean required;
    @XmlElement(name = "IsCnfrmRequired")
    protected Boolean isCnfrmRequired;
    @XmlElement(name = "IsPrintKeyPart")
    protected Boolean isPrintKeyPart;
    @XmlElement(name = "IsBAKeyPart")
    protected Boolean isBAKeyPart;
    @XmlElement(name = "IsEncryptRequired")
    protected Boolean isEncryptRequired;
    @XmlElement(name = "EncryptKeyProfile")
    protected String encryptKeyProfile;
    @XmlElement(name = "InputMethod")
    protected String inputMethod;
    @XmlElement(name = "IsInputMasked")
    protected Boolean isInputMasked;
    @XmlElement(name = "Description")
    protected String description;
    @XmlElement(name = "EnumValues")
    protected EnumValuesType enumValues;
    @XmlElement(name = "IsFavKey")
    protected Boolean isFavKey;
    @XmlElement(name = "RegEX")
    protected String regEX;
    @XmlElement(name = "KeyHint")
    protected String keyHint;

    /**
     * Gets the value of the key property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKey() {
        return key;
    }

    /**
     * Sets the value of the key property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKey(String value) {
        this.key = value;
    }

    /**
     * Gets the value of the label property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLabel() {
        return label;
    }

    /**
     * Sets the value of the label property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLabel(String value) {
        this.label = value;
    }

    /**
     * Gets the value of the required property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isRequired() {
        return required;
    }

    /**
     * Sets the value of the required property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRequired(Boolean value) {
        this.required = value;
    }

    /**
     * Gets the value of the isCnfrmRequired property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsCnfrmRequired() {
        return isCnfrmRequired;
    }

    /**
     * Sets the value of the isCnfrmRequired property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsCnfrmRequired(Boolean value) {
        this.isCnfrmRequired = value;
    }

    /**
     * Gets the value of the isPrintKeyPart property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsPrintKeyPart() {
        return isPrintKeyPart;
    }

    /**
     * Sets the value of the isPrintKeyPart property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsPrintKeyPart(Boolean value) {
        this.isPrintKeyPart = value;
    }

    /**
     * Gets the value of the isBAKeyPart property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsBAKeyPart() {
        return isBAKeyPart;
    }

    /**
     * Sets the value of the isBAKeyPart property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsBAKeyPart(Boolean value) {
        this.isBAKeyPart = value;
    }

    /**
     * Gets the value of the isEncryptRequired property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsEncryptRequired() {
        return isEncryptRequired;
    }

    /**
     * Sets the value of the isEncryptRequired property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsEncryptRequired(Boolean value) {
        this.isEncryptRequired = value;
    }

    /**
     * Gets the value of the encryptKeyProfile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEncryptKeyProfile() {
        return encryptKeyProfile;
    }

    /**
     * Sets the value of the encryptKeyProfile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEncryptKeyProfile(String value) {
        this.encryptKeyProfile = value;
    }

    /**
     * Gets the value of the inputMethod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInputMethod() {
        return inputMethod;
    }

    /**
     * Sets the value of the inputMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInputMethod(String value) {
        this.inputMethod = value;
    }

    /**
     * Gets the value of the isInputMasked property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsInputMasked() {
        return isInputMasked;
    }

    /**
     * Sets the value of the isInputMasked property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsInputMasked(Boolean value) {
        this.isInputMasked = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the enumValues property.
     * 
     * @return
     *     possible object is
     *     {@link EnumValuesType }
     *     
     */
    public EnumValuesType getEnumValues() {
        return enumValues;
    }

    /**
     * Sets the value of the enumValues property.
     * 
     * @param value
     *     allowed object is
     *     {@link EnumValuesType }
     *     
     */
    public void setEnumValues(EnumValuesType value) {
        this.enumValues = value;
    }

    /**
     * Gets the value of the isFavKey property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsFavKey() {
        return isFavKey;
    }

    /**
     * Sets the value of the isFavKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsFavKey(Boolean value) {
        this.isFavKey = value;
    }

    /**
     * Gets the value of the regEX property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegEX() {
        return regEX;
    }

    /**
     * Sets the value of the regEX property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegEX(String value) {
        this.regEX = value;
    }

    /**
     * Gets the value of the keyHint property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKeyHint() {
        return keyHint;
    }

    /**
     * Sets the value of the keyHint property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKeyHint(String value) {
        this.keyHint = value;
    }

}
