//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.fawry.adapter_template.model.fawryType;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BillUploadInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="BillUploadInfoType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="BillInfo" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}BillDataType"/>
 *         <element name="BillerInfo" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}BillerDataType" minOccurs="0"/>
 *         <element name="BSPInfo" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}BSPInfoType" minOccurs="0"/>
 *         <element name="ShippingInfo" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}ShippingDataType" minOccurs="0"/>
 *         <element name="CSPCode" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}Identifier_Type"/>
 *         <element name="DeliveryMethod" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}DeliveryMethodOpenEnum"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BillUploadInfoType", propOrder = {
    "billInfo",
    "billerInfo",
    "bspInfo",
    "shippingInfo",
    "cspCode",
    "deliveryMethod"
})
public class BillUploadInfoType {

    @XmlElement(name = "BillInfo", required = true)
    protected BillDataType billInfo;
    @XmlElement(name = "BillerInfo")
    protected BillerDataType billerInfo;
    @XmlElement(name = "BSPInfo")
    protected BSPInfoType bspInfo;
    @XmlElement(name = "ShippingInfo")
    protected ShippingDataType shippingInfo;
    @XmlElement(name = "CSPCode", required = true)
    protected String cspCode;
    @XmlElement(name = "DeliveryMethod", required = true)
    protected String deliveryMethod;

    /**
     * Gets the value of the billInfo property.
     * 
     * @return
     *     possible object is
     *     {@link BillDataType }
     *     
     */
    public BillDataType getBillInfo() {
        return billInfo;
    }

    /**
     * Sets the value of the billInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link BillDataType }
     *     
     */
    public void setBillInfo(BillDataType value) {
        this.billInfo = value;
    }

    /**
     * Gets the value of the billerInfo property.
     * 
     * @return
     *     possible object is
     *     {@link BillerDataType }
     *     
     */
    public BillerDataType getBillerInfo() {
        return billerInfo;
    }

    /**
     * Sets the value of the billerInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link BillerDataType }
     *     
     */
    public void setBillerInfo(BillerDataType value) {
        this.billerInfo = value;
    }

    /**
     * Gets the value of the bspInfo property.
     * 
     * @return
     *     possible object is
     *     {@link BSPInfoType }
     *     
     */
    public BSPInfoType getBSPInfo() {
        return bspInfo;
    }

    /**
     * Sets the value of the bspInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link BSPInfoType }
     *     
     */
    public void setBSPInfo(BSPInfoType value) {
        this.bspInfo = value;
    }

    /**
     * Gets the value of the shippingInfo property.
     * 
     * @return
     *     possible object is
     *     {@link ShippingDataType }
     *     
     */
    public ShippingDataType getShippingInfo() {
        return shippingInfo;
    }

    /**
     * Sets the value of the shippingInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link ShippingDataType }
     *     
     */
    public void setShippingInfo(ShippingDataType value) {
        this.shippingInfo = value;
    }

    /**
     * Gets the value of the cspCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCSPCode() {
        return cspCode;
    }

    /**
     * Sets the value of the cspCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCSPCode(String value) {
        this.cspCode = value;
    }

    /**
     * Gets the value of the deliveryMethod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeliveryMethod() {
        return deliveryMethod;
    }

    /**
     * Sets the value of the deliveryMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeliveryMethod(String value) {
        this.deliveryMethod = value;
    }

}
