//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.fawry.adapter_template.model.fawryType;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;

import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for BillerInqRsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="BillerInqRsType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="CustId" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}CustIdType" maxOccurs="unbounded" minOccurs="0"/>
 *         <element name="RecCtrlOut" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}RecCtrlOutType" minOccurs="0"/>
 *         <element name="PmtType" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}PmtTypeOpenEnum" minOccurs="0"/>
 *         <element name="ServiceType" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}ServiceTypeOpenEnum" minOccurs="0"/>
 *         <element name="DeliveryMethod" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}DeliveryMethodOpenEnum"/>
 *         <element name="BillerRec" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}BillerRecType" maxOccurs="unbounded" minOccurs="0"/>
 *         <element name="ProfileCode" minOccurs="0">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               <maxLength value="32"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BillerInqRsType", propOrder = {
    "custId",
    "recCtrlOut",
    "pmtType",
    "serviceType",
    "deliveryMethod",
    "billerRec",
    "profileCode"
})
public class BillerInqRsType {

    @XmlElement(name = "CustId")
    protected List<CustIdType> custId;
    @XmlElement(name = "RecCtrlOut")
    protected RecCtrlOutType recCtrlOut;
    @XmlElement(name = "PmtType")
    protected String pmtType;
    @XmlElement(name = "ServiceType")
    protected String serviceType;
    @XmlElement(name = "DeliveryMethod", required = true)
    protected String deliveryMethod;
    @XmlElement(name = "BillerRec")
    protected List<BillerRecType> billerRec;
    @XmlElement(name = "ProfileCode")
    protected String profileCode;

    /**
     * Gets the value of the custId property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the custId property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCustId().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CustIdType }
     * 
     * 
     * @return
     *     The value of the custId property.
     */
    public List<CustIdType> getCustId() {
        if (custId == null) {
            custId = new ArrayList<>();
        }
        return this.custId;
    }

    /**
     * Gets the value of the recCtrlOut property.
     * 
     * @return
     *     possible object is
     *     {@link RecCtrlOutType }
     *     
     */
    public RecCtrlOutType getRecCtrlOut() {
        return recCtrlOut;
    }

    /**
     * Sets the value of the recCtrlOut property.
     * 
     * @param value
     *     allowed object is
     *     {@link RecCtrlOutType }
     *     
     */
    public void setRecCtrlOut(RecCtrlOutType value) {
        this.recCtrlOut = value;
    }

    /**
     * Gets the value of the pmtType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPmtType() {
        return pmtType;
    }

    /**
     * Sets the value of the pmtType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPmtType(String value) {
        this.pmtType = value;
    }

    /**
     * Gets the value of the serviceType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceType() {
        return serviceType;
    }

    /**
     * Sets the value of the serviceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceType(String value) {
        this.serviceType = value;
    }

    /**
     * Gets the value of the deliveryMethod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeliveryMethod() {
        return deliveryMethod;
    }

    /**
     * Sets the value of the deliveryMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeliveryMethod(String value) {
        this.deliveryMethod = value;
    }

    /**
     * Gets the value of the billerRec property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the billerRec property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBillerRec().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BillerRecType }
     * 
     * 
     * @return
     *     The value of the billerRec property.
     */
    public List<BillerRecType> getBillerRec() {
        if (billerRec == null) {
            billerRec = new ArrayList<>();
        }
        return this.billerRec;
    }

    /**
     * Gets the value of the profileCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProfileCode() {
        return profileCode;
    }

    /**
     * Sets the value of the profileCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProfileCode(String value) {
        this.profileCode = value;
    }

}
