//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.fawry.adapter_template.model.fawryType;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BillTypeTypeEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>{@code
 * <simpleType name="BillTypeTypeEnum">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <enumeration value="PROMO"/>
 *     <enumeration value="FIXED"/>
 *     <enumeration value="VARIABLE"/>
 *     <enumeration value="REG"/>
 *     <enumeration value="BILLPMT"/>
 *     <enumeration value="KYCONLY"/>
 *     <enumeration value="KYCAndPMT"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "BillTypeTypeEnum")
@XmlEnum
public enum BillTypeTypeEnum {

    PROMO("PROMO"),
    FIXED("FIXED"),
    VARIABLE("VARIABLE"),
    REG("REG"),
    BILLPMT("BILLPMT"),
    KYCONLY("KYCONLY"),
    @XmlEnumValue("KYCAndPMT")
    KYC_AND_PMT("KYCAndPMT");
    private final String value;

    BillTypeTypeEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static BillTypeTypeEnum fromValue(String v) {
        for (BillTypeTypeEnum c: BillTypeTypeEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
