//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.fawry.adapter_template.model.fawryType;

import jakarta.xml.bind.annotation.*;

import javax.xml.datatype.XMLGregorianCalendar;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for BillDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="BillDataType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="BillNumber" minOccurs="0">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               <maxLength value="64"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="BillRefNumber" minOccurs="0">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               <maxLength value="36"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="BillingAcct" minOccurs="0">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               <maxLength value="128"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="ExtraBillingAcctKeys" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}ExtraBillingAcctKeysType" minOccurs="0"/>
 *         <element name="BillerId" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}Identifier_Type" minOccurs="0"/>
 *         <element name="BillTypeCode" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         <element name="BillTypeName" minOccurs="0">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               <maxLength value="128"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="BillDesc" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}BillDescType" minOccurs="0"/>
 *         <element name="BillStatus" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}BillStatusOpenEnum" minOccurs="0"/>
 *         <element name="BillSummAmt" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}BillSummAmtType" maxOccurs="unbounded" minOccurs="0"/>
 *         <element name="OpenDt" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         <element name="CloseDt" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         <element name="DueDt" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         <element name="ExpDt" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         <element name="IssueDt" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         <element name="CustomValue" minOccurs="0">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               <maxLength value="512"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="PaymentOption" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}PaymentOptionOpenEnum" minOccurs="0"/>
 *         <element name="Items" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}ItemsType" minOccurs="0"/>
 *         <element name="SubBills" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}SubBillsDataType" minOccurs="0"/>
 *         <element name="BillLabel" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}BillLabelType" minOccurs="0"/>
 *         <element name="SubBillCustomProperties" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}CustomPropertiesType" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BillDataType", propOrder = {
    "billNumber",
    "billRefNumber",
    "billingAcct",
    "extraBillingAcctKeys",
    "billerId",
    "billTypeCode",
    "billTypeName",
    "billDesc",
    "billStatus",
    "billSummAmt",
    "openDt",
    "closeDt",
    "dueDt",
    "expDt",
    "issueDt",
    "customValue",
    "paymentOption",
    "items",
    "subBills",
    "billLabel",
    "subBillCustomProperties"
})
public class BillDataType {

    @XmlElement(name = "BillNumber")
    protected String billNumber;
    @XmlElement(name = "BillRefNumber")
    protected String billRefNumber;
    @XmlElement(name = "BillingAcct")
    protected String billingAcct;
    @XmlElement(name = "ExtraBillingAcctKeys")
    protected ExtraBillingAcctKeysType extraBillingAcctKeys;
    @XmlElement(name = "BillerId")
    protected String billerId;
    @XmlElement(name = "BillTypeCode")
    protected Long billTypeCode;
    @XmlElement(name = "BillTypeName")
    protected String billTypeName;
    @XmlElement(name = "BillDesc")
    protected BillDescType billDesc;
    @XmlElement(name = "BillStatus")
    protected String billStatus;
    @XmlElement(name = "BillSummAmt")
    protected List<BillSummAmtType> billSummAmt;
    @XmlElement(name = "OpenDt")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar openDt;
    @XmlElement(name = "CloseDt")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar closeDt;
    @XmlElement(name = "DueDt")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dueDt;
    @XmlElement(name = "ExpDt")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar expDt;
    @XmlElement(name = "IssueDt")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar issueDt;
    @XmlElement(name = "CustomValue")
    protected String customValue;
    @XmlElement(name = "PaymentOption")
    protected String paymentOption;
    @XmlElement(name = "Items")
    protected ItemsType items;
    @XmlElement(name = "SubBills")
    protected SubBillsDataType subBills;
    @XmlElement(name = "BillLabel")
    protected String billLabel;
    @XmlElement(name = "SubBillCustomProperties")
    protected CustomPropertiesType subBillCustomProperties;

    /**
     * Gets the value of the billNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillNumber() {
        return billNumber;
    }

    /**
     * Sets the value of the billNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillNumber(String value) {
        this.billNumber = value;
    }

    /**
     * Gets the value of the billRefNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillRefNumber() {
        return billRefNumber;
    }

    /**
     * Sets the value of the billRefNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillRefNumber(String value) {
        this.billRefNumber = value;
    }

    /**
     * Gets the value of the billingAcct property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillingAcct() {
        return billingAcct;
    }

    /**
     * Sets the value of the billingAcct property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillingAcct(String value) {
        this.billingAcct = value;
    }

    /**
     * Gets the value of the extraBillingAcctKeys property.
     * 
     * @return
     *     possible object is
     *     {@link ExtraBillingAcctKeysType }
     *     
     */
    public ExtraBillingAcctKeysType getExtraBillingAcctKeys() {
        return extraBillingAcctKeys;
    }

    /**
     * Sets the value of the extraBillingAcctKeys property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExtraBillingAcctKeysType }
     *     
     */
    public void setExtraBillingAcctKeys(ExtraBillingAcctKeysType value) {
        this.extraBillingAcctKeys = value;
    }

    /**
     * Gets the value of the billerId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillerId() {
        return billerId;
    }

    /**
     * Sets the value of the billerId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillerId(String value) {
        this.billerId = value;
    }

    /**
     * Gets the value of the billTypeCode property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getBillTypeCode() {
        return billTypeCode;
    }

    /**
     * Sets the value of the billTypeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setBillTypeCode(Long value) {
        this.billTypeCode = value;
    }

    /**
     * Gets the value of the billTypeName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillTypeName() {
        return billTypeName;
    }

    /**
     * Sets the value of the billTypeName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillTypeName(String value) {
        this.billTypeName = value;
    }

    /**
     * Gets the value of the billDesc property.
     * 
     * @return
     *     possible object is
     *     {@link BillDescType }
     *     
     */
    public BillDescType getBillDesc() {
        return billDesc;
    }

    /**
     * Sets the value of the billDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link BillDescType }
     *     
     */
    public void setBillDesc(BillDescType value) {
        this.billDesc = value;
    }

    /**
     * Gets the value of the billStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillStatus() {
        return billStatus;
    }

    /**
     * Sets the value of the billStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillStatus(String value) {
        this.billStatus = value;
    }

    /**
     * Gets the value of the billSummAmt property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the billSummAmt property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBillSummAmt().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BillSummAmtType }
     * 
     * 
     * @return
     *     The value of the billSummAmt property.
     */
    public List<BillSummAmtType> getBillSummAmt() {
        if (billSummAmt == null) {
            billSummAmt = new ArrayList<>();
        }
        return this.billSummAmt;
    }

    /**
     * Gets the value of the openDt property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getOpenDt() {
        return openDt;
    }

    /**
     * Sets the value of the openDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setOpenDt(XMLGregorianCalendar value) {
        this.openDt = value;
    }

    /**
     * Gets the value of the closeDt property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCloseDt() {
        return closeDt;
    }

    /**
     * Sets the value of the closeDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCloseDt(XMLGregorianCalendar value) {
        this.closeDt = value;
    }

    /**
     * Gets the value of the dueDt property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDueDt() {
        return dueDt;
    }

    /**
     * Sets the value of the dueDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDueDt(XMLGregorianCalendar value) {
        this.dueDt = value;
    }

    /**
     * Gets the value of the expDt property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getExpDt() {
        return expDt;
    }

    /**
     * Sets the value of the expDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setExpDt(XMLGregorianCalendar value) {
        this.expDt = value;
    }

    /**
     * Gets the value of the issueDt property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getIssueDt() {
        return issueDt;
    }

    /**
     * Sets the value of the issueDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setIssueDt(XMLGregorianCalendar value) {
        this.issueDt = value;
    }

    /**
     * Gets the value of the customValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomValue() {
        return customValue;
    }

    /**
     * Sets the value of the customValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomValue(String value) {
        this.customValue = value;
    }

    /**
     * Gets the value of the paymentOption property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaymentOption() {
        return paymentOption;
    }

    /**
     * Sets the value of the paymentOption property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymentOption(String value) {
        this.paymentOption = value;
    }

    /**
     * Gets the value of the items property.
     * 
     * @return
     *     possible object is
     *     {@link ItemsType }
     *     
     */
    public ItemsType getItems() {
        return items;
    }

    /**
     * Sets the value of the items property.
     * 
     * @param value
     *     allowed object is
     *     {@link ItemsType }
     *     
     */
    public void setItems(ItemsType value) {
        this.items = value;
    }

    /**
     * Gets the value of the subBills property.
     * 
     * @return
     *     possible object is
     *     {@link SubBillsDataType }
     *     
     */
    public SubBillsDataType getSubBills() {
        return subBills;
    }

    /**
     * Sets the value of the subBills property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubBillsDataType }
     *     
     */
    public void setSubBills(SubBillsDataType value) {
        this.subBills = value;
    }

    /**
     * Gets the value of the billLabel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillLabel() {
        return billLabel;
    }

    /**
     * Sets the value of the billLabel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillLabel(String value) {
        this.billLabel = value;
    }

    /**
     * Gets the value of the subBillCustomProperties property.
     * 
     * @return
     *     possible object is
     *     {@link CustomPropertiesType }
     *     
     */
    public CustomPropertiesType getSubBillCustomProperties() {
        return subBillCustomProperties;
    }

    /**
     * Sets the value of the subBillCustomProperties property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustomPropertiesType }
     *     
     */
    public void setSubBillCustomProperties(CustomPropertiesType value) {
        this.subBillCustomProperties = value;
    }

}
