//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.fawry.adapter_template.model.fawryType;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BillSummAmtCodeEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>{@code
 * <simpleType name="BillSummAmtCodeEnum">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <enumeration value="TotalAmtDue"/>
 *     <enumeration value="Fees"/>
 *     <enumeration value="Charges"/>
 *     <enumeration value="ShippingAmt"/>
 *     <enumeration value="EcomCAF"/>
 *     <enumeration value="BAF"/>
 *     <enumeration value="VAT"/>
 *     <enumeration value="DownPmtAmt"/>
 *     <enumeration value="TotalOrderAmt"/>
 *     <enumeration value="TIPS"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "BillSummAmtCodeEnum")
@XmlEnum
public enum BillSummAmtCodeEnum {

    @XmlEnumValue("TotalAmtDue")
    TOTAL_AMT_DUE("TotalAmtDue"),
    @XmlEnumValue("Fees")
    FEES("Fees"),
    @XmlEnumValue("Charges")
    CHARGES("Charges"),
    @XmlEnumValue("ShippingAmt")
    SHIPPING_AMT("ShippingAmt"),
    @XmlEnumValue("EcomCAF")
    ECOM_CAF("EcomCAF"),
    BAF("BAF"),
    VAT("VAT"),
    @XmlEnumValue("DownPmtAmt")
    DOWN_PMT_AMT("DownPmtAmt"),
    @XmlEnumValue("TotalOrderAmt")
    TOTAL_ORDER_AMT("TotalOrderAmt"),
    TIPS("TIPS");
    private final String value;

    BillSummAmtCodeEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static BillSummAmtCodeEnum fromValue(String v) {
        for (BillSummAmtCodeEnum c: BillSummAmtCodeEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
