//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.fawry.adapter_template.model.fawryType;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;

import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for BillInqRqType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="BillInqRqType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="EnrollmentUID" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}NC36_Type" minOccurs="0"/>
 *         <element name="CustId" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}CustIdType" maxOccurs="unbounded" minOccurs="0"/>
 *         <element name="RecCtrlIn" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}RecCtrlInType" minOccurs="0"/>
 *         <element name="SelRangeDt" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}SelRangeDtType" minOccurs="0"/>
 *         <element name="IncOpenAmt" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         <element name="BillNumber" minOccurs="0">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               <maxLength value="64"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="BillingAcct" minOccurs="0">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               <maxLength value="128"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="ExtraBillingAcctKeys" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}ExtraBillingAcctKeysType" minOccurs="0"/>
 *         <element name="BillerId" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}Identifier_Type" minOccurs="0"/>
 *         <element name="BankId" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}Identifier_Type" minOccurs="0"/>
 *         <element name="PmtType" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}PmtTypeOpenEnum" minOccurs="0"/>
 *         <element name="BillTypeCode" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         <element name="ServiceType" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}ServiceTypeOpenEnum" minOccurs="0"/>
 *         <element name="DeliveryMethod" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}DeliveryMethodOpenEnum"/>
 *         <element name="ProfileCode" minOccurs="0">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               <maxLength value="32"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="InputMethod" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}AcctInputMethodOpenEnum" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BillInqRqType", propOrder = {
    "enrollmentUID",
    "custId",
    "recCtrlIn",
    "selRangeDt",
    "incOpenAmt",
    "billNumber",
    "billingAcct",
    "extraBillingAcctKeys",
    "billerId",
    "bankId",
    "pmtType",
    "billTypeCode",
    "serviceType",
    "deliveryMethod",
    "profileCode",
    "inputMethod"
})
public class BillInqRqType {

    @XmlElement(name = "EnrollmentUID")
    protected String enrollmentUID;
    @XmlElement(name = "CustId")
    protected List<CustIdType> custId;
    @XmlElement(name = "RecCtrlIn")
    protected RecCtrlInType recCtrlIn;
    @XmlElement(name = "SelRangeDt")
    protected SelRangeDtType selRangeDt;
    @XmlElement(name = "IncOpenAmt")
    protected Boolean incOpenAmt;
    @XmlElement(name = "BillNumber")
    protected String billNumber;
    @XmlElement(name = "BillingAcct")
    protected String billingAcct;
    @XmlElement(name = "ExtraBillingAcctKeys")
    protected ExtraBillingAcctKeysType extraBillingAcctKeys;
    @XmlElement(name = "BillerId")
    protected String billerId;
    @XmlElement(name = "BankId")
    protected String bankId;
    @XmlElement(name = "PmtType")
    protected String pmtType;
    @XmlElement(name = "BillTypeCode")
    protected Long billTypeCode;
    @XmlElement(name = "ServiceType")
    protected String serviceType;
    @XmlElement(name = "DeliveryMethod", required = true)
    protected String deliveryMethod;
    @XmlElement(name = "ProfileCode")
    protected String profileCode;
    @XmlElement(name = "InputMethod")
    protected String inputMethod;

    /**
     * Gets the value of the enrollmentUID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEnrollmentUID() {
        return enrollmentUID;
    }

    /**
     * Sets the value of the enrollmentUID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEnrollmentUID(String value) {
        this.enrollmentUID = value;
    }

    /**
     * Gets the value of the custId property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the custId property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCustId().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CustIdType }
     * 
     * 
     * @return
     *     The value of the custId property.
     */
    public List<CustIdType> getCustId() {
        if (custId == null) {
            custId = new ArrayList<>();
        }
        return this.custId;
    }

    /**
     * Gets the value of the recCtrlIn property.
     * 
     * @return
     *     possible object is
     *     {@link RecCtrlInType }
     *     
     */
    public RecCtrlInType getRecCtrlIn() {
        return recCtrlIn;
    }

    /**
     * Sets the value of the recCtrlIn property.
     * 
     * @param value
     *     allowed object is
     *     {@link RecCtrlInType }
     *     
     */
    public void setRecCtrlIn(RecCtrlInType value) {
        this.recCtrlIn = value;
    }

    /**
     * Gets the value of the selRangeDt property.
     * 
     * @return
     *     possible object is
     *     {@link SelRangeDtType }
     *     
     */
    public SelRangeDtType getSelRangeDt() {
        return selRangeDt;
    }

    /**
     * Sets the value of the selRangeDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link SelRangeDtType }
     *     
     */
    public void setSelRangeDt(SelRangeDtType value) {
        this.selRangeDt = value;
    }

    /**
     * Gets the value of the incOpenAmt property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIncOpenAmt() {
        return incOpenAmt;
    }

    /**
     * Sets the value of the incOpenAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIncOpenAmt(Boolean value) {
        this.incOpenAmt = value;
    }

    /**
     * Gets the value of the billNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillNumber() {
        return billNumber;
    }

    /**
     * Sets the value of the billNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillNumber(String value) {
        this.billNumber = value;
    }

    /**
     * Gets the value of the billingAcct property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillingAcct() {
        return billingAcct;
    }

    /**
     * Sets the value of the billingAcct property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillingAcct(String value) {
        this.billingAcct = value;
    }

    /**
     * Gets the value of the extraBillingAcctKeys property.
     * 
     * @return
     *     possible object is
     *     {@link ExtraBillingAcctKeysType }
     *     
     */
    public ExtraBillingAcctKeysType getExtraBillingAcctKeys() {
        return extraBillingAcctKeys;
    }

    /**
     * Sets the value of the extraBillingAcctKeys property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExtraBillingAcctKeysType }
     *     
     */
    public void setExtraBillingAcctKeys(ExtraBillingAcctKeysType value) {
        this.extraBillingAcctKeys = value;
    }

    /**
     * Gets the value of the billerId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillerId() {
        return billerId;
    }

    /**
     * Sets the value of the billerId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillerId(String value) {
        this.billerId = value;
    }

    /**
     * Gets the value of the bankId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBankId() {
        return bankId;
    }

    /**
     * Sets the value of the bankId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBankId(String value) {
        this.bankId = value;
    }

    /**
     * Gets the value of the pmtType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPmtType() {
        return pmtType;
    }

    /**
     * Sets the value of the pmtType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPmtType(String value) {
        this.pmtType = value;
    }

    /**
     * Gets the value of the billTypeCode property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getBillTypeCode() {
        return billTypeCode;
    }

    /**
     * Sets the value of the billTypeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setBillTypeCode(Long value) {
        this.billTypeCode = value;
    }

    /**
     * Gets the value of the serviceType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceType() {
        return serviceType;
    }

    /**
     * Sets the value of the serviceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceType(String value) {
        this.serviceType = value;
    }

    /**
     * Gets the value of the deliveryMethod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeliveryMethod() {
        return deliveryMethod;
    }

    /**
     * Sets the value of the deliveryMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeliveryMethod(String value) {
        this.deliveryMethod = value;
    }

    /**
     * Gets the value of the profileCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProfileCode() {
        return profileCode;
    }

    /**
     * Sets the value of the profileCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProfileCode(String value) {
        this.profileCode = value;
    }

    /**
     * Gets the value of the inputMethod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInputMethod() {
        return inputMethod;
    }

    /**
     * Sets the value of the inputMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInputMethod(String value) {
        this.inputMethod = value;
    }

}
