//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.fawry.adapter_template.model.fawryType;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;

import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for BSPInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="BSPInfoType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="BSPCode" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}Identifier_Type"/>
 *         <element name="NotifyEmail" maxOccurs="unbounded" minOccurs="0">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               <maxLength value="50"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="BillPresenter" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}BillPresenterType" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BSPInfoType", propOrder = {
    "bspCode",
    "notifyEmail",
    "billPresenter"
})
public class BSPInfoType {

    @XmlElement(name = "BSPCode", required = true)
    protected String bspCode;
    @XmlElement(name = "NotifyEmail")
    protected List<String> notifyEmail;
    @XmlElement(name = "BillPresenter")
    protected BillPresenterType billPresenter;

    /**
     * Gets the value of the bspCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBSPCode() {
        return bspCode;
    }

    /**
     * Sets the value of the bspCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBSPCode(String value) {
        this.bspCode = value;
    }

    /**
     * Gets the value of the notifyEmail property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the notifyEmail property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNotifyEmail().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     * @return
     *     The value of the notifyEmail property.
     */
    public List<String> getNotifyEmail() {
        if (notifyEmail == null) {
            notifyEmail = new ArrayList<>();
        }
        return this.notifyEmail;
    }

    /**
     * Gets the value of the billPresenter property.
     * 
     * @return
     *     possible object is
     *     {@link BillPresenterType }
     *     
     */
    public BillPresenterType getBillPresenter() {
        return billPresenter;
    }

    /**
     * Sets the value of the billPresenter property.
     * 
     * @param value
     *     allowed object is
     *     {@link BillPresenterType }
     *     
     */
    public void setBillPresenter(BillPresenterType value) {
        this.billPresenter = value;
    }

}
