//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.fawry.adapter_template.model.fawryType;

import jakarta.xml.bind.annotation.*;

import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for CardAcctIdType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="CardAcctIdType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="AcctId" minOccurs="0">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               <minLength value="0"/>
 *               <maxLength value="36"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="AcctType" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}AcctTypeOpenEnum" minOccurs="0"/>
 *         <element name="CardName" minOccurs="0">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               <maxLength value="256"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="IssuerBankId" minOccurs="0">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               <maxLength value="36"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="Status" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}CreditCardStatusOpenEnum" minOccurs="0"/>
 *         <element name="RegisterationDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         <element name="BlockingDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         <element name="CardExpiryDate" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}CardExpiryDateType" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CardAcctIdType", propOrder = {
    "acctId",
    "acctType",
    "cardName",
    "issuerBankId",
    "status",
    "registerationDate",
    "blockingDate",
    "cardExpiryDate"
})
public class CardAcctIdType {

    @XmlElement(name = "AcctId")
    protected String acctId;
    @XmlElement(name = "AcctType")
    protected String acctType;
    @XmlElement(name = "CardName")
    protected String cardName;
    @XmlElement(name = "IssuerBankId")
    protected String issuerBankId;
    @XmlElement(name = "Status")
    protected String status;
    @XmlElement(name = "RegisterationDate")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar registerationDate;
    @XmlElement(name = "BlockingDate")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar blockingDate;
    @XmlElement(name = "CardExpiryDate")
    protected CardExpiryDateType cardExpiryDate;

    /**
     * Gets the value of the acctId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAcctId() {
        return acctId;
    }

    /**
     * Sets the value of the acctId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAcctId(String value) {
        this.acctId = value;
    }

    /**
     * Gets the value of the acctType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAcctType() {
        return acctType;
    }

    /**
     * Sets the value of the acctType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAcctType(String value) {
        this.acctType = value;
    }

    /**
     * Gets the value of the cardName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardName() {
        return cardName;
    }

    /**
     * Sets the value of the cardName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardName(String value) {
        this.cardName = value;
    }

    /**
     * Gets the value of the issuerBankId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIssuerBankId() {
        return issuerBankId;
    }

    /**
     * Sets the value of the issuerBankId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIssuerBankId(String value) {
        this.issuerBankId = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the registerationDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getRegisterationDate() {
        return registerationDate;
    }

    /**
     * Sets the value of the registerationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setRegisterationDate(XMLGregorianCalendar value) {
        this.registerationDate = value;
    }

    /**
     * Gets the value of the blockingDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getBlockingDate() {
        return blockingDate;
    }

    /**
     * Sets the value of the blockingDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setBlockingDate(XMLGregorianCalendar value) {
        this.blockingDate = value;
    }

    /**
     * Gets the value of the cardExpiryDate property.
     * 
     * @return
     *     possible object is
     *     {@link CardExpiryDateType }
     *     
     */
    public CardExpiryDateType getCardExpiryDate() {
        return cardExpiryDate;
    }

    /**
     * Sets the value of the cardExpiryDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link CardExpiryDateType }
     *     
     */
    public void setCardExpiryDate(CardExpiryDateType value) {
        this.cardExpiryDate = value;
    }

}
