//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.fawry.adapter_template.model.fawryType;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CategoryDetailsRecType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="CategoryDetailsRecType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="CategoryCode" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}Identifier_Type"/>
 *         <element name="NamePrimLang" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}C40_Type"/>
 *         <element name="NameSecLang" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}C160_Type"/>
 *         <element name="DescPrimLang" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}C80_Type" minOccurs="0"/>
 *         <element name="DescSecLang" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}C320_Type" minOccurs="0"/>
 *         <element name="CategoryStatus" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}CategoryStatusOpenEnum"/>
 *         <element name="IsDefault" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         <element name="VelocityMeasures" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}VelocityMeasuresType" minOccurs="0"/>
 *         <element name="CategoryBillTypes" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}CategoryBillTypes" minOccurs="0"/>
 *         <element name="ProfileCode" minOccurs="0">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               <maxLength value="32"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="AllowedCustTypes" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}AllowedCustTypesType" minOccurs="0"/>
 *         <element name="CategoryType" minOccurs="0">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               <maxLength value="32"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CategoryDetailsRecType", propOrder = {
    "categoryCode",
    "namePrimLang",
    "nameSecLang",
    "descPrimLang",
    "descSecLang",
    "categoryStatus",
    "isDefault",
    "velocityMeasures",
    "categoryBillTypes",
    "profileCode",
    "allowedCustTypes",
    "categoryType"
})
public class CategoryDetailsRecType {

    @XmlElement(name = "CategoryCode", required = true)
    protected String categoryCode;
    @XmlElement(name = "NamePrimLang", required = true)
    protected String namePrimLang;
    @XmlElement(name = "NameSecLang", required = true)
    protected String nameSecLang;
    @XmlElement(name = "DescPrimLang")
    protected String descPrimLang;
    @XmlElement(name = "DescSecLang")
    protected String descSecLang;
    @XmlElement(name = "CategoryStatus", required = true)
    protected String categoryStatus;
    @XmlElement(name = "IsDefault")
    protected boolean isDefault;
    @XmlElement(name = "VelocityMeasures")
    protected VelocityMeasuresType velocityMeasures;
    @XmlElement(name = "CategoryBillTypes")
    protected CategoryBillTypes categoryBillTypes;
    @XmlElement(name = "ProfileCode")
    protected String profileCode;
    @XmlElement(name = "AllowedCustTypes")
    protected AllowedCustTypesType allowedCustTypes;
    @XmlElement(name = "CategoryType")
    protected String categoryType;

    /**
     * Gets the value of the categoryCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCategoryCode() {
        return categoryCode;
    }

    /**
     * Sets the value of the categoryCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCategoryCode(String value) {
        this.categoryCode = value;
    }

    /**
     * Gets the value of the namePrimLang property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNamePrimLang() {
        return namePrimLang;
    }

    /**
     * Sets the value of the namePrimLang property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNamePrimLang(String value) {
        this.namePrimLang = value;
    }

    /**
     * Gets the value of the nameSecLang property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameSecLang() {
        return nameSecLang;
    }

    /**
     * Sets the value of the nameSecLang property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameSecLang(String value) {
        this.nameSecLang = value;
    }

    /**
     * Gets the value of the descPrimLang property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescPrimLang() {
        return descPrimLang;
    }

    /**
     * Sets the value of the descPrimLang property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescPrimLang(String value) {
        this.descPrimLang = value;
    }

    /**
     * Gets the value of the descSecLang property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescSecLang() {
        return descSecLang;
    }

    /**
     * Sets the value of the descSecLang property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescSecLang(String value) {
        this.descSecLang = value;
    }

    /**
     * Gets the value of the categoryStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCategoryStatus() {
        return categoryStatus;
    }

    /**
     * Sets the value of the categoryStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCategoryStatus(String value) {
        this.categoryStatus = value;
    }

    /**
     * Gets the value of the isDefault property.
     * 
     */
    public boolean isIsDefault() {
        return isDefault;
    }

    /**
     * Sets the value of the isDefault property.
     * 
     */
    public void setIsDefault(boolean value) {
        this.isDefault = value;
    }

    /**
     * Gets the value of the velocityMeasures property.
     * 
     * @return
     *     possible object is
     *     {@link VelocityMeasuresType }
     *     
     */
    public VelocityMeasuresType getVelocityMeasures() {
        return velocityMeasures;
    }

    /**
     * Sets the value of the velocityMeasures property.
     * 
     * @param value
     *     allowed object is
     *     {@link VelocityMeasuresType }
     *     
     */
    public void setVelocityMeasures(VelocityMeasuresType value) {
        this.velocityMeasures = value;
    }

    /**
     * Gets the value of the categoryBillTypes property.
     * 
     * @return
     *     possible object is
     *     {@link CategoryBillTypes }
     *     
     */
    public CategoryBillTypes getCategoryBillTypes() {
        return categoryBillTypes;
    }

    /**
     * Sets the value of the categoryBillTypes property.
     * 
     * @param value
     *     allowed object is
     *     {@link CategoryBillTypes }
     *     
     */
    public void setCategoryBillTypes(CategoryBillTypes value) {
        this.categoryBillTypes = value;
    }

    /**
     * Gets the value of the profileCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProfileCode() {
        return profileCode;
    }

    /**
     * Sets the value of the profileCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProfileCode(String value) {
        this.profileCode = value;
    }

    /**
     * Gets the value of the allowedCustTypes property.
     * 
     * @return
     *     possible object is
     *     {@link AllowedCustTypesType }
     *     
     */
    public AllowedCustTypesType getAllowedCustTypes() {
        return allowedCustTypes;
    }

    /**
     * Sets the value of the allowedCustTypes property.
     * 
     * @param value
     *     allowed object is
     *     {@link AllowedCustTypesType }
     *     
     */
    public void setAllowedCustTypes(AllowedCustTypesType value) {
        this.allowedCustTypes = value;
    }

    /**
     * Gets the value of the categoryType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCategoryType() {
        return categoryType;
    }

    /**
     * Sets the value of the categoryType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCategoryType(String value) {
        this.categoryType = value;
    }

}
