//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.fawry.adapter_template.model.fawryType;

import jakarta.xml.bind.annotation.*;


/**
 * <p>Java class for ChunkStartDelimiter complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="ChunkStartDelimiter">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="ElementTypeCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="ElementUsageCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ChunkStartDelimiter", propOrder = {
    "elementTypeCode",
    "elementUsageCode"
})
@XmlSeeAlso({
    ChunkEndDelimiter.class
})
public class ChunkStartDelimiter {

    @XmlElement(name = "ElementTypeCode", required = true)
    protected String elementTypeCode;
    @XmlElement(name = "ElementUsageCode")
    protected String elementUsageCode;

    /**
     * Gets the value of the elementTypeCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getElementTypeCode() {
        return elementTypeCode;
    }

    /**
     * Sets the value of the elementTypeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setElementTypeCode(String value) {
        this.elementTypeCode = value;
    }

    /**
     * Gets the value of the elementUsageCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getElementUsageCode() {
        return elementUsageCode;
    }

    /**
     * Sets the value of the elementUsageCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setElementUsageCode(String value) {
        this.elementUsageCode = value;
    }

}
