//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.fawry.adapter_template.model.fawryType;

import jakarta.xml.bind.annotation.*;

import javax.xml.datatype.XMLGregorianCalendar;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for CustDataRsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="CustDataRsType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="CustIds" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}CustIdsType" minOccurs="0"/>
 *         <element name="RecCtrlOut" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}RecCtrlOutType" minOccurs="0"/>
 *         <element name="OptType" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}OptTypeEnum" minOccurs="0"/>
 *         <element name="CustType" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}CustTypeOpenEnum" minOccurs="0"/>
 *         <element name="CustStatus" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}CustStatusEnum" minOccurs="0"/>
 *         <element name="Name" minOccurs="0">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               <maxLength value="200"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="MiddleName" minOccurs="0">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               <maxLength value="200"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="SecondaryName" minOccurs="0">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               <maxLength value="200"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="SecondaryMiddleName" minOccurs="0">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               <maxLength value="200"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="SecondaryLastName" minOccurs="0">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               <maxLength value="200"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="MotherFirstName" minOccurs="0">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               <maxLength value="200"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="MotherMiddleName" minOccurs="0">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               <maxLength value="200"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="MotherLastName" minOccurs="0">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               <maxLength value="200"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="NationalityCode" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}NationalityCodeOpenEnum" minOccurs="0"/>
 *         <element name="PrimaryBranchCode" minOccurs="0">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               <maxLength value="36"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="DeactivationReason" minOccurs="0">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               <maxLength value="256"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="IsAutoArchive" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         <element name="AutoArchivePeriod" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         <element name="CustCategory" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}Identifier_Type" minOccurs="0"/>
 *         <element name="IsCCardEnabled" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         <element name="ContactInfo" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}ContactInfoType" maxOccurs="unbounded" minOccurs="0"/>
 *         <element name="SourceOfFunds" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}SourceOfFundsType" minOccurs="0"/>
 *         <element name="FawryCustNumber" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}FawryCustNumberType" minOccurs="0"/>
 *         <element name="LastName" minOccurs="0">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               <maxLength value="200"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="BirthDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         <element name="LinkCustomerReg" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         <element name="ActivationCode" minOccurs="0">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               <maxLength value="36"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="HasCCardWhiteList" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         <element name="CCardWhiteList" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}CardWhiteList" minOccurs="0"/>
 *         <element name="CustomerUsedCards" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}CustomerUsedCards" minOccurs="0"/>
 *         <element name="Gender" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         <element name="CustPhoto" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         <element name="MartialStatus" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}MartialStatusOpenEnum" minOccurs="0"/>
 *         <element name="CustAddresses" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}CustAddressesType" minOccurs="0"/>
 *         <element name="DashboardViewingType" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}DashboardViewingTypeEnum" minOccurs="0"/>
 *         <element name="KYCLevel" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}KYCLevelOpenEnum" minOccurs="0"/>
 *         <element name="BirthPlace" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}PlaceOfBirthType" minOccurs="0"/>
 *         <element name="OtherNationalityCode" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}NationalityCodeOpenEnum" minOccurs="0"/>
 *         <element name="HasBankAcct" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         <element name="JobTitle" minOccurs="0">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               <maxLength value="512"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="MonthlySalary" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         <element name="CompanyName" minOccurs="0">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               <maxLength value="256"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="Memo" minOccurs="0">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               <maxLength value="512"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="ExternalWLTCode" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}C128_Type" minOccurs="0"/>
 *         <element name="BusinessDomain" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}C128_Type" minOccurs="0"/>
 *         <element name="IsSelfReg" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         <element name="RegVerMethod" minOccurs="0">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               <maxLength value="128"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="CustPhotoBinary" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0"/>
 *         <element name="CustValStatus" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}CustStatusEnum" minOccurs="0"/>
 *         <element name="MasterAcctID" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}C128_Type" minOccurs="0"/>
 *         <element name="CustomerSubscriptions" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}CustomerSubscriptionsType" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CustDataRsType", propOrder = {
    "custIds",
    "recCtrlOut",
    "optType",
    "custType",
    "custStatus",
    "name",
    "middleName",
    "secondaryName",
    "secondaryMiddleName",
    "secondaryLastName",
    "motherFirstName",
    "motherMiddleName",
    "motherLastName",
    "nationalityCode",
    "primaryBranchCode",
    "deactivationReason",
    "isAutoArchive",
    "autoArchivePeriod",
    "custCategory",
    "isCCardEnabled",
    "contactInfo",
    "sourceOfFunds",
    "fawryCustNumber",
    "lastName",
    "birthDate",
    "linkCustomerReg",
    "activationCode",
    "hasCCardWhiteList",
    "cCardWhiteList",
    "customerUsedCards",
    "gender",
    "custPhoto",
    "martialStatus",
    "custAddresses",
    "dashboardViewingType",
    "kycLevel",
    "birthPlace",
    "otherNationalityCode",
    "hasBankAcct",
    "jobTitle",
    "monthlySalary",
    "companyName",
    "memo",
    "externalWLTCode",
    "businessDomain",
    "isSelfReg",
    "regVerMethod",
    "custPhotoBinary",
    "custValStatus",
    "masterAcctID",
    "customerSubscriptions"
})
public class CustDataRsType {

    @XmlElement(name = "CustIds")
    protected CustIdsType custIds;
    @XmlElement(name = "RecCtrlOut")
    protected RecCtrlOutType recCtrlOut;
    @XmlElement(name = "OptType")
    @XmlSchemaType(name = "string")
    protected OptTypeEnum optType;
    @XmlElement(name = "CustType")
    protected String custType;
    @XmlElement(name = "CustStatus")
    @XmlSchemaType(name = "string")
    protected CustStatusEnum custStatus;
    @XmlElement(name = "Name")
    protected String name;
    @XmlElement(name = "MiddleName")
    protected String middleName;
    @XmlElement(name = "SecondaryName")
    protected String secondaryName;
    @XmlElement(name = "SecondaryMiddleName")
    protected String secondaryMiddleName;
    @XmlElement(name = "SecondaryLastName")
    protected String secondaryLastName;
    @XmlElement(name = "MotherFirstName")
    protected String motherFirstName;
    @XmlElement(name = "MotherMiddleName")
    protected String motherMiddleName;
    @XmlElement(name = "MotherLastName")
    protected String motherLastName;
    @XmlElement(name = "NationalityCode")
    protected String nationalityCode;
    @XmlElement(name = "PrimaryBranchCode")
    protected String primaryBranchCode;
    @XmlElement(name = "DeactivationReason")
    protected String deactivationReason;
    @XmlElement(name = "IsAutoArchive")
    protected Boolean isAutoArchive;
    @XmlElement(name = "AutoArchivePeriod")
    protected Long autoArchivePeriod;
    @XmlElement(name = "CustCategory")
    protected String custCategory;
    @XmlElement(name = "IsCCardEnabled")
    protected Boolean isCCardEnabled;
    @XmlElement(name = "ContactInfo")
    protected List<ContactInfoType> contactInfo;
    @XmlElement(name = "SourceOfFunds")
    protected SourceOfFundsType sourceOfFunds;
    @XmlElement(name = "FawryCustNumber")
    protected String fawryCustNumber;
    @XmlElement(name = "LastName")
    protected String lastName;
    @XmlElement(name = "BirthDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar birthDate;
    @XmlElement(name = "LinkCustomerReg")
    protected Boolean linkCustomerReg;
    @XmlElement(name = "ActivationCode")
    protected String activationCode;
    @XmlElement(name = "HasCCardWhiteList")
    protected Boolean hasCCardWhiteList;
    @XmlElement(name = "CCardWhiteList")
    protected CardWhiteList cCardWhiteList;
    @XmlElement(name = "CustomerUsedCards")
    protected CustomerUsedCards customerUsedCards;
    @XmlElement(name = "Gender")
    protected String gender;
    @XmlElement(name = "CustPhoto")
    protected String custPhoto;
    @XmlElement(name = "MartialStatus")
    protected String martialStatus;
    @XmlElement(name = "CustAddresses")
    protected CustAddressesType custAddresses;
    @XmlElement(name = "DashboardViewingType")
    @XmlSchemaType(name = "string")
    protected DashboardViewingTypeEnum dashboardViewingType;
    @XmlElement(name = "KYCLevel")
    protected String kycLevel;
    @XmlElement(name = "BirthPlace")
    protected PlaceOfBirthType birthPlace;
    @XmlElement(name = "OtherNationalityCode")
    protected String otherNationalityCode;
    @XmlElement(name = "HasBankAcct")
    protected Boolean hasBankAcct;
    @XmlElement(name = "JobTitle")
    protected String jobTitle;
    @XmlElement(name = "MonthlySalary")
    protected Double monthlySalary;
    @XmlElement(name = "CompanyName")
    protected String companyName;
    @XmlElement(name = "Memo")
    protected String memo;
    @XmlElement(name = "ExternalWLTCode")
    protected String externalWLTCode;
    @XmlElement(name = "BusinessDomain")
    protected String businessDomain;
    @XmlElement(name = "IsSelfReg")
    protected Boolean isSelfReg;
    @XmlElement(name = "RegVerMethod")
    protected String regVerMethod;
    @XmlElement(name = "CustPhotoBinary")
    protected byte[] custPhotoBinary;
    @XmlElement(name = "CustValStatus")
    @XmlSchemaType(name = "string")
    protected CustStatusEnum custValStatus;
    @XmlElement(name = "MasterAcctID")
    protected String masterAcctID;
    @XmlElement(name = "CustomerSubscriptions")
    protected CustomerSubscriptionsType customerSubscriptions;

    /**
     * Gets the value of the custIds property.
     * 
     * @return
     *     possible object is
     *     {@link CustIdsType }
     *     
     */
    public CustIdsType getCustIds() {
        return custIds;
    }

    /**
     * Sets the value of the custIds property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustIdsType }
     *     
     */
    public void setCustIds(CustIdsType value) {
        this.custIds = value;
    }

    /**
     * Gets the value of the recCtrlOut property.
     * 
     * @return
     *     possible object is
     *     {@link RecCtrlOutType }
     *     
     */
    public RecCtrlOutType getRecCtrlOut() {
        return recCtrlOut;
    }

    /**
     * Sets the value of the recCtrlOut property.
     * 
     * @param value
     *     allowed object is
     *     {@link RecCtrlOutType }
     *     
     */
    public void setRecCtrlOut(RecCtrlOutType value) {
        this.recCtrlOut = value;
    }

    /**
     * Gets the value of the optType property.
     * 
     * @return
     *     possible object is
     *     {@link OptTypeEnum }
     *     
     */
    public OptTypeEnum getOptType() {
        return optType;
    }

    /**
     * Sets the value of the optType property.
     * 
     * @param value
     *     allowed object is
     *     {@link OptTypeEnum }
     *     
     */
    public void setOptType(OptTypeEnum value) {
        this.optType = value;
    }

    /**
     * Gets the value of the custType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustType() {
        return custType;
    }

    /**
     * Sets the value of the custType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustType(String value) {
        this.custType = value;
    }

    /**
     * Gets the value of the custStatus property.
     * 
     * @return
     *     possible object is
     *     {@link CustStatusEnum }
     *     
     */
    public CustStatusEnum getCustStatus() {
        return custStatus;
    }

    /**
     * Sets the value of the custStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustStatusEnum }
     *     
     */
    public void setCustStatus(CustStatusEnum value) {
        this.custStatus = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the middleName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMiddleName() {
        return middleName;
    }

    /**
     * Sets the value of the middleName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMiddleName(String value) {
        this.middleName = value;
    }

    /**
     * Gets the value of the secondaryName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSecondaryName() {
        return secondaryName;
    }

    /**
     * Sets the value of the secondaryName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSecondaryName(String value) {
        this.secondaryName = value;
    }

    /**
     * Gets the value of the secondaryMiddleName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSecondaryMiddleName() {
        return secondaryMiddleName;
    }

    /**
     * Sets the value of the secondaryMiddleName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSecondaryMiddleName(String value) {
        this.secondaryMiddleName = value;
    }

    /**
     * Gets the value of the secondaryLastName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSecondaryLastName() {
        return secondaryLastName;
    }

    /**
     * Sets the value of the secondaryLastName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSecondaryLastName(String value) {
        this.secondaryLastName = value;
    }

    /**
     * Gets the value of the motherFirstName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMotherFirstName() {
        return motherFirstName;
    }

    /**
     * Sets the value of the motherFirstName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMotherFirstName(String value) {
        this.motherFirstName = value;
    }

    /**
     * Gets the value of the motherMiddleName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMotherMiddleName() {
        return motherMiddleName;
    }

    /**
     * Sets the value of the motherMiddleName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMotherMiddleName(String value) {
        this.motherMiddleName = value;
    }

    /**
     * Gets the value of the motherLastName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMotherLastName() {
        return motherLastName;
    }

    /**
     * Sets the value of the motherLastName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMotherLastName(String value) {
        this.motherLastName = value;
    }

    /**
     * Gets the value of the nationalityCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNationalityCode() {
        return nationalityCode;
    }

    /**
     * Sets the value of the nationalityCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNationalityCode(String value) {
        this.nationalityCode = value;
    }

    /**
     * Gets the value of the primaryBranchCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrimaryBranchCode() {
        return primaryBranchCode;
    }

    /**
     * Sets the value of the primaryBranchCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrimaryBranchCode(String value) {
        this.primaryBranchCode = value;
    }

    /**
     * Gets the value of the deactivationReason property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeactivationReason() {
        return deactivationReason;
    }

    /**
     * Sets the value of the deactivationReason property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeactivationReason(String value) {
        this.deactivationReason = value;
    }

    /**
     * Gets the value of the isAutoArchive property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsAutoArchive() {
        return isAutoArchive;
    }

    /**
     * Sets the value of the isAutoArchive property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsAutoArchive(Boolean value) {
        this.isAutoArchive = value;
    }

    /**
     * Gets the value of the autoArchivePeriod property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getAutoArchivePeriod() {
        return autoArchivePeriod;
    }

    /**
     * Sets the value of the autoArchivePeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setAutoArchivePeriod(Long value) {
        this.autoArchivePeriod = value;
    }

    /**
     * Gets the value of the custCategory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustCategory() {
        return custCategory;
    }

    /**
     * Sets the value of the custCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustCategory(String value) {
        this.custCategory = value;
    }

    /**
     * Gets the value of the isCCardEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsCCardEnabled() {
        return isCCardEnabled;
    }

    /**
     * Sets the value of the isCCardEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsCCardEnabled(Boolean value) {
        this.isCCardEnabled = value;
    }

    /**
     * Gets the value of the contactInfo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the contactInfo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContactInfo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ContactInfoType }
     * 
     * 
     * @return
     *     The value of the contactInfo property.
     */
    public List<ContactInfoType> getContactInfo() {
        if (contactInfo == null) {
            contactInfo = new ArrayList<>();
        }
        return this.contactInfo;
    }

    /**
     * Gets the value of the sourceOfFunds property.
     * 
     * @return
     *     possible object is
     *     {@link SourceOfFundsType }
     *     
     */
    public SourceOfFundsType getSourceOfFunds() {
        return sourceOfFunds;
    }

    /**
     * Sets the value of the sourceOfFunds property.
     * 
     * @param value
     *     allowed object is
     *     {@link SourceOfFundsType }
     *     
     */
    public void setSourceOfFunds(SourceOfFundsType value) {
        this.sourceOfFunds = value;
    }

    /**
     * Gets the value of the fawryCustNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFawryCustNumber() {
        return fawryCustNumber;
    }

    /**
     * Sets the value of the fawryCustNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFawryCustNumber(String value) {
        this.fawryCustNumber = value;
    }

    /**
     * Gets the value of the lastName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * Sets the value of the lastName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastName(String value) {
        this.lastName = value;
    }

    /**
     * Gets the value of the birthDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getBirthDate() {
        return birthDate;
    }

    /**
     * Sets the value of the birthDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setBirthDate(XMLGregorianCalendar value) {
        this.birthDate = value;
    }

    /**
     * Gets the value of the linkCustomerReg property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isLinkCustomerReg() {
        return linkCustomerReg;
    }

    /**
     * Sets the value of the linkCustomerReg property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setLinkCustomerReg(Boolean value) {
        this.linkCustomerReg = value;
    }

    /**
     * Gets the value of the activationCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActivationCode() {
        return activationCode;
    }

    /**
     * Sets the value of the activationCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActivationCode(String value) {
        this.activationCode = value;
    }

    /**
     * Gets the value of the hasCCardWhiteList property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isHasCCardWhiteList() {
        return hasCCardWhiteList;
    }

    /**
     * Sets the value of the hasCCardWhiteList property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setHasCCardWhiteList(Boolean value) {
        this.hasCCardWhiteList = value;
    }

    /**
     * Gets the value of the cCardWhiteList property.
     * 
     * @return
     *     possible object is
     *     {@link CardWhiteList }
     *     
     */
    public CardWhiteList getCCardWhiteList() {
        return cCardWhiteList;
    }

    /**
     * Sets the value of the cCardWhiteList property.
     * 
     * @param value
     *     allowed object is
     *     {@link CardWhiteList }
     *     
     */
    public void setCCardWhiteList(CardWhiteList value) {
        this.cCardWhiteList = value;
    }

    /**
     * Gets the value of the customerUsedCards property.
     * 
     * @return
     *     possible object is
     *     {@link CustomerUsedCards }
     *     
     */
    public CustomerUsedCards getCustomerUsedCards() {
        return customerUsedCards;
    }

    /**
     * Sets the value of the customerUsedCards property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustomerUsedCards }
     *     
     */
    public void setCustomerUsedCards(CustomerUsedCards value) {
        this.customerUsedCards = value;
    }

    /**
     * Gets the value of the gender property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGender() {
        return gender;
    }

    /**
     * Sets the value of the gender property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGender(String value) {
        this.gender = value;
    }

    /**
     * Gets the value of the custPhoto property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustPhoto() {
        return custPhoto;
    }

    /**
     * Sets the value of the custPhoto property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustPhoto(String value) {
        this.custPhoto = value;
    }

    /**
     * Gets the value of the martialStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMartialStatus() {
        return martialStatus;
    }

    /**
     * Sets the value of the martialStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMartialStatus(String value) {
        this.martialStatus = value;
    }

    /**
     * Gets the value of the custAddresses property.
     * 
     * @return
     *     possible object is
     *     {@link CustAddressesType }
     *     
     */
    public CustAddressesType getCustAddresses() {
        return custAddresses;
    }

    /**
     * Sets the value of the custAddresses property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustAddressesType }
     *     
     */
    public void setCustAddresses(CustAddressesType value) {
        this.custAddresses = value;
    }

    /**
     * Gets the value of the dashboardViewingType property.
     * 
     * @return
     *     possible object is
     *     {@link DashboardViewingTypeEnum }
     *     
     */
    public DashboardViewingTypeEnum getDashboardViewingType() {
        return dashboardViewingType;
    }

    /**
     * Sets the value of the dashboardViewingType property.
     * 
     * @param value
     *     allowed object is
     *     {@link DashboardViewingTypeEnum }
     *     
     */
    public void setDashboardViewingType(DashboardViewingTypeEnum value) {
        this.dashboardViewingType = value;
    }

    /**
     * Gets the value of the kycLevel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKYCLevel() {
        return kycLevel;
    }

    /**
     * Sets the value of the kycLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKYCLevel(String value) {
        this.kycLevel = value;
    }

    /**
     * Gets the value of the birthPlace property.
     * 
     * @return
     *     possible object is
     *     {@link PlaceOfBirthType }
     *     
     */
    public PlaceOfBirthType getBirthPlace() {
        return birthPlace;
    }

    /**
     * Sets the value of the birthPlace property.
     * 
     * @param value
     *     allowed object is
     *     {@link PlaceOfBirthType }
     *     
     */
    public void setBirthPlace(PlaceOfBirthType value) {
        this.birthPlace = value;
    }

    /**
     * Gets the value of the otherNationalityCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOtherNationalityCode() {
        return otherNationalityCode;
    }

    /**
     * Sets the value of the otherNationalityCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOtherNationalityCode(String value) {
        this.otherNationalityCode = value;
    }

    /**
     * Gets the value of the hasBankAcct property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isHasBankAcct() {
        return hasBankAcct;
    }

    /**
     * Sets the value of the hasBankAcct property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setHasBankAcct(Boolean value) {
        this.hasBankAcct = value;
    }

    /**
     * Gets the value of the jobTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJobTitle() {
        return jobTitle;
    }

    /**
     * Sets the value of the jobTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJobTitle(String value) {
        this.jobTitle = value;
    }

    /**
     * Gets the value of the monthlySalary property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getMonthlySalary() {
        return monthlySalary;
    }

    /**
     * Sets the value of the monthlySalary property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setMonthlySalary(Double value) {
        this.monthlySalary = value;
    }

    /**
     * Gets the value of the companyName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * Sets the value of the companyName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCompanyName(String value) {
        this.companyName = value;
    }

    /**
     * Gets the value of the memo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMemo() {
        return memo;
    }

    /**
     * Sets the value of the memo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMemo(String value) {
        this.memo = value;
    }

    /**
     * Gets the value of the externalWLTCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExternalWLTCode() {
        return externalWLTCode;
    }

    /**
     * Sets the value of the externalWLTCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExternalWLTCode(String value) {
        this.externalWLTCode = value;
    }

    /**
     * Gets the value of the businessDomain property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBusinessDomain() {
        return businessDomain;
    }

    /**
     * Sets the value of the businessDomain property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBusinessDomain(String value) {
        this.businessDomain = value;
    }

    /**
     * Gets the value of the isSelfReg property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsSelfReg() {
        return isSelfReg;
    }

    /**
     * Sets the value of the isSelfReg property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsSelfReg(Boolean value) {
        this.isSelfReg = value;
    }

    /**
     * Gets the value of the regVerMethod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegVerMethod() {
        return regVerMethod;
    }

    /**
     * Sets the value of the regVerMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegVerMethod(String value) {
        this.regVerMethod = value;
    }

    /**
     * Gets the value of the custPhotoBinary property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getCustPhotoBinary() {
        return custPhotoBinary;
    }

    /**
     * Sets the value of the custPhotoBinary property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setCustPhotoBinary(byte[] value) {
        this.custPhotoBinary = value;
    }

    /**
     * Gets the value of the custValStatus property.
     * 
     * @return
     *     possible object is
     *     {@link CustStatusEnum }
     *     
     */
    public CustStatusEnum getCustValStatus() {
        return custValStatus;
    }

    /**
     * Sets the value of the custValStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustStatusEnum }
     *     
     */
    public void setCustValStatus(CustStatusEnum value) {
        this.custValStatus = value;
    }

    /**
     * Gets the value of the masterAcctID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMasterAcctID() {
        return masterAcctID;
    }

    /**
     * Sets the value of the masterAcctID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMasterAcctID(String value) {
        this.masterAcctID = value;
    }

    /**
     * Gets the value of the customerSubscriptions property.
     * 
     * @return
     *     possible object is
     *     {@link CustomerSubscriptionsType }
     *     
     */
    public CustomerSubscriptionsType getCustomerSubscriptions() {
        return customerSubscriptions;
    }

    /**
     * Sets the value of the customerSubscriptions property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustomerSubscriptionsType }
     *     
     */
    public void setCustomerSubscriptions(CustomerSubscriptionsType value) {
        this.customerSubscriptions = value;
    }

}
