//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.fawry.adapter_template.model.fawryType;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CustSOFsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="CustSOFsType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="CustIds" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}CustIdsType" minOccurs="0"/>
 *         <element name="FawryCustNumber" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}FawryCustNumberType" minOccurs="0"/>
 *         <element name="SourceOfFunds" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}SourceOfFundsType" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CustSOFsType", propOrder = {
    "custIds",
    "fawryCustNumber",
    "sourceOfFunds"
})
public class CustSOFsType {

    @XmlElement(name = "CustIds")
    protected CustIdsType custIds;
    @XmlElement(name = "FawryCustNumber")
    protected String fawryCustNumber;
    @XmlElement(name = "SourceOfFunds")
    protected SourceOfFundsType sourceOfFunds;

    /**
     * Gets the value of the custIds property.
     * 
     * @return
     *     possible object is
     *     {@link CustIdsType }
     *     
     */
    public CustIdsType getCustIds() {
        return custIds;
    }

    /**
     * Sets the value of the custIds property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustIdsType }
     *     
     */
    public void setCustIds(CustIdsType value) {
        this.custIds = value;
    }

    /**
     * Gets the value of the fawryCustNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFawryCustNumber() {
        return fawryCustNumber;
    }

    /**
     * Sets the value of the fawryCustNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFawryCustNumber(String value) {
        this.fawryCustNumber = value;
    }

    /**
     * Gets the value of the sourceOfFunds property.
     * 
     * @return
     *     possible object is
     *     {@link SourceOfFundsType }
     *     
     */
    public SourceOfFundsType getSourceOfFunds() {
        return sourceOfFunds;
    }

    /**
     * Sets the value of the sourceOfFunds property.
     * 
     * @param value
     *     allowed object is
     *     {@link SourceOfFundsType }
     *     
     */
    public void setSourceOfFunds(SourceOfFundsType value) {
        this.sourceOfFunds = value;
    }

}
