//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.fawry.adapter_template.model.fawryType;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CycleIntervalUnitEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>{@code
 * <simpleType name="CycleIntervalUnitEnum">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <enumeration value="WEEKLY"/>
 *     <enumeration value="BIWEEKLY"/>
 *     <enumeration value="MONTHLY"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "CycleIntervalUnitEnum")
@XmlEnum
public enum CycleIntervalUnitEnum {

    WEEKLY,
    BIWEEKLY,
    MONTHLY;

    public String value() {
        return name();
    }

    public static CycleIntervalUnitEnum fromValue(String v) {
        return valueOf(v);
    }

}
