//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.fawry.adapter_template.model.fawryType;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DashboardDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="DashboardDataType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="TtlSpent" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}CurAmtType"/>
 *         <element name="CustomerTtlSpent" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}CustomerTtlSpentType" minOccurs="0"/>
 *         <element name="TtlSpentPerMonth" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}TotalSpentsPerMonthType" minOccurs="0"/>
 *         <element name="TtlSpentPerSvcType" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}TotalSpentsPerServiceTypeType" minOccurs="0"/>
 *         <element name="TtlSpentPerBillType" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}TotalSpentsPerBillTypeType" minOccurs="0"/>
 *         <element name="FreqUsedBillTypes" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}FreqUsedBillTypesType" minOccurs="0"/>
 *         <element name="FreqUsedEnrollments" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}FreqUsedEnrollmentsType" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DashboardDataType", propOrder = {
    "ttlSpent",
    "customerTtlSpent",
    "ttlSpentPerMonth",
    "ttlSpentPerSvcType",
    "ttlSpentPerBillType",
    "freqUsedBillTypes",
    "freqUsedEnrollments"
})
public class DashboardDataType {

    @XmlElement(name = "TtlSpent", required = true)
    protected CurAmtType ttlSpent;
    @XmlElement(name = "CustomerTtlSpent")
    protected CustomerTtlSpentType customerTtlSpent;
    @XmlElement(name = "TtlSpentPerMonth")
    protected TotalSpentsPerMonthType ttlSpentPerMonth;
    @XmlElement(name = "TtlSpentPerSvcType")
    protected TotalSpentsPerServiceTypeType ttlSpentPerSvcType;
    @XmlElement(name = "TtlSpentPerBillType")
    protected TotalSpentsPerBillTypeType ttlSpentPerBillType;
    @XmlElement(name = "FreqUsedBillTypes")
    protected FreqUsedBillTypesType freqUsedBillTypes;
    @XmlElement(name = "FreqUsedEnrollments")
    protected FreqUsedEnrollmentsType freqUsedEnrollments;

    /**
     * Gets the value of the ttlSpent property.
     * 
     * @return
     *     possible object is
     *     {@link CurAmtType }
     *     
     */
    public CurAmtType getTtlSpent() {
        return ttlSpent;
    }

    /**
     * Sets the value of the ttlSpent property.
     * 
     * @param value
     *     allowed object is
     *     {@link CurAmtType }
     *     
     */
    public void setTtlSpent(CurAmtType value) {
        this.ttlSpent = value;
    }

    /**
     * Gets the value of the customerTtlSpent property.
     * 
     * @return
     *     possible object is
     *     {@link CustomerTtlSpentType }
     *     
     */
    public CustomerTtlSpentType getCustomerTtlSpent() {
        return customerTtlSpent;
    }

    /**
     * Sets the value of the customerTtlSpent property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustomerTtlSpentType }
     *     
     */
    public void setCustomerTtlSpent(CustomerTtlSpentType value) {
        this.customerTtlSpent = value;
    }

    /**
     * Gets the value of the ttlSpentPerMonth property.
     * 
     * @return
     *     possible object is
     *     {@link TotalSpentsPerMonthType }
     *     
     */
    public TotalSpentsPerMonthType getTtlSpentPerMonth() {
        return ttlSpentPerMonth;
    }

    /**
     * Sets the value of the ttlSpentPerMonth property.
     * 
     * @param value
     *     allowed object is
     *     {@link TotalSpentsPerMonthType }
     *     
     */
    public void setTtlSpentPerMonth(TotalSpentsPerMonthType value) {
        this.ttlSpentPerMonth = value;
    }

    /**
     * Gets the value of the ttlSpentPerSvcType property.
     * 
     * @return
     *     possible object is
     *     {@link TotalSpentsPerServiceTypeType }
     *     
     */
    public TotalSpentsPerServiceTypeType getTtlSpentPerSvcType() {
        return ttlSpentPerSvcType;
    }

    /**
     * Sets the value of the ttlSpentPerSvcType property.
     * 
     * @param value
     *     allowed object is
     *     {@link TotalSpentsPerServiceTypeType }
     *     
     */
    public void setTtlSpentPerSvcType(TotalSpentsPerServiceTypeType value) {
        this.ttlSpentPerSvcType = value;
    }

    /**
     * Gets the value of the ttlSpentPerBillType property.
     * 
     * @return
     *     possible object is
     *     {@link TotalSpentsPerBillTypeType }
     *     
     */
    public TotalSpentsPerBillTypeType getTtlSpentPerBillType() {
        return ttlSpentPerBillType;
    }

    /**
     * Sets the value of the ttlSpentPerBillType property.
     * 
     * @param value
     *     allowed object is
     *     {@link TotalSpentsPerBillTypeType }
     *     
     */
    public void setTtlSpentPerBillType(TotalSpentsPerBillTypeType value) {
        this.ttlSpentPerBillType = value;
    }

    /**
     * Gets the value of the freqUsedBillTypes property.
     * 
     * @return
     *     possible object is
     *     {@link FreqUsedBillTypesType }
     *     
     */
    public FreqUsedBillTypesType getFreqUsedBillTypes() {
        return freqUsedBillTypes;
    }

    /**
     * Sets the value of the freqUsedBillTypes property.
     * 
     * @param value
     *     allowed object is
     *     {@link FreqUsedBillTypesType }
     *     
     */
    public void setFreqUsedBillTypes(FreqUsedBillTypesType value) {
        this.freqUsedBillTypes = value;
    }

    /**
     * Gets the value of the freqUsedEnrollments property.
     * 
     * @return
     *     possible object is
     *     {@link FreqUsedEnrollmentsType }
     *     
     */
    public FreqUsedEnrollmentsType getFreqUsedEnrollments() {
        return freqUsedEnrollments;
    }

    /**
     * Sets the value of the freqUsedEnrollments property.
     * 
     * @param value
     *     allowed object is
     *     {@link FreqUsedEnrollmentsType }
     *     
     */
    public void setFreqUsedEnrollments(FreqUsedEnrollmentsType value) {
        this.freqUsedEnrollments = value;
    }

}
