//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.fawry.adapter_template.model.fawryType;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DebitMsgRqInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="DebitMsgRqInfoType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="DebitId" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}Identifier_Type" minOccurs="0"/>
 *         <element name="DebitAddRq" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}DebitAddRqType" minOccurs="0"/>
 *         <element name="ExternalSOFCode" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}Identifier_Type" minOccurs="0"/>
 *         <element name="AccountInfo" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}AccountInfoType" minOccurs="0"/>
 *         <element name="MerchantInfo" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}MerchantInfoType" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DebitMsgRqInfoType", propOrder = {
    "debitId",
    "debitAddRq",
    "externalSOFCode",
    "accountInfo",
    "merchantInfo"
})
public class DebitMsgRqInfoType {

    @XmlElement(name = "DebitId")
    protected String debitId;
    @XmlElement(name = "DebitAddRq")
    protected DebitAddRqType debitAddRq;
    @XmlElement(name = "ExternalSOFCode")
    protected String externalSOFCode;
    @XmlElement(name = "AccountInfo")
    protected AccountInfoType accountInfo;
    @XmlElement(name = "MerchantInfo")
    protected MerchantInfoType merchantInfo;

    /**
     * Gets the value of the debitId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDebitId() {
        return debitId;
    }

    /**
     * Sets the value of the debitId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDebitId(String value) {
        this.debitId = value;
    }

    /**
     * Gets the value of the debitAddRq property.
     * 
     * @return
     *     possible object is
     *     {@link DebitAddRqType }
     *     
     */
    public DebitAddRqType getDebitAddRq() {
        return debitAddRq;
    }

    /**
     * Sets the value of the debitAddRq property.
     * 
     * @param value
     *     allowed object is
     *     {@link DebitAddRqType }
     *     
     */
    public void setDebitAddRq(DebitAddRqType value) {
        this.debitAddRq = value;
    }

    /**
     * Gets the value of the externalSOFCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExternalSOFCode() {
        return externalSOFCode;
    }

    /**
     * Sets the value of the externalSOFCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExternalSOFCode(String value) {
        this.externalSOFCode = value;
    }

    /**
     * Gets the value of the accountInfo property.
     * 
     * @return
     *     possible object is
     *     {@link AccountInfoType }
     *     
     */
    public AccountInfoType getAccountInfo() {
        return accountInfo;
    }

    /**
     * Sets the value of the accountInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccountInfoType }
     *     
     */
    public void setAccountInfo(AccountInfoType value) {
        this.accountInfo = value;
    }

    /**
     * Gets the value of the merchantInfo property.
     * 
     * @return
     *     possible object is
     *     {@link MerchantInfoType }
     *     
     */
    public MerchantInfoType getMerchantInfo() {
        return merchantInfo;
    }

    /**
     * Sets the value of the merchantInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link MerchantInfoType }
     *     
     */
    public void setMerchantInfo(MerchantInfoType value) {
        this.merchantInfo = value;
    }

}
