//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.fawry.adapter_template.model.fawryType;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DimensionUnitEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>{@code
 * <simpleType name="DimensionUnitEnum">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <enumeration value="Inches"/>
 *     <enumeration value="Centimeters"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "DimensionUnitEnum")
@XmlEnum
public enum DimensionUnitEnum {

    @XmlEnumValue("Inches")
    INCHES("Inches"),
    @XmlEnumValue("Centimeters")
    CENTIMETERS("Centimeters");
    private final String value;

    DimensionUnitEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static DimensionUnitEnum fromValue(String v) {
        for (DimensionUnitEnum c: DimensionUnitEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
