//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.fawry.adapter_template.model.fawryType;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ExtraBillingAcctKeyType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="ExtraBillingAcctKeyType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="Key" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}ExtraBillingAcctKeyTypeOpenEnum"/>
 *         <element name="Value">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               <maxLength value="128"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="Label" minOccurs="0">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               <maxLength value="80"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="InputMethod" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}AcctInputMethodOpenEnum" minOccurs="0"/>
 *         <element name="IsPrintKeyPart" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         <element name="IsEncryptRequired" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         <element name="EncryptKeyProfile" minOccurs="0">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               <maxLength value="256"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="IsInputMasked" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ExtraBillingAcctKeyType", propOrder = {
    "key",
    "value",
    "label",
    "inputMethod",
    "isPrintKeyPart",
    "isEncryptRequired",
    "encryptKeyProfile",
    "isInputMasked"
})
public class ExtraBillingAcctKeyType {

    @XmlElement(name = "Key", required = true)
    protected String key;
    @XmlElement(name = "Value", required = true)
    protected String value;
    @XmlElement(name = "Label")
    protected String label;
    @XmlElement(name = "InputMethod")
    protected String inputMethod;
    @XmlElement(name = "IsPrintKeyPart")
    protected Boolean isPrintKeyPart;
    @XmlElement(name = "IsEncryptRequired")
    protected Boolean isEncryptRequired;
    @XmlElement(name = "EncryptKeyProfile")
    protected String encryptKeyProfile;
    @XmlElement(name = "IsInputMasked")
    protected Boolean isInputMasked;

    /**
     * Gets the value of the key property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKey() {
        return key;
    }

    /**
     * Sets the value of the key property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKey(String value) {
        this.key = value;
    }

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the label property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLabel() {
        return label;
    }

    /**
     * Sets the value of the label property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLabel(String value) {
        this.label = value;
    }

    /**
     * Gets the value of the inputMethod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInputMethod() {
        return inputMethod;
    }

    /**
     * Sets the value of the inputMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInputMethod(String value) {
        this.inputMethod = value;
    }

    /**
     * Gets the value of the isPrintKeyPart property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsPrintKeyPart() {
        return isPrintKeyPart;
    }

    /**
     * Sets the value of the isPrintKeyPart property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsPrintKeyPart(Boolean value) {
        this.isPrintKeyPart = value;
    }

    /**
     * Gets the value of the isEncryptRequired property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsEncryptRequired() {
        return isEncryptRequired;
    }

    /**
     * Sets the value of the isEncryptRequired property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsEncryptRequired(Boolean value) {
        this.isEncryptRequired = value;
    }

    /**
     * Gets the value of the encryptKeyProfile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEncryptKeyProfile() {
        return encryptKeyProfile;
    }

    /**
     * Sets the value of the encryptKeyProfile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEncryptKeyProfile(String value) {
        this.encryptKeyProfile = value;
    }

    /**
     * Gets the value of the isInputMasked property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsInputMasked() {
        return isInputMasked;
    }

    /**
     * Sets the value of the isInputMasked property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsInputMasked(Boolean value) {
        this.isInputMasked = value;
    }

}
