//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.fawry.adapter_template.model.fawryType;

import jakarta.xml.bind.annotation.*;

import javax.xml.datatype.XMLGregorianCalendar;
import java.math.BigDecimal;


/**
 * <p>Java class for FinanceProgramDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="FinanceProgramDataType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="ProgramStatus" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}ProgramStatusOpenEnum" minOccurs="0"/>
 *         <element name="Class" minOccurs="0">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               <maxLength value="1"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="FacilityAmt" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         <element name="Desc" minOccurs="0">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               <maxLength value="512"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="FinanceProgramCode" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}Identifier_Type" minOccurs="0"/>
 *         <element name="EnableDt" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         <element name="DisableDt" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         <element name="ProgramTypeCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         <element name="FinanceProgramSetup" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}FinanceProgramSetup" minOccurs="0"/>
 *         <element name="InstallmentPlans" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}InstallmentRulesType" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FinanceProgramDataType", propOrder = {
    "programStatus",
    "clazz",
    "facilityAmt",
    "desc",
    "financeProgramCode",
    "enableDt",
    "disableDt",
    "programTypeCode",
    "financeProgramSetup",
    "installmentPlans"
})
public class FinanceProgramDataType {

    @XmlElement(name = "ProgramStatus")
    protected String programStatus;
    @XmlElement(name = "Class")
    protected String clazz;
    @XmlElement(name = "FacilityAmt")
    protected BigDecimal facilityAmt;
    @XmlElement(name = "Desc")
    protected String desc;
    @XmlElement(name = "FinanceProgramCode")
    protected String financeProgramCode;
    @XmlElement(name = "EnableDt")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar enableDt;
    @XmlElement(name = "DisableDt")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar disableDt;
    @XmlElement(name = "ProgramTypeCode")
    protected String programTypeCode;
    @XmlElement(name = "FinanceProgramSetup")
    protected FinanceProgramSetup financeProgramSetup;
    @XmlElement(name = "InstallmentPlans")
    protected InstallmentRulesType installmentPlans;

    /**
     * Gets the value of the programStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProgramStatus() {
        return programStatus;
    }

    /**
     * Sets the value of the programStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProgramStatus(String value) {
        this.programStatus = value;
    }

    /**
     * Gets the value of the clazz property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClazz() {
        return clazz;
    }

    /**
     * Sets the value of the clazz property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClazz(String value) {
        this.clazz = value;
    }

    /**
     * Gets the value of the facilityAmt property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getFacilityAmt() {
        return facilityAmt;
    }

    /**
     * Sets the value of the facilityAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setFacilityAmt(BigDecimal value) {
        this.facilityAmt = value;
    }

    /**
     * Gets the value of the desc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDesc() {
        return desc;
    }

    /**
     * Sets the value of the desc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDesc(String value) {
        this.desc = value;
    }

    /**
     * Gets the value of the financeProgramCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFinanceProgramCode() {
        return financeProgramCode;
    }

    /**
     * Sets the value of the financeProgramCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFinanceProgramCode(String value) {
        this.financeProgramCode = value;
    }

    /**
     * Gets the value of the enableDt property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEnableDt() {
        return enableDt;
    }

    /**
     * Sets the value of the enableDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEnableDt(XMLGregorianCalendar value) {
        this.enableDt = value;
    }

    /**
     * Gets the value of the disableDt property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDisableDt() {
        return disableDt;
    }

    /**
     * Sets the value of the disableDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDisableDt(XMLGregorianCalendar value) {
        this.disableDt = value;
    }

    /**
     * Gets the value of the programTypeCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProgramTypeCode() {
        return programTypeCode;
    }

    /**
     * Sets the value of the programTypeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProgramTypeCode(String value) {
        this.programTypeCode = value;
    }

    /**
     * Gets the value of the financeProgramSetup property.
     * 
     * @return
     *     possible object is
     *     {@link FinanceProgramSetup }
     *     
     */
    public FinanceProgramSetup getFinanceProgramSetup() {
        return financeProgramSetup;
    }

    /**
     * Sets the value of the financeProgramSetup property.
     * 
     * @param value
     *     allowed object is
     *     {@link FinanceProgramSetup }
     *     
     */
    public void setFinanceProgramSetup(FinanceProgramSetup value) {
        this.financeProgramSetup = value;
    }

    /**
     * Gets the value of the installmentPlans property.
     * 
     * @return
     *     possible object is
     *     {@link InstallmentRulesType }
     *     
     */
    public InstallmentRulesType getInstallmentPlans() {
        return installmentPlans;
    }

    /**
     * Sets the value of the installmentPlans property.
     * 
     * @param value
     *     allowed object is
     *     {@link InstallmentRulesType }
     *     
     */
    public void setInstallmentPlans(InstallmentRulesType value) {
        this.installmentPlans = value;
    }

}
