//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.fawry.adapter_template.model.fawryType;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GetShippingFeesRqType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="GetShippingFeesRqType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="DeliveryType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         <element name="PaymentOption" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}PaymentOptionOpenEnum" minOccurs="0"/>
 *         <element name="MerchantId" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}Identifier_Type"/>
 *         <element name="ShippingAddress" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}AddressType"/>
 *         <element name="Items" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}ItemsType" minOccurs="0"/>
 *         <element name="BillTypeCode" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetShippingFeesRqType", propOrder = {
    "deliveryType",
    "paymentOption",
    "merchantId",
    "shippingAddress",
    "items",
    "billTypeCode"
})
public class GetShippingFeesRqType {

    @XmlElement(name = "DeliveryType")
    protected String deliveryType;
    @XmlElement(name = "PaymentOption")
    protected String paymentOption;
    @XmlElement(name = "MerchantId", required = true)
    protected String merchantId;
    @XmlElement(name = "ShippingAddress", required = true)
    protected AddressType shippingAddress;
    @XmlElement(name = "Items")
    protected ItemsType items;
    @XmlElement(name = "BillTypeCode")
    protected Long billTypeCode;

    /**
     * Gets the value of the deliveryType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeliveryType() {
        return deliveryType;
    }

    /**
     * Sets the value of the deliveryType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeliveryType(String value) {
        this.deliveryType = value;
    }

    /**
     * Gets the value of the paymentOption property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaymentOption() {
        return paymentOption;
    }

    /**
     * Sets the value of the paymentOption property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymentOption(String value) {
        this.paymentOption = value;
    }

    /**
     * Gets the value of the merchantId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMerchantId() {
        return merchantId;
    }

    /**
     * Sets the value of the merchantId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMerchantId(String value) {
        this.merchantId = value;
    }

    /**
     * Gets the value of the shippingAddress property.
     * 
     * @return
     *     possible object is
     *     {@link AddressType }
     *     
     */
    public AddressType getShippingAddress() {
        return shippingAddress;
    }

    /**
     * Sets the value of the shippingAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddressType }
     *     
     */
    public void setShippingAddress(AddressType value) {
        this.shippingAddress = value;
    }

    /**
     * Gets the value of the items property.
     * 
     * @return
     *     possible object is
     *     {@link ItemsType }
     *     
     */
    public ItemsType getItems() {
        return items;
    }

    /**
     * Sets the value of the items property.
     * 
     * @param value
     *     allowed object is
     *     {@link ItemsType }
     *     
     */
    public void setItems(ItemsType value) {
        this.items = value;
    }

    /**
     * Gets the value of the billTypeCode property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getBillTypeCode() {
        return billTypeCode;
    }

    /**
     * Sets the value of the billTypeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setBillTypeCode(Long value) {
        this.billTypeCode = value;
    }

}
