//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.fawry.adapter_template.model.fawryType;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ItemType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="ItemType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="Code">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               <maxLength value="50"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="Type" minOccurs="0">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               <maxLength value="200"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="Desc" minOccurs="0">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               <maxLength value="200"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="WarehouseLocation" minOccurs="0">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               <maxLength value="250"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="Quantity" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         <element name="Amt" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}CurAmtType" minOccurs="0"/>
 *         <element name="Weight" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}WeightType" minOccurs="0"/>
 *         <element name="Width" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}DimensionType" minOccurs="0"/>
 *         <element name="Height" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}DimensionType" minOccurs="0"/>
 *         <element name="Length" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}DimensionType" minOccurs="0"/>
 *         <element name="ItemExraDetails" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}ItemExtraDetailsType" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ItemType", propOrder = {
    "code",
    "type",
    "desc",
    "warehouseLocation",
    "quantity",
    "amt",
    "weight",
    "width",
    "height",
    "length",
    "itemExraDetails"
})
public class ItemType {

    @XmlElement(name = "Code", required = true)
    protected String code;
    @XmlElement(name = "Type")
    protected String type;
    @XmlElement(name = "Desc")
    protected String desc;
    @XmlElement(name = "WarehouseLocation")
    protected String warehouseLocation;
    @XmlElement(name = "Quantity")
    protected Long quantity;
    @XmlElement(name = "Amt")
    protected CurAmtType amt;
    @XmlElement(name = "Weight")
    protected WeightType weight;
    @XmlElement(name = "Width")
    protected DimensionType width;
    @XmlElement(name = "Height")
    protected DimensionType height;
    @XmlElement(name = "Length")
    protected DimensionType length;
    @XmlElement(name = "ItemExraDetails")
    protected ItemExtraDetailsType itemExraDetails;

    /**
     * Gets the value of the code property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCode() {
        return code;
    }

    /**
     * Sets the value of the code property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCode(String value) {
        this.code = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the desc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDesc() {
        return desc;
    }

    /**
     * Sets the value of the desc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDesc(String value) {
        this.desc = value;
    }

    /**
     * Gets the value of the warehouseLocation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWarehouseLocation() {
        return warehouseLocation;
    }

    /**
     * Sets the value of the warehouseLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWarehouseLocation(String value) {
        this.warehouseLocation = value;
    }

    /**
     * Gets the value of the quantity property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getQuantity() {
        return quantity;
    }

    /**
     * Sets the value of the quantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setQuantity(Long value) {
        this.quantity = value;
    }

    /**
     * Gets the value of the amt property.
     * 
     * @return
     *     possible object is
     *     {@link CurAmtType }
     *     
     */
    public CurAmtType getAmt() {
        return amt;
    }

    /**
     * Sets the value of the amt property.
     * 
     * @param value
     *     allowed object is
     *     {@link CurAmtType }
     *     
     */
    public void setAmt(CurAmtType value) {
        this.amt = value;
    }

    /**
     * Gets the value of the weight property.
     * 
     * @return
     *     possible object is
     *     {@link WeightType }
     *     
     */
    public WeightType getWeight() {
        return weight;
    }

    /**
     * Sets the value of the weight property.
     * 
     * @param value
     *     allowed object is
     *     {@link WeightType }
     *     
     */
    public void setWeight(WeightType value) {
        this.weight = value;
    }

    /**
     * Gets the value of the width property.
     * 
     * @return
     *     possible object is
     *     {@link DimensionType }
     *     
     */
    public DimensionType getWidth() {
        return width;
    }

    /**
     * Sets the value of the width property.
     * 
     * @param value
     *     allowed object is
     *     {@link DimensionType }
     *     
     */
    public void setWidth(DimensionType value) {
        this.width = value;
    }

    /**
     * Gets the value of the height property.
     * 
     * @return
     *     possible object is
     *     {@link DimensionType }
     *     
     */
    public DimensionType getHeight() {
        return height;
    }

    /**
     * Sets the value of the height property.
     * 
     * @param value
     *     allowed object is
     *     {@link DimensionType }
     *     
     */
    public void setHeight(DimensionType value) {
        this.height = value;
    }

    /**
     * Gets the value of the length property.
     * 
     * @return
     *     possible object is
     *     {@link DimensionType }
     *     
     */
    public DimensionType getLength() {
        return length;
    }

    /**
     * Sets the value of the length property.
     * 
     * @param value
     *     allowed object is
     *     {@link DimensionType }
     *     
     */
    public void setLength(DimensionType value) {
        this.length = value;
    }

    /**
     * Gets the value of the itemExraDetails property.
     * 
     * @return
     *     possible object is
     *     {@link ItemExtraDetailsType }
     *     
     */
    public ItemExtraDetailsType getItemExraDetails() {
        return itemExraDetails;
    }

    /**
     * Sets the value of the itemExraDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link ItemExtraDetailsType }
     *     
     */
    public void setItemExraDetails(ItemExtraDetailsType value) {
        this.itemExraDetails = value;
    }

}
