//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.fawry.adapter_template.model.fawryType;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LookupRsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="LookupRsType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="RecCtrlOut" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}RecCtrlOutType" minOccurs="0"/>
 *         <element name="LookupsInfo" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}LookupsInfoType"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LookupRsType", propOrder = {
    "recCtrlOut",
    "lookupsInfo"
})
public class LookupRsType {

    @XmlElement(name = "RecCtrlOut")
    protected RecCtrlOutType recCtrlOut;
    @XmlElement(name = "LookupsInfo", required = true)
    protected LookupsInfoType lookupsInfo;

    /**
     * Gets the value of the recCtrlOut property.
     * 
     * @return
     *     possible object is
     *     {@link RecCtrlOutType }
     *     
     */
    public RecCtrlOutType getRecCtrlOut() {
        return recCtrlOut;
    }

    /**
     * Sets the value of the recCtrlOut property.
     * 
     * @param value
     *     allowed object is
     *     {@link RecCtrlOutType }
     *     
     */
    public void setRecCtrlOut(RecCtrlOutType value) {
        this.recCtrlOut = value;
    }

    /**
     * Gets the value of the lookupsInfo property.
     * 
     * @return
     *     possible object is
     *     {@link LookupsInfoType }
     *     
     */
    public LookupsInfoType getLookupsInfo() {
        return lookupsInfo;
    }

    /**
     * Sets the value of the lookupsInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link LookupsInfoType }
     *     
     */
    public void setLookupsInfo(LookupsInfoType value) {
        this.lookupsInfo = value;
    }

}
