//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.fawry.adapter_template.model.fawryType;

import jakarta.xml.bind.annotation.*;


/**
 * <p>Java class for MandatesDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="MandatesDataType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="MandateRecsData" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}MandateRecsDataType"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MandatesDataType", propOrder = {
    "mandateRecsData"
})
@XmlSeeAlso({
    MandateDataRqType.class
})
public class MandatesDataType {

    @XmlElement(name = "MandateRecsData", required = true)
    protected MandateRecsDataType mandateRecsData;

    /**
     * Gets the value of the mandateRecsData property.
     * 
     * @return
     *     possible object is
     *     {@link MandateRecsDataType }
     *     
     */
    public MandateRecsDataType getMandateRecsData() {
        return mandateRecsData;
    }

    /**
     * Sets the value of the mandateRecsData property.
     * 
     * @param value
     *     allowed object is
     *     {@link MandateRecsDataType }
     *     
     */
    public void setMandateRecsData(MandateRecsDataType value) {
        this.mandateRecsData = value;
    }

}
