//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.fawry.adapter_template.model.fawryType;

import jakarta.xml.bind.annotation.*;

import javax.xml.datatype.XMLGregorianCalendar;
import java.math.BigDecimal;


/**
 * <p>Java class for MandateDataRsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="MandateDataRsType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="OptType" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}OptTypeEnum" minOccurs="0"/>
 *         <element name="MandType" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}MandateTypeOpenEnum" minOccurs="0"/>
 *         <element name="BillerId" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}Identifier_Type" minOccurs="0"/>
 *         <element name="BillTypeCode" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         <element name="BillRefNumber" minOccurs="0">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               <maxLength value="36"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="BillingAcct" minOccurs="0">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               <maxLength value="128"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="ExtraBillingAcctKeys" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}ExtraBillingAcctKeysType" minOccurs="0"/>
 *         <element name="StrDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         <element name="EndDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         <element name="NoOfOccurs" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         <element name="DefSof" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}SourceOfFundSearchType" minOccurs="0"/>
 *         <element name="AltSof" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}SourceOfFundSearchType" minOccurs="0"/>
 *         <element name="MandUID" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}Identifier_Type" minOccurs="0"/>
 *         <element name="EnrUID" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}Identifier_Type" minOccurs="0"/>
 *         <element name="MandCurCode" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}CurCodeEnum" minOccurs="0"/>
 *         <element name="PmtPercentage" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         <element name="PmtThreshold" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         <element name="PayAmt" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         <element name="PayFreq" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}PayFreqType" minOccurs="0"/>
 *         <element name="DeactivationReason" minOccurs="0">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               <maxLength value="256"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="LastPayPaid" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         <element name="NextPayDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         <element name="PaidPmts" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         <element name="TotalAmtPaid" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         <element name="RemainingPmts" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         <element name="RemainingAmts" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         <element name="MandateStatus" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}MandateStatusOpenEnum" minOccurs="0"/>
 *         <element name="MBRN" minOccurs="0">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               <maxLength value="36"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="PmtType" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}PmtTypeEnum" minOccurs="0"/>
 *         <element name="CustData" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}CustDataType" minOccurs="0"/>
 *         <element name="BillerName" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}C160_Type" minOccurs="0"/>
 *         <element name="AdditionalDeactivationReason" minOccurs="0">
 *           <complexType>
 *             <complexContent>
 *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 <sequence>
 *                   <element name="Code">
 *                     <simpleType>
 *                       <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         <maxLength value="36"/>
 *                       </restriction>
 *                     </simpleType>
 *                   </element>
 *                   <element name="AdditionalInfo" minOccurs="0">
 *                     <simpleType>
 *                       <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         <maxLength value="500"/>
 *                       </restriction>
 *                     </simpleType>
 *                   </element>
 *                 </sequence>
 *               </restriction>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *         <element name="DtOfSignature" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         <element name="ToSOF" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}SourceOfFundSearchType" minOccurs="0"/>
 *         <element name="PmtSchemeCode" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}Identifier_Type" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MandateDataRsType", propOrder = {
    "optType",
    "mandType",
    "billerId",
    "billTypeCode",
    "billRefNumber",
    "billingAcct",
    "extraBillingAcctKeys",
    "strDate",
    "endDate",
    "noOfOccurs",
    "defSof",
    "altSof",
    "mandUID",
    "enrUID",
    "mandCurCode",
    "pmtPercentage",
    "pmtThreshold",
    "payAmt",
    "payFreq",
    "deactivationReason",
    "lastPayPaid",
    "nextPayDate",
    "paidPmts",
    "totalAmtPaid",
    "remainingPmts",
    "remainingAmts",
    "mandateStatus",
    "mbrn",
    "pmtType",
    "custData",
    "billerName",
    "additionalDeactivationReason",
    "dtOfSignature",
    "toSOF",
    "pmtSchemeCode"
})
public class MandateDataRsType {

    @XmlElement(name = "OptType")
    @XmlSchemaType(name = "string")
    protected OptTypeEnum optType;
    @XmlElement(name = "MandType")
    protected String mandType;
    @XmlElement(name = "BillerId")
    protected String billerId;
    @XmlElement(name = "BillTypeCode")
    protected Long billTypeCode;
    @XmlElement(name = "BillRefNumber")
    protected String billRefNumber;
    @XmlElement(name = "BillingAcct")
    protected String billingAcct;
    @XmlElement(name = "ExtraBillingAcctKeys")
    protected ExtraBillingAcctKeysType extraBillingAcctKeys;
    @XmlElement(name = "StrDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar strDate;
    @XmlElement(name = "EndDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar endDate;
    @XmlElement(name = "NoOfOccurs")
    protected Long noOfOccurs;
    @XmlElement(name = "DefSof")
    protected SourceOfFundSearchType defSof;
    @XmlElement(name = "AltSof")
    protected SourceOfFundSearchType altSof;
    @XmlElement(name = "MandUID")
    protected String mandUID;
    @XmlElement(name = "EnrUID")
    protected String enrUID;
    @XmlElement(name = "MandCurCode")
    @XmlSchemaType(name = "string")
    protected CurCodeEnum mandCurCode;
    @XmlElement(name = "PmtPercentage")
    protected BigDecimal pmtPercentage;
    @XmlElement(name = "PmtThreshold")
    protected BigDecimal pmtThreshold;
    @XmlElement(name = "PayAmt")
    protected BigDecimal payAmt;
    @XmlElement(name = "PayFreq")
    protected PayFreqType payFreq;
    @XmlElement(name = "DeactivationReason")
    protected String deactivationReason;
    @XmlElement(name = "LastPayPaid")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar lastPayPaid;
    @XmlElement(name = "NextPayDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar nextPayDate;
    @XmlElement(name = "PaidPmts")
    protected BigDecimal paidPmts;
    @XmlElement(name = "TotalAmtPaid")
    protected BigDecimal totalAmtPaid;
    @XmlElement(name = "RemainingPmts")
    protected BigDecimal remainingPmts;
    @XmlElement(name = "RemainingAmts")
    protected BigDecimal remainingAmts;
    @XmlElement(name = "MandateStatus")
    protected String mandateStatus;
    @XmlElement(name = "MBRN")
    protected String mbrn;
    @XmlElement(name = "PmtType")
    @XmlSchemaType(name = "string")
    protected PmtTypeEnum pmtType;
    @XmlElement(name = "CustData")
    protected CustDataType custData;
    @XmlElement(name = "BillerName")
    protected String billerName;
    @XmlElement(name = "AdditionalDeactivationReason")
    protected AdditionalDeactivationReason additionalDeactivationReason;
    @XmlElement(name = "DtOfSignature")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dtOfSignature;
    @XmlElement(name = "ToSOF")
    protected SourceOfFundSearchType toSOF;
    @XmlElement(name = "PmtSchemeCode")
    protected String pmtSchemeCode;

    /**
     * Gets the value of the optType property.
     * 
     * @return
     *     possible object is
     *     {@link OptTypeEnum }
     *     
     */
    public OptTypeEnum getOptType() {
        return optType;
    }

    /**
     * Sets the value of the optType property.
     * 
     * @param value
     *     allowed object is
     *     {@link OptTypeEnum }
     *     
     */
    public void setOptType(OptTypeEnum value) {
        this.optType = value;
    }

    /**
     * Gets the value of the mandType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMandType() {
        return mandType;
    }

    /**
     * Sets the value of the mandType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMandType(String value) {
        this.mandType = value;
    }

    /**
     * Gets the value of the billerId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillerId() {
        return billerId;
    }

    /**
     * Sets the value of the billerId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillerId(String value) {
        this.billerId = value;
    }

    /**
     * Gets the value of the billTypeCode property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getBillTypeCode() {
        return billTypeCode;
    }

    /**
     * Sets the value of the billTypeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setBillTypeCode(Long value) {
        this.billTypeCode = value;
    }

    /**
     * Gets the value of the billRefNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillRefNumber() {
        return billRefNumber;
    }

    /**
     * Sets the value of the billRefNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillRefNumber(String value) {
        this.billRefNumber = value;
    }

    /**
     * Gets the value of the billingAcct property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillingAcct() {
        return billingAcct;
    }

    /**
     * Sets the value of the billingAcct property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillingAcct(String value) {
        this.billingAcct = value;
    }

    /**
     * Gets the value of the extraBillingAcctKeys property.
     * 
     * @return
     *     possible object is
     *     {@link ExtraBillingAcctKeysType }
     *     
     */
    public ExtraBillingAcctKeysType getExtraBillingAcctKeys() {
        return extraBillingAcctKeys;
    }

    /**
     * Sets the value of the extraBillingAcctKeys property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExtraBillingAcctKeysType }
     *     
     */
    public void setExtraBillingAcctKeys(ExtraBillingAcctKeysType value) {
        this.extraBillingAcctKeys = value;
    }

    /**
     * Gets the value of the strDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getStrDate() {
        return strDate;
    }

    /**
     * Sets the value of the strDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setStrDate(XMLGregorianCalendar value) {
        this.strDate = value;
    }

    /**
     * Gets the value of the endDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEndDate() {
        return endDate;
    }

    /**
     * Sets the value of the endDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEndDate(XMLGregorianCalendar value) {
        this.endDate = value;
    }

    /**
     * Gets the value of the noOfOccurs property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getNoOfOccurs() {
        return noOfOccurs;
    }

    /**
     * Sets the value of the noOfOccurs property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setNoOfOccurs(Long value) {
        this.noOfOccurs = value;
    }

    /**
     * Gets the value of the defSof property.
     * 
     * @return
     *     possible object is
     *     {@link SourceOfFundSearchType }
     *     
     */
    public SourceOfFundSearchType getDefSof() {
        return defSof;
    }

    /**
     * Sets the value of the defSof property.
     * 
     * @param value
     *     allowed object is
     *     {@link SourceOfFundSearchType }
     *     
     */
    public void setDefSof(SourceOfFundSearchType value) {
        this.defSof = value;
    }

    /**
     * Gets the value of the altSof property.
     * 
     * @return
     *     possible object is
     *     {@link SourceOfFundSearchType }
     *     
     */
    public SourceOfFundSearchType getAltSof() {
        return altSof;
    }

    /**
     * Sets the value of the altSof property.
     * 
     * @param value
     *     allowed object is
     *     {@link SourceOfFundSearchType }
     *     
     */
    public void setAltSof(SourceOfFundSearchType value) {
        this.altSof = value;
    }

    /**
     * Gets the value of the mandUID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMandUID() {
        return mandUID;
    }

    /**
     * Sets the value of the mandUID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMandUID(String value) {
        this.mandUID = value;
    }

    /**
     * Gets the value of the enrUID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEnrUID() {
        return enrUID;
    }

    /**
     * Sets the value of the enrUID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEnrUID(String value) {
        this.enrUID = value;
    }

    /**
     * Gets the value of the mandCurCode property.
     * 
     * @return
     *     possible object is
     *     {@link CurCodeEnum }
     *     
     */
    public CurCodeEnum getMandCurCode() {
        return mandCurCode;
    }

    /**
     * Sets the value of the mandCurCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link CurCodeEnum }
     *     
     */
    public void setMandCurCode(CurCodeEnum value) {
        this.mandCurCode = value;
    }

    /**
     * Gets the value of the pmtPercentage property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPmtPercentage() {
        return pmtPercentage;
    }

    /**
     * Sets the value of the pmtPercentage property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPmtPercentage(BigDecimal value) {
        this.pmtPercentage = value;
    }

    /**
     * Gets the value of the pmtThreshold property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPmtThreshold() {
        return pmtThreshold;
    }

    /**
     * Sets the value of the pmtThreshold property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPmtThreshold(BigDecimal value) {
        this.pmtThreshold = value;
    }

    /**
     * Gets the value of the payAmt property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPayAmt() {
        return payAmt;
    }

    /**
     * Sets the value of the payAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPayAmt(BigDecimal value) {
        this.payAmt = value;
    }

    /**
     * Gets the value of the payFreq property.
     * 
     * @return
     *     possible object is
     *     {@link PayFreqType }
     *     
     */
    public PayFreqType getPayFreq() {
        return payFreq;
    }

    /**
     * Sets the value of the payFreq property.
     * 
     * @param value
     *     allowed object is
     *     {@link PayFreqType }
     *     
     */
    public void setPayFreq(PayFreqType value) {
        this.payFreq = value;
    }

    /**
     * Gets the value of the deactivationReason property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeactivationReason() {
        return deactivationReason;
    }

    /**
     * Sets the value of the deactivationReason property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeactivationReason(String value) {
        this.deactivationReason = value;
    }

    /**
     * Gets the value of the lastPayPaid property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLastPayPaid() {
        return lastPayPaid;
    }

    /**
     * Sets the value of the lastPayPaid property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLastPayPaid(XMLGregorianCalendar value) {
        this.lastPayPaid = value;
    }

    /**
     * Gets the value of the nextPayDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getNextPayDate() {
        return nextPayDate;
    }

    /**
     * Sets the value of the nextPayDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setNextPayDate(XMLGregorianCalendar value) {
        this.nextPayDate = value;
    }

    /**
     * Gets the value of the paidPmts property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPaidPmts() {
        return paidPmts;
    }

    /**
     * Sets the value of the paidPmts property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPaidPmts(BigDecimal value) {
        this.paidPmts = value;
    }

    /**
     * Gets the value of the totalAmtPaid property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTotalAmtPaid() {
        return totalAmtPaid;
    }

    /**
     * Sets the value of the totalAmtPaid property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTotalAmtPaid(BigDecimal value) {
        this.totalAmtPaid = value;
    }

    /**
     * Gets the value of the remainingPmts property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getRemainingPmts() {
        return remainingPmts;
    }

    /**
     * Sets the value of the remainingPmts property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setRemainingPmts(BigDecimal value) {
        this.remainingPmts = value;
    }

    /**
     * Gets the value of the remainingAmts property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getRemainingAmts() {
        return remainingAmts;
    }

    /**
     * Sets the value of the remainingAmts property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setRemainingAmts(BigDecimal value) {
        this.remainingAmts = value;
    }

    /**
     * Gets the value of the mandateStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMandateStatus() {
        return mandateStatus;
    }

    /**
     * Sets the value of the mandateStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMandateStatus(String value) {
        this.mandateStatus = value;
    }

    /**
     * Gets the value of the mbrn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMBRN() {
        return mbrn;
    }

    /**
     * Sets the value of the mbrn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMBRN(String value) {
        this.mbrn = value;
    }

    /**
     * Gets the value of the pmtType property.
     * 
     * @return
     *     possible object is
     *     {@link PmtTypeEnum }
     *     
     */
    public PmtTypeEnum getPmtType() {
        return pmtType;
    }

    /**
     * Sets the value of the pmtType property.
     * 
     * @param value
     *     allowed object is
     *     {@link PmtTypeEnum }
     *     
     */
    public void setPmtType(PmtTypeEnum value) {
        this.pmtType = value;
    }

    /**
     * Gets the value of the custData property.
     * 
     * @return
     *     possible object is
     *     {@link CustDataType }
     *     
     */
    public CustDataType getCustData() {
        return custData;
    }

    /**
     * Sets the value of the custData property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustDataType }
     *     
     */
    public void setCustData(CustDataType value) {
        this.custData = value;
    }

    /**
     * Gets the value of the billerName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillerName() {
        return billerName;
    }

    /**
     * Sets the value of the billerName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillerName(String value) {
        this.billerName = value;
    }

    /**
     * Gets the value of the additionalDeactivationReason property.
     * 
     * @return
     *     possible object is
     *     {@link AdditionalDeactivationReason }
     *     
     */
    public AdditionalDeactivationReason getAdditionalDeactivationReason() {
        return additionalDeactivationReason;
    }

    /**
     * Sets the value of the additionalDeactivationReason property.
     * 
     * @param value
     *     allowed object is
     *     {@link AdditionalDeactivationReason }
     *     
     */
    public void setAdditionalDeactivationReason(AdditionalDeactivationReason value) {
        this.additionalDeactivationReason = value;
    }

    /**
     * Gets the value of the dtOfSignature property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDtOfSignature() {
        return dtOfSignature;
    }

    /**
     * Sets the value of the dtOfSignature property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDtOfSignature(XMLGregorianCalendar value) {
        this.dtOfSignature = value;
    }

    /**
     * Gets the value of the toSOF property.
     * 
     * @return
     *     possible object is
     *     {@link SourceOfFundSearchType }
     *     
     */
    public SourceOfFundSearchType getToSOF() {
        return toSOF;
    }

    /**
     * Sets the value of the toSOF property.
     * 
     * @param value
     *     allowed object is
     *     {@link SourceOfFundSearchType }
     *     
     */
    public void setToSOF(SourceOfFundSearchType value) {
        this.toSOF = value;
    }

    /**
     * Gets the value of the pmtSchemeCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPmtSchemeCode() {
        return pmtSchemeCode;
    }

    /**
     * Sets the value of the pmtSchemeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPmtSchemeCode(String value) {
        this.pmtSchemeCode = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       <sequence>
     *         <element name="Code">
     *           <simpleType>
     *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               <maxLength value="36"/>
     *             </restriction>
     *           </simpleType>
     *         </element>
     *         <element name="AdditionalInfo" minOccurs="0">
     *           <simpleType>
     *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               <maxLength value="500"/>
     *             </restriction>
     *           </simpleType>
     *         </element>
     *       </sequence>
     *     </restriction>
     *   </complexContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "code",
        "additionalInfo"
    })
    public static class AdditionalDeactivationReason {

        @XmlElement(name = "Code", required = true)
        protected String code;
        @XmlElement(name = "AdditionalInfo")
        protected String additionalInfo;

        /**
         * Gets the value of the code property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCode() {
            return code;
        }

        /**
         * Sets the value of the code property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCode(String value) {
            this.code = value;
        }

        /**
         * Gets the value of the additionalInfo property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAdditionalInfo() {
            return additionalInfo;
        }

        /**
         * Sets the value of the additionalInfo property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAdditionalInfo(String value) {
            this.additionalInfo = value;
        }

    }

}
