//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.fawry.adapter_template.model.fawryType;

import jakarta.xml.bind.annotation.*;

import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for MessageRecType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="MessageRecType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <choice>
 *           <element name="ExMsgID">
 *             <simpleType>
 *               <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                 <minLength value="1"/>
 *                 <maxLength value="36"/>
 *               </restriction>
 *             </simpleType>
 *           </element>
 *           <element name="MsgID" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         </choice>
 *         <element name="MsgStartDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         <element name="MsgExpiryDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         <element name="MsgSubject">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               <minLength value="1"/>
 *               <maxLength value="40"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="MsgBody" minOccurs="0">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               <maxLength value="256"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="IsMandatory" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         <element name="MsgType" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}MsgTypeOpenEnum" minOccurs="0"/>
 *         <element name="MsgLang" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}LanguageOpenEnum"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MessageRecType", propOrder = {
    "exMsgID",
    "msgID",
    "msgStartDate",
    "msgExpiryDate",
    "msgSubject",
    "msgBody",
    "isMandatory",
    "msgType",
    "msgLang"
})
public class MessageRecType {

    @XmlElement(name = "ExMsgID")
    protected String exMsgID;
    @XmlElement(name = "MsgID")
    protected Long msgID;
    @XmlElement(name = "MsgStartDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar msgStartDate;
    @XmlElement(name = "MsgExpiryDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar msgExpiryDate;
    @XmlElement(name = "MsgSubject", required = true)
    protected String msgSubject;
    @XmlElement(name = "MsgBody")
    protected String msgBody;
    @XmlElement(name = "IsMandatory")
    protected Boolean isMandatory;
    @XmlElement(name = "MsgType")
    protected String msgType;
    @XmlElement(name = "MsgLang", required = true)
    protected String msgLang;

    /**
     * Gets the value of the exMsgID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExMsgID() {
        return exMsgID;
    }

    /**
     * Sets the value of the exMsgID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExMsgID(String value) {
        this.exMsgID = value;
    }

    /**
     * Gets the value of the msgID property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getMsgID() {
        return msgID;
    }

    /**
     * Sets the value of the msgID property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setMsgID(Long value) {
        this.msgID = value;
    }

    /**
     * Gets the value of the msgStartDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getMsgStartDate() {
        return msgStartDate;
    }

    /**
     * Sets the value of the msgStartDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setMsgStartDate(XMLGregorianCalendar value) {
        this.msgStartDate = value;
    }

    /**
     * Gets the value of the msgExpiryDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getMsgExpiryDate() {
        return msgExpiryDate;
    }

    /**
     * Sets the value of the msgExpiryDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setMsgExpiryDate(XMLGregorianCalendar value) {
        this.msgExpiryDate = value;
    }

    /**
     * Gets the value of the msgSubject property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMsgSubject() {
        return msgSubject;
    }

    /**
     * Sets the value of the msgSubject property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMsgSubject(String value) {
        this.msgSubject = value;
    }

    /**
     * Gets the value of the msgBody property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMsgBody() {
        return msgBody;
    }

    /**
     * Sets the value of the msgBody property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMsgBody(String value) {
        this.msgBody = value;
    }

    /**
     * Gets the value of the isMandatory property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsMandatory() {
        return isMandatory;
    }

    /**
     * Sets the value of the isMandatory property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsMandatory(Boolean value) {
        this.isMandatory = value;
    }

    /**
     * Gets the value of the msgType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMsgType() {
        return msgType;
    }

    /**
     * Sets the value of the msgType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMsgType(String value) {
        this.msgType = value;
    }

    /**
     * Gets the value of the msgLang property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMsgLang() {
        return msgLang;
    }

    /**
     * Sets the value of the msgLang property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMsgLang(String value) {
        this.msgLang = value;
    }

}
