//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.fawry.adapter_template.model.fawryType;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MngCustRqType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="MngCustRqType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="RecCtrlIn" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}RecCtrlInType" minOccurs="0"/>
 *         <element name="BankId" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}Identifier_Type"/>
 *         <element name="BillTypeCode" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         <element name="CustData" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}CustDataRqType"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MngCustRqType", propOrder = {
    "recCtrlIn",
    "bankId",
    "billTypeCode",
    "custData"
})
public class MngCustRqType {

    @XmlElement(name = "RecCtrlIn")
    protected RecCtrlInType recCtrlIn;
    @XmlElement(name = "BankId", required = true)
    protected String bankId;
    @XmlElement(name = "BillTypeCode")
    protected Long billTypeCode;
    @XmlElement(name = "CustData", required = true)
    protected CustDataRqType custData;

    /**
     * Gets the value of the recCtrlIn property.
     * 
     * @return
     *     possible object is
     *     {@link RecCtrlInType }
     *     
     */
    public RecCtrlInType getRecCtrlIn() {
        return recCtrlIn;
    }

    /**
     * Sets the value of the recCtrlIn property.
     * 
     * @param value
     *     allowed object is
     *     {@link RecCtrlInType }
     *     
     */
    public void setRecCtrlIn(RecCtrlInType value) {
        this.recCtrlIn = value;
    }

    /**
     * Gets the value of the bankId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBankId() {
        return bankId;
    }

    /**
     * Sets the value of the bankId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBankId(String value) {
        this.bankId = value;
    }

    /**
     * Gets the value of the billTypeCode property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getBillTypeCode() {
        return billTypeCode;
    }

    /**
     * Sets the value of the billTypeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setBillTypeCode(Long value) {
        this.billTypeCode = value;
    }

    /**
     * Gets the value of the custData property.
     * 
     * @return
     *     possible object is
     *     {@link CustDataRqType }
     *     
     */
    public CustDataRqType getCustData() {
        return custData;
    }

    /**
     * Sets the value of the custData property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustDataRqType }
     *     
     */
    public void setCustData(CustDataRqType value) {
        this.custData = value;
    }

}
