//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.fawry.adapter_template.model.fawryType;

import jakarta.xml.bind.annotation.*;


/**
 * <p>Java class for MngInboxRqType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="MngInboxRqType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="OptType" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}MngInboxOptType"/>
 *         <element name="AcctRec" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}AcctRecType" minOccurs="0"/>
 *         <element name="CSPRec" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}CSPRecType" minOccurs="0"/>
 *         <element name="InboxData" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}InboxDataType"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MngInboxRqType", propOrder = {
    "optType",
    "acctRec",
    "cspRec",
    "inboxData"
})
public class MngInboxRqType {

    @XmlElement(name = "OptType", required = true)
    @XmlSchemaType(name = "string")
    protected MngInboxOptType optType;
    @XmlElement(name = "AcctRec")
    protected AcctRecType acctRec;
    @XmlElement(name = "CSPRec")
    protected CSPRecType cspRec;
    @XmlElement(name = "InboxData", required = true)
    protected InboxDataType inboxData;

    /**
     * Gets the value of the optType property.
     * 
     * @return
     *     possible object is
     *     {@link MngInboxOptType }
     *     
     */
    public MngInboxOptType getOptType() {
        return optType;
    }

    /**
     * Sets the value of the optType property.
     * 
     * @param value
     *     allowed object is
     *     {@link MngInboxOptType }
     *     
     */
    public void setOptType(MngInboxOptType value) {
        this.optType = value;
    }

    /**
     * Gets the value of the acctRec property.
     * 
     * @return
     *     possible object is
     *     {@link AcctRecType }
     *     
     */
    public AcctRecType getAcctRec() {
        return acctRec;
    }

    /**
     * Sets the value of the acctRec property.
     * 
     * @param value
     *     allowed object is
     *     {@link AcctRecType }
     *     
     */
    public void setAcctRec(AcctRecType value) {
        this.acctRec = value;
    }

    /**
     * Gets the value of the cspRec property.
     * 
     * @return
     *     possible object is
     *     {@link CSPRecType }
     *     
     */
    public CSPRecType getCSPRec() {
        return cspRec;
    }

    /**
     * Sets the value of the cspRec property.
     * 
     * @param value
     *     allowed object is
     *     {@link CSPRecType }
     *     
     */
    public void setCSPRec(CSPRecType value) {
        this.cspRec = value;
    }

    /**
     * Gets the value of the inboxData property.
     * 
     * @return
     *     possible object is
     *     {@link InboxDataType }
     *     
     */
    public InboxDataType getInboxData() {
        return inboxData;
    }

    /**
     * Sets the value of the inboxData property.
     * 
     * @param value
     *     allowed object is
     *     {@link InboxDataType }
     *     
     */
    public void setInboxData(InboxDataType value) {
        this.inboxData = value;
    }

}
