//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.fawry.adapter_template.model.fawryType;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PaySvcRqType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="PaySvcRqType">
 *   <complexContent>
 *     <extension base="{http://www.fawry-eg.com/ebpp/IFXMessages/}SvcCommonType">
 *       <choice>
 *         <element name="PmtAddRq" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}PmtAddRqType"/>
 *         <element name="PmtAdvConfRq" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}PmtAdvConfRqType"/>
 *         <element name="PmtNotifyRq" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}PmtNotifyRqType"/>
 *         <element name="PmtAdvRq" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}PmtAdvRqType"/>
 *         <element name="PmtInqRq" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}PmtInqRqType"/>
 *         <element name="PmtReFireRq" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}PmtReFireRqType"/>
 *         <element name="CashoutRq" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}CashoutRqType"/>
 *         <element name="LinkCustPmtsRq" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}LinkCustPmtsRqType"/>
 *       </choice>
 *     </extension>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PaySvcRqType", propOrder = {
    "pmtAddRq",
    "pmtAdvConfRq",
    "pmtNotifyRq",
    "pmtAdvRq",
    "pmtInqRq",
    "pmtReFireRq",
    "cashoutRq",
    "linkCustPmtsRq"
})
public class PaySvcRqType
    extends SvcCommonType
{

    @XmlElement(name = "PmtAddRq")
    protected PmtAddRqType pmtAddRq;
    @XmlElement(name = "PmtAdvConfRq")
    protected PmtAdvConfRqType pmtAdvConfRq;
    @XmlElement(name = "PmtNotifyRq")
    protected PmtNotifyRqType pmtNotifyRq;
    @XmlElement(name = "PmtAdvRq")
    protected PmtAdvRqType pmtAdvRq;
    @XmlElement(name = "PmtInqRq")
    protected PmtInqRqType pmtInqRq;
    @XmlElement(name = "PmtReFireRq")
    protected PmtReFireRqType pmtReFireRq;
    @XmlElement(name = "CashoutRq")
    protected CashoutRqType cashoutRq;
    @XmlElement(name = "LinkCustPmtsRq")
    protected LinkCustPmtsRqType linkCustPmtsRq;

    /**
     * Gets the value of the pmtAddRq property.
     * 
     * @return
     *     possible object is
     *     {@link PmtAddRqType }
     *     
     */
    public PmtAddRqType getPmtAddRq() {
        return pmtAddRq;
    }

    /**
     * Sets the value of the pmtAddRq property.
     * 
     * @param value
     *     allowed object is
     *     {@link PmtAddRqType }
     *     
     */
    public void setPmtAddRq(PmtAddRqType value) {
        this.pmtAddRq = value;
    }

    /**
     * Gets the value of the pmtAdvConfRq property.
     * 
     * @return
     *     possible object is
     *     {@link PmtAdvConfRqType }
     *     
     */
    public PmtAdvConfRqType getPmtAdvConfRq() {
        return pmtAdvConfRq;
    }

    /**
     * Sets the value of the pmtAdvConfRq property.
     * 
     * @param value
     *     allowed object is
     *     {@link PmtAdvConfRqType }
     *     
     */
    public void setPmtAdvConfRq(PmtAdvConfRqType value) {
        this.pmtAdvConfRq = value;
    }

    /**
     * Gets the value of the pmtNotifyRq property.
     * 
     * @return
     *     possible object is
     *     {@link PmtNotifyRqType }
     *     
     */
    public PmtNotifyRqType getPmtNotifyRq() {
        return pmtNotifyRq;
    }

    /**
     * Sets the value of the pmtNotifyRq property.
     * 
     * @param value
     *     allowed object is
     *     {@link PmtNotifyRqType }
     *     
     */
    public void setPmtNotifyRq(PmtNotifyRqType value) {
        this.pmtNotifyRq = value;
    }

    /**
     * Gets the value of the pmtAdvRq property.
     * 
     * @return
     *     possible object is
     *     {@link PmtAdvRqType }
     *     
     */
    public PmtAdvRqType getPmtAdvRq() {
        return pmtAdvRq;
    }

    /**
     * Sets the value of the pmtAdvRq property.
     * 
     * @param value
     *     allowed object is
     *     {@link PmtAdvRqType }
     *     
     */
    public void setPmtAdvRq(PmtAdvRqType value) {
        this.pmtAdvRq = value;
    }

    /**
     * Gets the value of the pmtInqRq property.
     * 
     * @return
     *     possible object is
     *     {@link PmtInqRqType }
     *     
     */
    public PmtInqRqType getPmtInqRq() {
        return pmtInqRq;
    }

    /**
     * Sets the value of the pmtInqRq property.
     * 
     * @param value
     *     allowed object is
     *     {@link PmtInqRqType }
     *     
     */
    public void setPmtInqRq(PmtInqRqType value) {
        this.pmtInqRq = value;
    }

    /**
     * Gets the value of the pmtReFireRq property.
     * 
     * @return
     *     possible object is
     *     {@link PmtReFireRqType }
     *     
     */
    public PmtReFireRqType getPmtReFireRq() {
        return pmtReFireRq;
    }

    /**
     * Sets the value of the pmtReFireRq property.
     * 
     * @param value
     *     allowed object is
     *     {@link PmtReFireRqType }
     *     
     */
    public void setPmtReFireRq(PmtReFireRqType value) {
        this.pmtReFireRq = value;
    }

    /**
     * Gets the value of the cashoutRq property.
     * 
     * @return
     *     possible object is
     *     {@link CashoutRqType }
     *     
     */
    public CashoutRqType getCashoutRq() {
        return cashoutRq;
    }

    /**
     * Sets the value of the cashoutRq property.
     * 
     * @param value
     *     allowed object is
     *     {@link CashoutRqType }
     *     
     */
    public void setCashoutRq(CashoutRqType value) {
        this.cashoutRq = value;
    }

    /**
     * Gets the value of the linkCustPmtsRq property.
     * 
     * @return
     *     possible object is
     *     {@link LinkCustPmtsRqType }
     *     
     */
    public LinkCustPmtsRqType getLinkCustPmtsRq() {
        return linkCustPmtsRq;
    }

    /**
     * Sets the value of the linkCustPmtsRq property.
     * 
     * @param value
     *     allowed object is
     *     {@link LinkCustPmtsRqType }
     *     
     */
    public void setLinkCustPmtsRq(LinkCustPmtsRqType value) {
        this.linkCustPmtsRq = value;
    }

}
