//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.fawry.adapter_template.model.fawryType;

import jakarta.xml.bind.annotation.*;

import javax.xml.datatype.XMLGregorianCalendar;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for PayTrxRecType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="PayTrxRecType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="EnrAlias" minOccurs="0">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               <minLength value="1"/>
 *               <maxLength value="32"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="EnrUID" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}Identifier_Type" minOccurs="0"/>
 *         <element name="BillingAcct" minOccurs="0">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               <maxLength value="128"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="ExtraBillingAcctKeys" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}ExtraBillingAcctKeysType" minOccurs="0"/>
 *         <element name="PmtTransId" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}PmtTransIdType" maxOccurs="unbounded" minOccurs="0"/>
 *         <element name="PmtTrxStatus" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}PmtTxnSearchCodeEnum" minOccurs="0"/>
 *         <element name="PmtCorrelationFCRN" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         <element name="PmtNature" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}PmtInstNature" minOccurs="0"/>
 *         <element name="BillTypeCode" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         <element name="DeliveryMethod" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}DeliveryMethodOpenEnum" minOccurs="0"/>
 *         <element name="CompositeCurAmt" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}CompositeCurAmtType" maxOccurs="unbounded" minOccurs="0"/>
 *         <element name="BillInfo" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}BillInfoType" minOccurs="0"/>
 *         <element name="SOF" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}SOFType" minOccurs="0"/>
 *         <element name="AuthorizationNumber" minOccurs="0">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               <maxLength value="16"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="MerchantRefNumber" minOccurs="0">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               <maxLength value="40"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="PIFailureCode" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         <element name="TransactionDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         <element name="PaymentDesc" minOccurs="0">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               <maxLength value="64"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="ExtraPmtInfo" minOccurs="0">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               <maxLength value="512"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="VouchInfo" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}VouchInfoType" minOccurs="0"/>
 *         <element name="DiscountInfo" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}DiscountInfoType" minOccurs="0"/>
 *         <element name="InstallmentRule" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}InstallmentRuleType" minOccurs="0"/>
 *         <element name="GiftNum" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}GiftNumType" minOccurs="0"/>
 *         <element name="CustomProperties" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}CustomPropertiesType" minOccurs="0"/>
 *         <element name="BillerName" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}Identifier_Type" minOccurs="0"/>
 *         <element name="BillTypeName" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}Identifier_Type" minOccurs="0"/>
 *         <element name="MerchantType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         <element name="AuthorizationMessage" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         <element name="MerchantName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         <element name="TrxsLoanDetails" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}TrxsLoanDetailsType" minOccurs="0"/>
 *         <element name="CashbackInfo" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}CashbackInfoType" minOccurs="0"/>
 *         <element name="CampaignRedemptionInfo" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}CampaignRedemptionInfoType" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PayTrxRecType", propOrder = {
    "enrAlias",
    "enrUID",
    "billingAcct",
    "extraBillingAcctKeys",
    "pmtTransId",
    "pmtTrxStatus",
    "pmtCorrelationFCRN",
    "pmtNature",
    "billTypeCode",
    "deliveryMethod",
    "compositeCurAmt",
    "billInfo",
    "sof",
    "authorizationNumber",
    "merchantRefNumber",
    "piFailureCode",
    "transactionDateTime",
    "paymentDesc",
    "extraPmtInfo",
    "vouchInfo",
    "discountInfo",
    "installmentRule",
    "giftNum",
    "customProperties",
    "billerName",
    "billTypeName",
    "merchantType",
    "authorizationMessage",
    "merchantName",
    "trxsLoanDetails",
    "cashbackInfo",
    "campaignRedemptionInfo"
})
public class PayTrxRecType {

    @XmlElement(name = "EnrAlias")
    protected String enrAlias;
    @XmlElement(name = "EnrUID")
    protected String enrUID;
    @XmlElement(name = "BillingAcct")
    protected String billingAcct;
    @XmlElement(name = "ExtraBillingAcctKeys")
    protected ExtraBillingAcctKeysType extraBillingAcctKeys;
    @XmlElement(name = "PmtTransId")
    protected List<PmtTransIdType> pmtTransId;
    @XmlElement(name = "PmtTrxStatus")
    @XmlSchemaType(name = "string")
    protected PmtTxnSearchCodeEnum pmtTrxStatus;
    @XmlElement(name = "PmtCorrelationFCRN")
    protected String pmtCorrelationFCRN;
    @XmlElement(name = "PmtNature")
    @XmlSchemaType(name = "string")
    protected PmtInstNature pmtNature;
    @XmlElement(name = "BillTypeCode")
    protected Long billTypeCode;
    @XmlElement(name = "DeliveryMethod")
    protected String deliveryMethod;
    @XmlElement(name = "CompositeCurAmt")
    protected List<CompositeCurAmtType> compositeCurAmt;
    @XmlElement(name = "BillInfo")
    protected BillInfoType billInfo;
    @XmlElement(name = "SOF")
    protected SOFType sof;
    @XmlElement(name = "AuthorizationNumber")
    protected String authorizationNumber;
    @XmlElement(name = "MerchantRefNumber")
    protected String merchantRefNumber;
    @XmlElement(name = "PIFailureCode")
    protected Long piFailureCode;
    @XmlElement(name = "TransactionDateTime")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar transactionDateTime;
    @XmlElement(name = "PaymentDesc")
    protected String paymentDesc;
    @XmlElement(name = "ExtraPmtInfo")
    protected String extraPmtInfo;
    @XmlElement(name = "VouchInfo")
    protected VouchInfoType vouchInfo;
    @XmlElement(name = "DiscountInfo")
    protected DiscountInfoType discountInfo;
    @XmlElement(name = "InstallmentRule")
    protected InstallmentRuleType installmentRule;
    @XmlElement(name = "GiftNum")
    protected String giftNum;
    @XmlElement(name = "CustomProperties")
    protected CustomPropertiesType customProperties;
    @XmlElement(name = "BillerName")
    protected String billerName;
    @XmlElement(name = "BillTypeName")
    protected String billTypeName;
    @XmlElement(name = "MerchantType")
    protected String merchantType;
    @XmlElement(name = "AuthorizationMessage")
    protected String authorizationMessage;
    @XmlElement(name = "MerchantName")
    protected String merchantName;
    @XmlElement(name = "TrxsLoanDetails")
    protected TrxsLoanDetailsType trxsLoanDetails;
    @XmlElement(name = "CashbackInfo")
    protected CashbackInfoType cashbackInfo;
    @XmlElement(name = "CampaignRedemptionInfo")
    protected CampaignRedemptionInfoType campaignRedemptionInfo;

    /**
     * Gets the value of the enrAlias property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEnrAlias() {
        return enrAlias;
    }

    /**
     * Sets the value of the enrAlias property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEnrAlias(String value) {
        this.enrAlias = value;
    }

    /**
     * Gets the value of the enrUID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEnrUID() {
        return enrUID;
    }

    /**
     * Sets the value of the enrUID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEnrUID(String value) {
        this.enrUID = value;
    }

    /**
     * Gets the value of the billingAcct property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillingAcct() {
        return billingAcct;
    }

    /**
     * Sets the value of the billingAcct property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillingAcct(String value) {
        this.billingAcct = value;
    }

    /**
     * Gets the value of the extraBillingAcctKeys property.
     * 
     * @return
     *     possible object is
     *     {@link ExtraBillingAcctKeysType }
     *     
     */
    public ExtraBillingAcctKeysType getExtraBillingAcctKeys() {
        return extraBillingAcctKeys;
    }

    /**
     * Sets the value of the extraBillingAcctKeys property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExtraBillingAcctKeysType }
     *     
     */
    public void setExtraBillingAcctKeys(ExtraBillingAcctKeysType value) {
        this.extraBillingAcctKeys = value;
    }

    /**
     * Gets the value of the pmtTransId property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the pmtTransId property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPmtTransId().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PmtTransIdType }
     * 
     * 
     * @return
     *     The value of the pmtTransId property.
     */
    public List<PmtTransIdType> getPmtTransId() {
        if (pmtTransId == null) {
            pmtTransId = new ArrayList<>();
        }
        return this.pmtTransId;
    }

    /**
     * Gets the value of the pmtTrxStatus property.
     * 
     * @return
     *     possible object is
     *     {@link PmtTxnSearchCodeEnum }
     *     
     */
    public PmtTxnSearchCodeEnum getPmtTrxStatus() {
        return pmtTrxStatus;
    }

    /**
     * Sets the value of the pmtTrxStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link PmtTxnSearchCodeEnum }
     *     
     */
    public void setPmtTrxStatus(PmtTxnSearchCodeEnum value) {
        this.pmtTrxStatus = value;
    }

    /**
     * Gets the value of the pmtCorrelationFCRN property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPmtCorrelationFCRN() {
        return pmtCorrelationFCRN;
    }

    /**
     * Sets the value of the pmtCorrelationFCRN property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPmtCorrelationFCRN(String value) {
        this.pmtCorrelationFCRN = value;
    }

    /**
     * Gets the value of the pmtNature property.
     * 
     * @return
     *     possible object is
     *     {@link PmtInstNature }
     *     
     */
    public PmtInstNature getPmtNature() {
        return pmtNature;
    }

    /**
     * Sets the value of the pmtNature property.
     * 
     * @param value
     *     allowed object is
     *     {@link PmtInstNature }
     *     
     */
    public void setPmtNature(PmtInstNature value) {
        this.pmtNature = value;
    }

    /**
     * Gets the value of the billTypeCode property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getBillTypeCode() {
        return billTypeCode;
    }

    /**
     * Sets the value of the billTypeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setBillTypeCode(Long value) {
        this.billTypeCode = value;
    }

    /**
     * Gets the value of the deliveryMethod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeliveryMethod() {
        return deliveryMethod;
    }

    /**
     * Sets the value of the deliveryMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeliveryMethod(String value) {
        this.deliveryMethod = value;
    }

    /**
     * Gets the value of the compositeCurAmt property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the compositeCurAmt property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCompositeCurAmt().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CompositeCurAmtType }
     * 
     * 
     * @return
     *     The value of the compositeCurAmt property.
     */
    public List<CompositeCurAmtType> getCompositeCurAmt() {
        if (compositeCurAmt == null) {
            compositeCurAmt = new ArrayList<>();
        }
        return this.compositeCurAmt;
    }

    /**
     * Gets the value of the billInfo property.
     * 
     * @return
     *     possible object is
     *     {@link BillInfoType }
     *     
     */
    public BillInfoType getBillInfo() {
        return billInfo;
    }

    /**
     * Sets the value of the billInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link BillInfoType }
     *     
     */
    public void setBillInfo(BillInfoType value) {
        this.billInfo = value;
    }

    /**
     * Gets the value of the sof property.
     * 
     * @return
     *     possible object is
     *     {@link SOFType }
     *     
     */
    public SOFType getSOF() {
        return sof;
    }

    /**
     * Sets the value of the sof property.
     * 
     * @param value
     *     allowed object is
     *     {@link SOFType }
     *     
     */
    public void setSOF(SOFType value) {
        this.sof = value;
    }

    /**
     * Gets the value of the authorizationNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthorizationNumber() {
        return authorizationNumber;
    }

    /**
     * Sets the value of the authorizationNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthorizationNumber(String value) {
        this.authorizationNumber = value;
    }

    /**
     * Gets the value of the merchantRefNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMerchantRefNumber() {
        return merchantRefNumber;
    }

    /**
     * Sets the value of the merchantRefNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMerchantRefNumber(String value) {
        this.merchantRefNumber = value;
    }

    /**
     * Gets the value of the piFailureCode property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getPIFailureCode() {
        return piFailureCode;
    }

    /**
     * Sets the value of the piFailureCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setPIFailureCode(Long value) {
        this.piFailureCode = value;
    }

    /**
     * Gets the value of the transactionDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTransactionDateTime() {
        return transactionDateTime;
    }

    /**
     * Sets the value of the transactionDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTransactionDateTime(XMLGregorianCalendar value) {
        this.transactionDateTime = value;
    }

    /**
     * Gets the value of the paymentDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaymentDesc() {
        return paymentDesc;
    }

    /**
     * Sets the value of the paymentDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymentDesc(String value) {
        this.paymentDesc = value;
    }

    /**
     * Gets the value of the extraPmtInfo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExtraPmtInfo() {
        return extraPmtInfo;
    }

    /**
     * Sets the value of the extraPmtInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExtraPmtInfo(String value) {
        this.extraPmtInfo = value;
    }

    /**
     * Gets the value of the vouchInfo property.
     * 
     * @return
     *     possible object is
     *     {@link VouchInfoType }
     *     
     */
    public VouchInfoType getVouchInfo() {
        return vouchInfo;
    }

    /**
     * Sets the value of the vouchInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link VouchInfoType }
     *     
     */
    public void setVouchInfo(VouchInfoType value) {
        this.vouchInfo = value;
    }

    /**
     * Gets the value of the discountInfo property.
     * 
     * @return
     *     possible object is
     *     {@link DiscountInfoType }
     *     
     */
    public DiscountInfoType getDiscountInfo() {
        return discountInfo;
    }

    /**
     * Sets the value of the discountInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link DiscountInfoType }
     *     
     */
    public void setDiscountInfo(DiscountInfoType value) {
        this.discountInfo = value;
    }

    /**
     * Gets the value of the installmentRule property.
     * 
     * @return
     *     possible object is
     *     {@link InstallmentRuleType }
     *     
     */
    public InstallmentRuleType getInstallmentRule() {
        return installmentRule;
    }

    /**
     * Sets the value of the installmentRule property.
     * 
     * @param value
     *     allowed object is
     *     {@link InstallmentRuleType }
     *     
     */
    public void setInstallmentRule(InstallmentRuleType value) {
        this.installmentRule = value;
    }

    /**
     * Gets the value of the giftNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGiftNum() {
        return giftNum;
    }

    /**
     * Sets the value of the giftNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGiftNum(String value) {
        this.giftNum = value;
    }

    /**
     * Gets the value of the customProperties property.
     * 
     * @return
     *     possible object is
     *     {@link CustomPropertiesType }
     *     
     */
    public CustomPropertiesType getCustomProperties() {
        return customProperties;
    }

    /**
     * Sets the value of the customProperties property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustomPropertiesType }
     *     
     */
    public void setCustomProperties(CustomPropertiesType value) {
        this.customProperties = value;
    }

    /**
     * Gets the value of the billerName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillerName() {
        return billerName;
    }

    /**
     * Sets the value of the billerName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillerName(String value) {
        this.billerName = value;
    }

    /**
     * Gets the value of the billTypeName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillTypeName() {
        return billTypeName;
    }

    /**
     * Sets the value of the billTypeName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillTypeName(String value) {
        this.billTypeName = value;
    }

    /**
     * Gets the value of the merchantType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMerchantType() {
        return merchantType;
    }

    /**
     * Sets the value of the merchantType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMerchantType(String value) {
        this.merchantType = value;
    }

    /**
     * Gets the value of the authorizationMessage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthorizationMessage() {
        return authorizationMessage;
    }

    /**
     * Sets the value of the authorizationMessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthorizationMessage(String value) {
        this.authorizationMessage = value;
    }

    /**
     * Gets the value of the merchantName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMerchantName() {
        return merchantName;
    }

    /**
     * Sets the value of the merchantName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMerchantName(String value) {
        this.merchantName = value;
    }

    /**
     * Gets the value of the trxsLoanDetails property.
     * 
     * @return
     *     possible object is
     *     {@link TrxsLoanDetailsType }
     *     
     */
    public TrxsLoanDetailsType getTrxsLoanDetails() {
        return trxsLoanDetails;
    }

    /**
     * Sets the value of the trxsLoanDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link TrxsLoanDetailsType }
     *     
     */
    public void setTrxsLoanDetails(TrxsLoanDetailsType value) {
        this.trxsLoanDetails = value;
    }

    /**
     * Gets the value of the cashbackInfo property.
     * 
     * @return
     *     possible object is
     *     {@link CashbackInfoType }
     *     
     */
    public CashbackInfoType getCashbackInfo() {
        return cashbackInfo;
    }

    /**
     * Sets the value of the cashbackInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link CashbackInfoType }
     *     
     */
    public void setCashbackInfo(CashbackInfoType value) {
        this.cashbackInfo = value;
    }

    /**
     * Gets the value of the campaignRedemptionInfo property.
     * 
     * @return
     *     possible object is
     *     {@link CampaignRedemptionInfoType }
     *     
     */
    public CampaignRedemptionInfoType getCampaignRedemptionInfo() {
        return campaignRedemptionInfo;
    }

    /**
     * Sets the value of the campaignRedemptionInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link CampaignRedemptionInfoType }
     *     
     */
    public void setCampaignRedemptionInfo(CampaignRedemptionInfoType value) {
        this.campaignRedemptionInfo = value;
    }

}
