//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.fawry.adapter_template.model.fawryType;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;

import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for PmtAdvRqType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="PmtAdvRqType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="CustId" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}CustIdType" maxOccurs="unbounded" minOccurs="0"/>
 *         <element name="PmtRec" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}PmtRecType" maxOccurs="unbounded"/>
 *         <element name="AuthInfo" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}AuthInfoType" minOccurs="0"/>
 *         <element name="DiscountInfo" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}DiscountInfoType" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PmtAdvRqType", propOrder = {
    "custId",
    "pmtRec",
    "authInfo",
    "discountInfo"
})
public class PmtAdvRqType {

    @XmlElement(name = "CustId")
    protected List<CustIdType> custId;
    @XmlElement(name = "PmtRec", required = true)
    protected List<PmtRecType> pmtRec;
    @XmlElement(name = "AuthInfo")
    protected AuthInfoType authInfo;
    @XmlElement(name = "DiscountInfo")
    protected DiscountInfoType discountInfo;

    /**
     * Gets the value of the custId property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the custId property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCustId().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CustIdType }
     * 
     * 
     * @return
     *     The value of the custId property.
     */
    public List<CustIdType> getCustId() {
        if (custId == null) {
            custId = new ArrayList<>();
        }
        return this.custId;
    }

    /**
     * Gets the value of the pmtRec property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the pmtRec property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPmtRec().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PmtRecType }
     * 
     * 
     * @return
     *     The value of the pmtRec property.
     */
    public List<PmtRecType> getPmtRec() {
        if (pmtRec == null) {
            pmtRec = new ArrayList<>();
        }
        return this.pmtRec;
    }

    /**
     * Gets the value of the authInfo property.
     * 
     * @return
     *     possible object is
     *     {@link AuthInfoType }
     *     
     */
    public AuthInfoType getAuthInfo() {
        return authInfo;
    }

    /**
     * Sets the value of the authInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link AuthInfoType }
     *     
     */
    public void setAuthInfo(AuthInfoType value) {
        this.authInfo = value;
    }

    /**
     * Gets the value of the discountInfo property.
     * 
     * @return
     *     possible object is
     *     {@link DiscountInfoType }
     *     
     */
    public DiscountInfoType getDiscountInfo() {
        return discountInfo;
    }

    /**
     * Sets the value of the discountInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link DiscountInfoType }
     *     
     */
    public void setDiscountInfo(DiscountInfoType value) {
        this.discountInfo = value;
    }

}
