//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.fawry.adapter_template.model.fawryType;

import jakarta.xml.bind.annotation.*;

import javax.xml.datatype.XMLGregorianCalendar;
import java.math.BigDecimal;


/**
 * <p>Java class for PmtInstInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="PmtInstInfoType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="PmtDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         <element name="PmtInstStatus" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}PmtInstStatusOpenEnum"/>
 *         <element name="SOFId">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               <maxLength value="32"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="PIRN">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               <maxLength value="36"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="PIFailureCode" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         <element name="PmtInstNature" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}PmtInstNatureOpenEnum"/>
 *         <element name="PaymentAmount" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         <element name="FeesAmt" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}FeesAmtType" minOccurs="0"/>
 *         <element name="PmtTransRefNo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         <element name="AuthorizationNumber" minOccurs="0">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               <maxLength value="16"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="MerchantRefNumber" minOccurs="0">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               <maxLength value="40"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PmtInstInfoType", propOrder = {
    "pmtDate",
    "pmtInstStatus",
    "sofId",
    "pirn",
    "piFailureCode",
    "pmtInstNature",
    "paymentAmount",
    "feesAmt",
    "pmtTransRefNo",
    "authorizationNumber",
    "merchantRefNumber"
})
public class PmtInstInfoType {

    @XmlElement(name = "PmtDate", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar pmtDate;
    @XmlElement(name = "PmtInstStatus", required = true)
    protected String pmtInstStatus;
    @XmlElement(name = "SOFId", required = true)
    protected String sofId;
    @XmlElement(name = "PIRN", required = true)
    protected String pirn;
    @XmlElement(name = "PIFailureCode")
    protected Long piFailureCode;
    @XmlElement(name = "PmtInstNature", required = true)
    protected String pmtInstNature;
    @XmlElement(name = "PaymentAmount", required = true)
    protected BigDecimal paymentAmount;
    @XmlElement(name = "FeesAmt")
    protected FeesAmtType feesAmt;
    @XmlElement(name = "PmtTransRefNo")
    protected String pmtTransRefNo;
    @XmlElement(name = "AuthorizationNumber")
    protected String authorizationNumber;
    @XmlElement(name = "MerchantRefNumber")
    protected String merchantRefNumber;

    /**
     * Gets the value of the pmtDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPmtDate() {
        return pmtDate;
    }

    /**
     * Sets the value of the pmtDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPmtDate(XMLGregorianCalendar value) {
        this.pmtDate = value;
    }

    /**
     * Gets the value of the pmtInstStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPmtInstStatus() {
        return pmtInstStatus;
    }

    /**
     * Sets the value of the pmtInstStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPmtInstStatus(String value) {
        this.pmtInstStatus = value;
    }

    /**
     * Gets the value of the sofId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSOFId() {
        return sofId;
    }

    /**
     * Sets the value of the sofId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSOFId(String value) {
        this.sofId = value;
    }

    /**
     * Gets the value of the pirn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPIRN() {
        return pirn;
    }

    /**
     * Sets the value of the pirn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPIRN(String value) {
        this.pirn = value;
    }

    /**
     * Gets the value of the piFailureCode property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getPIFailureCode() {
        return piFailureCode;
    }

    /**
     * Sets the value of the piFailureCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setPIFailureCode(Long value) {
        this.piFailureCode = value;
    }

    /**
     * Gets the value of the pmtInstNature property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPmtInstNature() {
        return pmtInstNature;
    }

    /**
     * Sets the value of the pmtInstNature property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPmtInstNature(String value) {
        this.pmtInstNature = value;
    }

    /**
     * Gets the value of the paymentAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPaymentAmount() {
        return paymentAmount;
    }

    /**
     * Sets the value of the paymentAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPaymentAmount(BigDecimal value) {
        this.paymentAmount = value;
    }

    /**
     * Gets the value of the feesAmt property.
     * 
     * @return
     *     possible object is
     *     {@link FeesAmtType }
     *     
     */
    public FeesAmtType getFeesAmt() {
        return feesAmt;
    }

    /**
     * Sets the value of the feesAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link FeesAmtType }
     *     
     */
    public void setFeesAmt(FeesAmtType value) {
        this.feesAmt = value;
    }

    /**
     * Gets the value of the pmtTransRefNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPmtTransRefNo() {
        return pmtTransRefNo;
    }

    /**
     * Sets the value of the pmtTransRefNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPmtTransRefNo(String value) {
        this.pmtTransRefNo = value;
    }

    /**
     * Gets the value of the authorizationNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthorizationNumber() {
        return authorizationNumber;
    }

    /**
     * Sets the value of the authorizationNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthorizationNumber(String value) {
        this.authorizationNumber = value;
    }

    /**
     * Gets the value of the merchantRefNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMerchantRefNumber() {
        return merchantRefNumber;
    }

    /**
     * Sets the value of the merchantRefNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMerchantRefNumber(String value) {
        this.merchantRefNumber = value;
    }

}
