//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.fawry.adapter_template.model.fawryType;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PmtInstNature.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>{@code
 * <simpleType name="PmtInstNature">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <enumeration value="MANUAL"/>
 *     <enumeration value="SCHEDULED"/>
 *     <enumeration value="AUTOMATIC"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "PmtInstNature")
@XmlEnum
public enum PmtInstNature {

    MANUAL,
    SCHEDULED,
    AUTOMATIC;

    public String value() {
        return name();
    }

    public static PmtInstNature fromValue(String v) {
        return valueOf(v);
    }

}
