//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.fawry.adapter_template.model.fawryType;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PmtInstructRsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="PmtInstructRsType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence minOccurs="0">
 *         <element name="CustIds" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}CustIdsType" minOccurs="0"/>
 *         <element name="PmtStatusRec" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}PmtStatusRecType" minOccurs="0"/>
 *         <element name="PmtStatus" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}PmtStatusType" minOccurs="0"/>
 *         <element name="PmtInfo" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}PmtInfoType" minOccurs="0"/>
 *         <element name="MndtInfoType" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}MndtInfoType" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PmtInstructRsType", propOrder = {
    "custIds",
    "pmtStatusRec",
    "pmtStatus",
    "pmtInfo",
    "mndtInfoType"
})
public class PmtInstructRsType {

    @XmlElement(name = "CustIds")
    protected CustIdsType custIds;
    @XmlElement(name = "PmtStatusRec")
    protected PmtStatusRecType pmtStatusRec;
    @XmlElement(name = "PmtStatus")
    protected PmtStatusType pmtStatus;
    @XmlElement(name = "PmtInfo")
    protected PmtInfoType pmtInfo;
    @XmlElement(name = "MndtInfoType")
    protected MndtInfoType mndtInfoType;

    /**
     * Gets the value of the custIds property.
     * 
     * @return
     *     possible object is
     *     {@link CustIdsType }
     *     
     */
    public CustIdsType getCustIds() {
        return custIds;
    }

    /**
     * Sets the value of the custIds property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustIdsType }
     *     
     */
    public void setCustIds(CustIdsType value) {
        this.custIds = value;
    }

    /**
     * Gets the value of the pmtStatusRec property.
     * 
     * @return
     *     possible object is
     *     {@link PmtStatusRecType }
     *     
     */
    public PmtStatusRecType getPmtStatusRec() {
        return pmtStatusRec;
    }

    /**
     * Sets the value of the pmtStatusRec property.
     * 
     * @param value
     *     allowed object is
     *     {@link PmtStatusRecType }
     *     
     */
    public void setPmtStatusRec(PmtStatusRecType value) {
        this.pmtStatusRec = value;
    }

    /**
     * Gets the value of the pmtStatus property.
     * 
     * @return
     *     possible object is
     *     {@link PmtStatusType }
     *     
     */
    public PmtStatusType getPmtStatus() {
        return pmtStatus;
    }

    /**
     * Sets the value of the pmtStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link PmtStatusType }
     *     
     */
    public void setPmtStatus(PmtStatusType value) {
        this.pmtStatus = value;
    }

    /**
     * Gets the value of the pmtInfo property.
     * 
     * @return
     *     possible object is
     *     {@link PmtInfoType }
     *     
     */
    public PmtInfoType getPmtInfo() {
        return pmtInfo;
    }

    /**
     * Sets the value of the pmtInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link PmtInfoType }
     *     
     */
    public void setPmtInfo(PmtInfoType value) {
        this.pmtInfo = value;
    }

    /**
     * Gets the value of the mndtInfoType property.
     * 
     * @return
     *     possible object is
     *     {@link MndtInfoType }
     *     
     */
    public MndtInfoType getMndtInfoType() {
        return mndtInfoType;
    }

    /**
     * Sets the value of the mndtInfoType property.
     * 
     * @param value
     *     allowed object is
     *     {@link MndtInfoType }
     *     
     */
    public void setMndtInfoType(MndtInfoType value) {
        this.mndtInfoType = value;
    }

}
