//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.fawry.adapter_template.model.fawryType;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PmtldTypeEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>{@code
 * <simpleType name="PmtldTypeEnum">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <enumeration value="FPTN"/>
 *     <enumeration value="BLRPTN"/>
 *     <enumeration value="BNKPTN"/>
 *     <enumeration value="BNKDTN"/>
 *     <enumeration value="FCRN"/>
 *     <enumeration value="OBNKPTN"/>
 *     <enumeration value="ASYNCUID"/>
 *     <enumeration value="PTIN"/>
 *     <enumeration value="OASYNCUID"/>
 *     <enumeration value="OBLRPTN"/>
 *     <enumeration value="OBNKDTN"/>
 *     <enumeration value="OAUTHID"/>
 *     <enumeration value="OFCRN"/>
 *     <enumeration value="PDTN"/>
 *     <enumeration value="CORRUID"/>
 *     <enumeration value="NTN"/>
 *     <enumeration value="CTSID"/>
 *     <enumeration value="RQUID"/>
 *     <enumeration value="LONID"/>
 *     <enumeration value="CHAINUID"/>
 *     <maxLength value="10"/>
 *     <minLength value="1"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "PmtldTypeEnum")
@XmlEnum
public enum PmtldTypeEnum {

    FPTN,
    BLRPTN,
    BNKPTN,
    BNKDTN,
    FCRN,
    OBNKPTN,
    ASYNCUID,
    PTIN,
    OASYNCUID,
    OBLRPTN,
    OBNKDTN,
    OAUTHID,
    OFCRN,
    PDTN,
    CORRUID,
    NTN,
    CTSID,
    RQUID,
    LONID,
    CHAINUID;

    public String value() {
        return name();
    }

    public static PmtldTypeEnum fromValue(String v) {
        return valueOf(v);
    }

}
