//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.fawry.adapter_template.model.fawryType;

import jakarta.xml.bind.annotation.*;

import javax.xml.datatype.XMLGregorianCalendar;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for PmtTrxType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="PmtTrxType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="BillTypeCode" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         <element name="PmtTransId" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}PmtTransIdType" maxOccurs="unbounded" minOccurs="0"/>
 *         <element name="TransactionTime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         <element name="CurAmt" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}CurAmtType"/>
 *         <element name="FeesAmt" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}FeesAmtType" minOccurs="0"/>
 *         <element name="VatAmt" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}VatAmtType" minOccurs="0"/>
 *         <element name="TipsAmt" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}TipsAmtType" minOccurs="0"/>
 *         <element name="RefundAmt" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}RefundAmtType" minOccurs="0"/>
 *         <element name="AvailableRefundAmt" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}AvailableRefundAmtType" minOccurs="0"/>
 *         <element name="PmtStatus">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               <maxLength value="40"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="ClientTerminalSeqId" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}Identifier_Type" minOccurs="0"/>
 *         <element name="BillingAcct" minOccurs="0">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               <maxLength value="128"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="ExtraBillingAcctKeys" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}ExtraBillingAcctKeysType" minOccurs="0"/>
 *         <element name="CustomerCIF" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}Identifier_Type" minOccurs="0"/>
 *         <element name="VouchInfo" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}VouchInfoType" minOccurs="0"/>
 *         <element name="CustomProperties" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}CustomPropertiesType" minOccurs="0"/>
 *         <element name="DeliveryMethod" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}DeliveryMethodOpenEnum" minOccurs="0"/>
 *         <element name="PmtMethod" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}PmtMethodOpenEnum" minOccurs="0"/>
 *         <element name="CustomMessage" minOccurs="0">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               <maxLength value="256"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="DiscountInfo" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}DiscountInfoType" minOccurs="0"/>
 *         <element name="InstallmentRule" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}InstallmentRuleType" minOccurs="0"/>
 *         <element name="BillerId" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}Identifier_Type" minOccurs="0"/>
 *         <element name="BillerName" minOccurs="0">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               <maxLength value="40"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="BillTypeAcctLabel" minOccurs="0">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               <maxLength value="80"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="Name" minOccurs="0">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               <maxLength value="40"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="PmtType" minOccurs="0">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               <maxLength value="40"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="TotalAmt" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}CurAmtType" minOccurs="0"/>
 *         <element name="DisputeTicketNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         <element name="TerminalId" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}Identifier_Type" minOccurs="0"/>
 *         <element name="PaymentAccount" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         <element name="PaymentAccountType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         <element name="PmtInitiationStatus" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}PmtInitiationStatusType" minOccurs="0"/>
 *         <element name="PmtStatusDesc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         <element name="ExtraPmtInfo" minOccurs="0">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               <maxLength value="512"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="AuthInfo" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}AuthInfoType" minOccurs="0"/>
 *         <element name="LoyaltyInfo" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}LoyaltyInfoType" minOccurs="0"/>
 *         <element name="MerchantName" minOccurs="0">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               <maxLength value="256"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="TransactionType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         <element name="ReceiptHeader" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         <element name="PmtCorrelationFCRN" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         <element name="ReceiptFooter" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         <element name="ReceiptLogoName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         <element name="AcctInputMethod" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}AcctInputMethodOpenEnum" minOccurs="0"/>
 *         <element name="IsEmbeddedFees" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         <element name="BillInfo" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}BillInfoType" minOccurs="0"/>
 *         <element name="BillTypeType" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}BillTypeTypeOpenEnum" minOccurs="0"/>
 *         <element name="NotifyMobile" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         <element name="ChainUID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         <element name="IsSplitPmt" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         <element name="ExchangeRates" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}ExchangeRatesType" minOccurs="0"/>
 *         <element name="PosSerialNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PmtTrxType", propOrder = {
    "billTypeCode",
    "pmtTransId",
    "transactionTime",
    "curAmt",
    "feesAmt",
    "vatAmt",
    "tipsAmt",
    "refundAmt",
    "availableRefundAmt",
    "pmtStatus",
    "clientTerminalSeqId",
    "billingAcct",
    "extraBillingAcctKeys",
    "customerCIF",
    "vouchInfo",
    "customProperties",
    "deliveryMethod",
    "pmtMethod",
    "customMessage",
    "discountInfo",
    "installmentRule",
    "billerId",
    "billerName",
    "billTypeAcctLabel",
    "name",
    "pmtType",
    "totalAmt",
    "disputeTicketNumber",
    "terminalId",
    "paymentAccount",
    "paymentAccountType",
    "pmtInitiationStatus",
    "pmtStatusDesc",
    "extraPmtInfo",
    "authInfo",
    "loyaltyInfo",
    "merchantName",
    "transactionType",
    "receiptHeader",
    "pmtCorrelationFCRN",
    "receiptFooter",
    "receiptLogoName",
    "acctInputMethod",
    "isEmbeddedFees",
    "billInfo",
    "billTypeType",
    "notifyMobile",
    "chainUID",
    "isSplitPmt",
    "exchangeRates",
    "posSerialNumber"
})
public class PmtTrxType {

    @XmlElement(name = "BillTypeCode")
    protected long billTypeCode;
    @XmlElement(name = "PmtTransId")
    protected List<PmtTransIdType> pmtTransId;
    @XmlElement(name = "TransactionTime", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar transactionTime;
    @XmlElement(name = "CurAmt", required = true)
    protected CurAmtType curAmt;
    @XmlElement(name = "FeesAmt")
    protected FeesAmtType feesAmt;
    @XmlElement(name = "VatAmt")
    protected VatAmtType vatAmt;
    @XmlElement(name = "TipsAmt")
    protected TipsAmtType tipsAmt;
    @XmlElement(name = "RefundAmt")
    protected RefundAmtType refundAmt;
    @XmlElement(name = "AvailableRefundAmt")
    protected AvailableRefundAmtType availableRefundAmt;
    @XmlElement(name = "PmtStatus", required = true)
    protected String pmtStatus;
    @XmlElement(name = "ClientTerminalSeqId")
    protected String clientTerminalSeqId;
    @XmlElement(name = "BillingAcct")
    protected String billingAcct;
    @XmlElement(name = "ExtraBillingAcctKeys")
    protected ExtraBillingAcctKeysType extraBillingAcctKeys;
    @XmlElement(name = "CustomerCIF")
    protected String customerCIF;
    @XmlElement(name = "VouchInfo")
    protected VouchInfoType vouchInfo;
    @XmlElement(name = "CustomProperties")
    protected CustomPropertiesType customProperties;
    @XmlElement(name = "DeliveryMethod")
    protected String deliveryMethod;
    @XmlElement(name = "PmtMethod")
    protected String pmtMethod;
    @XmlElement(name = "CustomMessage")
    protected String customMessage;
    @XmlElement(name = "DiscountInfo")
    protected DiscountInfoType discountInfo;
    @XmlElement(name = "InstallmentRule")
    protected InstallmentRuleType installmentRule;
    @XmlElement(name = "BillerId")
    protected String billerId;
    @XmlElement(name = "BillerName")
    protected String billerName;
    @XmlElement(name = "BillTypeAcctLabel")
    protected String billTypeAcctLabel;
    @XmlElement(name = "Name")
    protected String name;
    @XmlElement(name = "PmtType")
    protected String pmtType;
    @XmlElement(name = "TotalAmt")
    protected CurAmtType totalAmt;
    @XmlElement(name = "DisputeTicketNumber")
    protected String disputeTicketNumber;
    @XmlElement(name = "TerminalId")
    protected String terminalId;
    @XmlElement(name = "PaymentAccount")
    protected String paymentAccount;
    @XmlElement(name = "PaymentAccountType")
    protected String paymentAccountType;
    @XmlElement(name = "PmtInitiationStatus")
    @XmlSchemaType(name = "string")
    protected PmtInitiationStatusType pmtInitiationStatus;
    @XmlElement(name = "PmtStatusDesc")
    protected String pmtStatusDesc;
    @XmlElement(name = "ExtraPmtInfo")
    protected String extraPmtInfo;
    @XmlElement(name = "AuthInfo")
    protected AuthInfoType authInfo;
    @XmlElement(name = "LoyaltyInfo")
    protected LoyaltyInfoType loyaltyInfo;
    @XmlElement(name = "MerchantName")
    protected String merchantName;
    @XmlElement(name = "TransactionType")
    protected String transactionType;
    @XmlElement(name = "ReceiptHeader")
    protected String receiptHeader;
    @XmlElement(name = "PmtCorrelationFCRN")
    protected String pmtCorrelationFCRN;
    @XmlElement(name = "ReceiptFooter")
    protected String receiptFooter;
    @XmlElement(name = "ReceiptLogoName")
    protected String receiptLogoName;
    @XmlElement(name = "AcctInputMethod")
    protected String acctInputMethod;
    @XmlElement(name = "IsEmbeddedFees")
    protected Boolean isEmbeddedFees;
    @XmlElement(name = "BillInfo")
    protected BillInfoType billInfo;
    @XmlElement(name = "BillTypeType")
    protected String billTypeType;
    @XmlElement(name = "NotifyMobile")
    protected String notifyMobile;
    @XmlElement(name = "ChainUID")
    protected String chainUID;
    @XmlElement(name = "IsSplitPmt")
    protected String isSplitPmt;
    @XmlElement(name = "ExchangeRates")
    protected ExchangeRatesType exchangeRates;
    @XmlElement(name = "PosSerialNumber")
    protected String posSerialNumber;

    /**
     * Gets the value of the billTypeCode property.
     * 
     */
    public long getBillTypeCode() {
        return billTypeCode;
    }

    /**
     * Sets the value of the billTypeCode property.
     * 
     */
    public void setBillTypeCode(long value) {
        this.billTypeCode = value;
    }

    /**
     * Gets the value of the pmtTransId property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the pmtTransId property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPmtTransId().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PmtTransIdType }
     * 
     * 
     * @return
     *     The value of the pmtTransId property.
     */
    public List<PmtTransIdType> getPmtTransId() {
        if (pmtTransId == null) {
            pmtTransId = new ArrayList<>();
        }
        return this.pmtTransId;
    }

    /**
     * Gets the value of the transactionTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTransactionTime() {
        return transactionTime;
    }

    /**
     * Sets the value of the transactionTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTransactionTime(XMLGregorianCalendar value) {
        this.transactionTime = value;
    }

    /**
     * Gets the value of the curAmt property.
     * 
     * @return
     *     possible object is
     *     {@link CurAmtType }
     *     
     */
    public CurAmtType getCurAmt() {
        return curAmt;
    }

    /**
     * Sets the value of the curAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link CurAmtType }
     *     
     */
    public void setCurAmt(CurAmtType value) {
        this.curAmt = value;
    }

    /**
     * Gets the value of the feesAmt property.
     * 
     * @return
     *     possible object is
     *     {@link FeesAmtType }
     *     
     */
    public FeesAmtType getFeesAmt() {
        return feesAmt;
    }

    /**
     * Sets the value of the feesAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link FeesAmtType }
     *     
     */
    public void setFeesAmt(FeesAmtType value) {
        this.feesAmt = value;
    }

    /**
     * Gets the value of the vatAmt property.
     * 
     * @return
     *     possible object is
     *     {@link VatAmtType }
     *     
     */
    public VatAmtType getVatAmt() {
        return vatAmt;
    }

    /**
     * Sets the value of the vatAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link VatAmtType }
     *     
     */
    public void setVatAmt(VatAmtType value) {
        this.vatAmt = value;
    }

    /**
     * Gets the value of the tipsAmt property.
     * 
     * @return
     *     possible object is
     *     {@link TipsAmtType }
     *     
     */
    public TipsAmtType getTipsAmt() {
        return tipsAmt;
    }

    /**
     * Sets the value of the tipsAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipsAmtType }
     *     
     */
    public void setTipsAmt(TipsAmtType value) {
        this.tipsAmt = value;
    }

    /**
     * Gets the value of the refundAmt property.
     * 
     * @return
     *     possible object is
     *     {@link RefundAmtType }
     *     
     */
    public RefundAmtType getRefundAmt() {
        return refundAmt;
    }

    /**
     * Sets the value of the refundAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link RefundAmtType }
     *     
     */
    public void setRefundAmt(RefundAmtType value) {
        this.refundAmt = value;
    }

    /**
     * Gets the value of the availableRefundAmt property.
     * 
     * @return
     *     possible object is
     *     {@link AvailableRefundAmtType }
     *     
     */
    public AvailableRefundAmtType getAvailableRefundAmt() {
        return availableRefundAmt;
    }

    /**
     * Sets the value of the availableRefundAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link AvailableRefundAmtType }
     *     
     */
    public void setAvailableRefundAmt(AvailableRefundAmtType value) {
        this.availableRefundAmt = value;
    }

    /**
     * Gets the value of the pmtStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPmtStatus() {
        return pmtStatus;
    }

    /**
     * Sets the value of the pmtStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPmtStatus(String value) {
        this.pmtStatus = value;
    }

    /**
     * Gets the value of the clientTerminalSeqId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClientTerminalSeqId() {
        return clientTerminalSeqId;
    }

    /**
     * Sets the value of the clientTerminalSeqId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClientTerminalSeqId(String value) {
        this.clientTerminalSeqId = value;
    }

    /**
     * Gets the value of the billingAcct property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillingAcct() {
        return billingAcct;
    }

    /**
     * Sets the value of the billingAcct property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillingAcct(String value) {
        this.billingAcct = value;
    }

    /**
     * Gets the value of the extraBillingAcctKeys property.
     * 
     * @return
     *     possible object is
     *     {@link ExtraBillingAcctKeysType }
     *     
     */
    public ExtraBillingAcctKeysType getExtraBillingAcctKeys() {
        return extraBillingAcctKeys;
    }

    /**
     * Sets the value of the extraBillingAcctKeys property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExtraBillingAcctKeysType }
     *     
     */
    public void setExtraBillingAcctKeys(ExtraBillingAcctKeysType value) {
        this.extraBillingAcctKeys = value;
    }

    /**
     * Gets the value of the customerCIF property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerCIF() {
        return customerCIF;
    }

    /**
     * Sets the value of the customerCIF property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerCIF(String value) {
        this.customerCIF = value;
    }

    /**
     * Gets the value of the vouchInfo property.
     * 
     * @return
     *     possible object is
     *     {@link VouchInfoType }
     *     
     */
    public VouchInfoType getVouchInfo() {
        return vouchInfo;
    }

    /**
     * Sets the value of the vouchInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link VouchInfoType }
     *     
     */
    public void setVouchInfo(VouchInfoType value) {
        this.vouchInfo = value;
    }

    /**
     * Gets the value of the customProperties property.
     * 
     * @return
     *     possible object is
     *     {@link CustomPropertiesType }
     *     
     */
    public CustomPropertiesType getCustomProperties() {
        return customProperties;
    }

    /**
     * Sets the value of the customProperties property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustomPropertiesType }
     *     
     */
    public void setCustomProperties(CustomPropertiesType value) {
        this.customProperties = value;
    }

    /**
     * Gets the value of the deliveryMethod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeliveryMethod() {
        return deliveryMethod;
    }

    /**
     * Sets the value of the deliveryMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeliveryMethod(String value) {
        this.deliveryMethod = value;
    }

    /**
     * Gets the value of the pmtMethod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPmtMethod() {
        return pmtMethod;
    }

    /**
     * Sets the value of the pmtMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPmtMethod(String value) {
        this.pmtMethod = value;
    }

    /**
     * Gets the value of the customMessage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomMessage() {
        return customMessage;
    }

    /**
     * Sets the value of the customMessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomMessage(String value) {
        this.customMessage = value;
    }

    /**
     * Gets the value of the discountInfo property.
     * 
     * @return
     *     possible object is
     *     {@link DiscountInfoType }
     *     
     */
    public DiscountInfoType getDiscountInfo() {
        return discountInfo;
    }

    /**
     * Sets the value of the discountInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link DiscountInfoType }
     *     
     */
    public void setDiscountInfo(DiscountInfoType value) {
        this.discountInfo = value;
    }

    /**
     * Gets the value of the installmentRule property.
     * 
     * @return
     *     possible object is
     *     {@link InstallmentRuleType }
     *     
     */
    public InstallmentRuleType getInstallmentRule() {
        return installmentRule;
    }

    /**
     * Sets the value of the installmentRule property.
     * 
     * @param value
     *     allowed object is
     *     {@link InstallmentRuleType }
     *     
     */
    public void setInstallmentRule(InstallmentRuleType value) {
        this.installmentRule = value;
    }

    /**
     * Gets the value of the billerId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillerId() {
        return billerId;
    }

    /**
     * Sets the value of the billerId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillerId(String value) {
        this.billerId = value;
    }

    /**
     * Gets the value of the billerName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillerName() {
        return billerName;
    }

    /**
     * Sets the value of the billerName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillerName(String value) {
        this.billerName = value;
    }

    /**
     * Gets the value of the billTypeAcctLabel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillTypeAcctLabel() {
        return billTypeAcctLabel;
    }

    /**
     * Sets the value of the billTypeAcctLabel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillTypeAcctLabel(String value) {
        this.billTypeAcctLabel = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the pmtType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPmtType() {
        return pmtType;
    }

    /**
     * Sets the value of the pmtType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPmtType(String value) {
        this.pmtType = value;
    }

    /**
     * Gets the value of the totalAmt property.
     * 
     * @return
     *     possible object is
     *     {@link CurAmtType }
     *     
     */
    public CurAmtType getTotalAmt() {
        return totalAmt;
    }

    /**
     * Sets the value of the totalAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link CurAmtType }
     *     
     */
    public void setTotalAmt(CurAmtType value) {
        this.totalAmt = value;
    }

    /**
     * Gets the value of the disputeTicketNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisputeTicketNumber() {
        return disputeTicketNumber;
    }

    /**
     * Sets the value of the disputeTicketNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisputeTicketNumber(String value) {
        this.disputeTicketNumber = value;
    }

    /**
     * Gets the value of the terminalId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTerminalId() {
        return terminalId;
    }

    /**
     * Sets the value of the terminalId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTerminalId(String value) {
        this.terminalId = value;
    }

    /**
     * Gets the value of the paymentAccount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaymentAccount() {
        return paymentAccount;
    }

    /**
     * Sets the value of the paymentAccount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymentAccount(String value) {
        this.paymentAccount = value;
    }

    /**
     * Gets the value of the paymentAccountType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaymentAccountType() {
        return paymentAccountType;
    }

    /**
     * Sets the value of the paymentAccountType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymentAccountType(String value) {
        this.paymentAccountType = value;
    }

    /**
     * Gets the value of the pmtInitiationStatus property.
     * 
     * @return
     *     possible object is
     *     {@link PmtInitiationStatusType }
     *     
     */
    public PmtInitiationStatusType getPmtInitiationStatus() {
        return pmtInitiationStatus;
    }

    /**
     * Sets the value of the pmtInitiationStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link PmtInitiationStatusType }
     *     
     */
    public void setPmtInitiationStatus(PmtInitiationStatusType value) {
        this.pmtInitiationStatus = value;
    }

    /**
     * Gets the value of the pmtStatusDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPmtStatusDesc() {
        return pmtStatusDesc;
    }

    /**
     * Sets the value of the pmtStatusDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPmtStatusDesc(String value) {
        this.pmtStatusDesc = value;
    }

    /**
     * Gets the value of the extraPmtInfo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExtraPmtInfo() {
        return extraPmtInfo;
    }

    /**
     * Sets the value of the extraPmtInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExtraPmtInfo(String value) {
        this.extraPmtInfo = value;
    }

    /**
     * Gets the value of the authInfo property.
     * 
     * @return
     *     possible object is
     *     {@link AuthInfoType }
     *     
     */
    public AuthInfoType getAuthInfo() {
        return authInfo;
    }

    /**
     * Sets the value of the authInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link AuthInfoType }
     *     
     */
    public void setAuthInfo(AuthInfoType value) {
        this.authInfo = value;
    }

    /**
     * Gets the value of the loyaltyInfo property.
     * 
     * @return
     *     possible object is
     *     {@link LoyaltyInfoType }
     *     
     */
    public LoyaltyInfoType getLoyaltyInfo() {
        return loyaltyInfo;
    }

    /**
     * Sets the value of the loyaltyInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link LoyaltyInfoType }
     *     
     */
    public void setLoyaltyInfo(LoyaltyInfoType value) {
        this.loyaltyInfo = value;
    }

    /**
     * Gets the value of the merchantName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMerchantName() {
        return merchantName;
    }

    /**
     * Sets the value of the merchantName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMerchantName(String value) {
        this.merchantName = value;
    }

    /**
     * Gets the value of the transactionType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransactionType() {
        return transactionType;
    }

    /**
     * Sets the value of the transactionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransactionType(String value) {
        this.transactionType = value;
    }

    /**
     * Gets the value of the receiptHeader property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReceiptHeader() {
        return receiptHeader;
    }

    /**
     * Sets the value of the receiptHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReceiptHeader(String value) {
        this.receiptHeader = value;
    }

    /**
     * Gets the value of the pmtCorrelationFCRN property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPmtCorrelationFCRN() {
        return pmtCorrelationFCRN;
    }

    /**
     * Sets the value of the pmtCorrelationFCRN property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPmtCorrelationFCRN(String value) {
        this.pmtCorrelationFCRN = value;
    }

    /**
     * Gets the value of the receiptFooter property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReceiptFooter() {
        return receiptFooter;
    }

    /**
     * Sets the value of the receiptFooter property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReceiptFooter(String value) {
        this.receiptFooter = value;
    }

    /**
     * Gets the value of the receiptLogoName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReceiptLogoName() {
        return receiptLogoName;
    }

    /**
     * Sets the value of the receiptLogoName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReceiptLogoName(String value) {
        this.receiptLogoName = value;
    }

    /**
     * Gets the value of the acctInputMethod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAcctInputMethod() {
        return acctInputMethod;
    }

    /**
     * Sets the value of the acctInputMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAcctInputMethod(String value) {
        this.acctInputMethod = value;
    }

    /**
     * Gets the value of the isEmbeddedFees property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsEmbeddedFees() {
        return isEmbeddedFees;
    }

    /**
     * Sets the value of the isEmbeddedFees property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsEmbeddedFees(Boolean value) {
        this.isEmbeddedFees = value;
    }

    /**
     * Gets the value of the billInfo property.
     * 
     * @return
     *     possible object is
     *     {@link BillInfoType }
     *     
     */
    public BillInfoType getBillInfo() {
        return billInfo;
    }

    /**
     * Sets the value of the billInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link BillInfoType }
     *     
     */
    public void setBillInfo(BillInfoType value) {
        this.billInfo = value;
    }

    /**
     * Gets the value of the billTypeType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillTypeType() {
        return billTypeType;
    }

    /**
     * Sets the value of the billTypeType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillTypeType(String value) {
        this.billTypeType = value;
    }

    /**
     * Gets the value of the notifyMobile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNotifyMobile() {
        return notifyMobile;
    }

    /**
     * Sets the value of the notifyMobile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNotifyMobile(String value) {
        this.notifyMobile = value;
    }

    /**
     * Gets the value of the chainUID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChainUID() {
        return chainUID;
    }

    /**
     * Sets the value of the chainUID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChainUID(String value) {
        this.chainUID = value;
    }

    /**
     * Gets the value of the isSplitPmt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsSplitPmt() {
        return isSplitPmt;
    }

    /**
     * Sets the value of the isSplitPmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsSplitPmt(String value) {
        this.isSplitPmt = value;
    }

    /**
     * Gets the value of the exchangeRates property.
     * 
     * @return
     *     possible object is
     *     {@link ExchangeRatesType }
     *     
     */
    public ExchangeRatesType getExchangeRates() {
        return exchangeRates;
    }

    /**
     * Sets the value of the exchangeRates property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExchangeRatesType }
     *     
     */
    public void setExchangeRates(ExchangeRatesType value) {
        this.exchangeRates = value;
    }

    /**
     * Gets the value of the posSerialNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPosSerialNumber() {
        return posSerialNumber;
    }

    /**
     * Sets the value of the posSerialNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPosSerialNumber(String value) {
        this.posSerialNumber = value;
    }

}
