//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.fawry.adapter_template.model.fawryType;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PresSvcRsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="PresSvcRsType">
 *   <complexContent>
 *     <extension base="{http://www.fawry-eg.com/ebpp/IFXMessages/}SvcRsCommonType">
 *       <choice>
 *         <element name="BillInqRs" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}BillInqRsType"/>
 *         <element name="BillUploadRs" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}BillUploadRsType"/>
 *         <element name="VouchUploadRs" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}VouchUploadRsType"/>
 *         <element name="BillerInqRs" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}BillerInqRsType"/>
 *         <element name="NotificationModelRs" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}NotificationModelRsType"/>
 *         <element name="GetShippingFeesRs" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}GetShippingFeesRsType"/>
 *         <element name="MngOrderRs" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}MngOrderRsType"/>
 *         <element name="GetOrderRs" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}GetOrdersRsType"/>
 *         <element name="BalanceInqRs" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}BalanceInqRsType"/>
 *         <element name="BalanceSheetRs" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}BalanceSheetRsType"/>
 *         <element name="GetDashboardRs" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}GetDashboardRsType"/>
 *         <element name="BillersStructureRs" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}BillersStructureRsType"/>
 *       </choice>
 *     </extension>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PresSvcRsType", propOrder = {
    "billInqRs",
    "billUploadRs",
    "vouchUploadRs",
    "billerInqRs",
    "notificationModelRs",
    "getShippingFeesRs",
    "mngOrderRs",
    "getOrderRs",
    "balanceInqRs",
    "balanceSheetRs",
    "getDashboardRs",
    "billersStructureRs"
})
public class PresSvcRsType
    extends SvcRsCommonType
{

    @XmlElement(name = "BillInqRs")
    protected BillInqRsType billInqRs;
    @XmlElement(name = "BillUploadRs")
    protected BillUploadRsType billUploadRs;
    @XmlElement(name = "VouchUploadRs")
    protected VouchUploadRsType vouchUploadRs;
    @XmlElement(name = "BillerInqRs")
    protected BillerInqRsType billerInqRs;
    @XmlElement(name = "NotificationModelRs")
    protected NotificationModelRsType notificationModelRs;
    @XmlElement(name = "GetShippingFeesRs")
    protected GetShippingFeesRsType getShippingFeesRs;
    @XmlElement(name = "MngOrderRs")
    protected MngOrderRsType mngOrderRs;
    @XmlElement(name = "GetOrderRs")
    protected GetOrdersRsType getOrderRs;
    @XmlElement(name = "BalanceInqRs")
    protected BalanceInqRsType balanceInqRs;
    @XmlElement(name = "BalanceSheetRs")
    protected BalanceSheetRsType balanceSheetRs;
    @XmlElement(name = "GetDashboardRs")
    protected GetDashboardRsType getDashboardRs;
    @XmlElement(name = "BillersStructureRs")
    protected BillersStructureRsType billersStructureRs;

    /**
     * Gets the value of the billInqRs property.
     * 
     * @return
     *     possible object is
     *     {@link BillInqRsType }
     *     
     */
    public BillInqRsType getBillInqRs() {
        return billInqRs;
    }

    /**
     * Sets the value of the billInqRs property.
     * 
     * @param value
     *     allowed object is
     *     {@link BillInqRsType }
     *     
     */
    public void setBillInqRs(BillInqRsType value) {
        this.billInqRs = value;
    }

    /**
     * Gets the value of the billUploadRs property.
     * 
     * @return
     *     possible object is
     *     {@link BillUploadRsType }
     *     
     */
    public BillUploadRsType getBillUploadRs() {
        return billUploadRs;
    }

    /**
     * Sets the value of the billUploadRs property.
     * 
     * @param value
     *     allowed object is
     *     {@link BillUploadRsType }
     *     
     */
    public void setBillUploadRs(BillUploadRsType value) {
        this.billUploadRs = value;
    }

    /**
     * Gets the value of the vouchUploadRs property.
     * 
     * @return
     *     possible object is
     *     {@link VouchUploadRsType }
     *     
     */
    public VouchUploadRsType getVouchUploadRs() {
        return vouchUploadRs;
    }

    /**
     * Sets the value of the vouchUploadRs property.
     * 
     * @param value
     *     allowed object is
     *     {@link VouchUploadRsType }
     *     
     */
    public void setVouchUploadRs(VouchUploadRsType value) {
        this.vouchUploadRs = value;
    }

    /**
     * Gets the value of the billerInqRs property.
     * 
     * @return
     *     possible object is
     *     {@link BillerInqRsType }
     *     
     */
    public BillerInqRsType getBillerInqRs() {
        return billerInqRs;
    }

    /**
     * Sets the value of the billerInqRs property.
     * 
     * @param value
     *     allowed object is
     *     {@link BillerInqRsType }
     *     
     */
    public void setBillerInqRs(BillerInqRsType value) {
        this.billerInqRs = value;
    }

    /**
     * Gets the value of the notificationModelRs property.
     * 
     * @return
     *     possible object is
     *     {@link NotificationModelRsType }
     *     
     */
    public NotificationModelRsType getNotificationModelRs() {
        return notificationModelRs;
    }

    /**
     * Sets the value of the notificationModelRs property.
     * 
     * @param value
     *     allowed object is
     *     {@link NotificationModelRsType }
     *     
     */
    public void setNotificationModelRs(NotificationModelRsType value) {
        this.notificationModelRs = value;
    }

    /**
     * Gets the value of the getShippingFeesRs property.
     * 
     * @return
     *     possible object is
     *     {@link GetShippingFeesRsType }
     *     
     */
    public GetShippingFeesRsType getGetShippingFeesRs() {
        return getShippingFeesRs;
    }

    /**
     * Sets the value of the getShippingFeesRs property.
     * 
     * @param value
     *     allowed object is
     *     {@link GetShippingFeesRsType }
     *     
     */
    public void setGetShippingFeesRs(GetShippingFeesRsType value) {
        this.getShippingFeesRs = value;
    }

    /**
     * Gets the value of the mngOrderRs property.
     * 
     * @return
     *     possible object is
     *     {@link MngOrderRsType }
     *     
     */
    public MngOrderRsType getMngOrderRs() {
        return mngOrderRs;
    }

    /**
     * Sets the value of the mngOrderRs property.
     * 
     * @param value
     *     allowed object is
     *     {@link MngOrderRsType }
     *     
     */
    public void setMngOrderRs(MngOrderRsType value) {
        this.mngOrderRs = value;
    }

    /**
     * Gets the value of the getOrderRs property.
     * 
     * @return
     *     possible object is
     *     {@link GetOrdersRsType }
     *     
     */
    public GetOrdersRsType getGetOrderRs() {
        return getOrderRs;
    }

    /**
     * Sets the value of the getOrderRs property.
     * 
     * @param value
     *     allowed object is
     *     {@link GetOrdersRsType }
     *     
     */
    public void setGetOrderRs(GetOrdersRsType value) {
        this.getOrderRs = value;
    }

    /**
     * Gets the value of the balanceInqRs property.
     * 
     * @return
     *     possible object is
     *     {@link BalanceInqRsType }
     *     
     */
    public BalanceInqRsType getBalanceInqRs() {
        return balanceInqRs;
    }

    /**
     * Sets the value of the balanceInqRs property.
     * 
     * @param value
     *     allowed object is
     *     {@link BalanceInqRsType }
     *     
     */
    public void setBalanceInqRs(BalanceInqRsType value) {
        this.balanceInqRs = value;
    }

    /**
     * Gets the value of the balanceSheetRs property.
     * 
     * @return
     *     possible object is
     *     {@link BalanceSheetRsType }
     *     
     */
    public BalanceSheetRsType getBalanceSheetRs() {
        return balanceSheetRs;
    }

    /**
     * Sets the value of the balanceSheetRs property.
     * 
     * @param value
     *     allowed object is
     *     {@link BalanceSheetRsType }
     *     
     */
    public void setBalanceSheetRs(BalanceSheetRsType value) {
        this.balanceSheetRs = value;
    }

    /**
     * Gets the value of the getDashboardRs property.
     * 
     * @return
     *     possible object is
     *     {@link GetDashboardRsType }
     *     
     */
    public GetDashboardRsType getGetDashboardRs() {
        return getDashboardRs;
    }

    /**
     * Sets the value of the getDashboardRs property.
     * 
     * @param value
     *     allowed object is
     *     {@link GetDashboardRsType }
     *     
     */
    public void setGetDashboardRs(GetDashboardRsType value) {
        this.getDashboardRs = value;
    }

    /**
     * Gets the value of the billersStructureRs property.
     * 
     * @return
     *     possible object is
     *     {@link BillersStructureRsType }
     *     
     */
    public BillersStructureRsType getBillersStructureRs() {
        return billersStructureRs;
    }

    /**
     * Sets the value of the billersStructureRs property.
     * 
     * @param value
     *     allowed object is
     *     {@link BillersStructureRsType }
     *     
     */
    public void setBillersStructureRs(BillersStructureRsType value) {
        this.billersStructureRs = value;
    }

}
