//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.fawry.adapter_template.model.fawryType;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RecCtrlOutType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="RecCtrlOutType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="MatchedRec" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         <element name="SentRec" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         <element name="Cursor" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RecCtrlOutType", propOrder = {
    "matchedRec",
    "sentRec",
    "cursor"
})
public class RecCtrlOutType {

    @XmlElement(name = "MatchedRec")
    protected long matchedRec;
    @XmlElement(name = "SentRec")
    protected long sentRec;
    @XmlElement(name = "Cursor")
    protected Long cursor;

    /**
     * Gets the value of the matchedRec property.
     * 
     */
    public long getMatchedRec() {
        return matchedRec;
    }

    /**
     * Sets the value of the matchedRec property.
     * 
     */
    public void setMatchedRec(long value) {
        this.matchedRec = value;
    }

    /**
     * Gets the value of the sentRec property.
     * 
     */
    public long getSentRec() {
        return sentRec;
    }

    /**
     * Sets the value of the sentRec property.
     * 
     */
    public void setSentRec(long value) {
        this.sentRec = value;
    }

    /**
     * Gets the value of the cursor property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getCursor() {
        return cursor;
    }

    /**
     * Sets the value of the cursor property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setCursor(Long value) {
        this.cursor = value;
    }

}
