//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.fawry.adapter_template.model.fawryType;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ReconTotalsResultType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="ReconTotalsResultType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="CspReconResultPrcInfo" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}CspReconResultPrcInfoType"/>
 *         <element name="ReconTotalsResultList" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}ReconTotalsResultListType"/>
 *         <element name="ReconTrxResultList" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}ReconTrxResultListType" minOccurs="0"/>
 *         <element name="NeedReversalTrxList" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}NeedReversalTrxListType" minOccurs="0"/>
 *         <element name="FailedBankList" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}FailedBankListType" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ReconTotalsResultType", propOrder = {
    "cspReconResultPrcInfo",
    "reconTotalsResultList",
    "reconTrxResultList",
    "needReversalTrxList",
    "failedBankList"
})
public class ReconTotalsResultType {

    @XmlElement(name = "CspReconResultPrcInfo", required = true)
    protected CspReconResultPrcInfoType cspReconResultPrcInfo;
    @XmlElement(name = "ReconTotalsResultList", required = true)
    protected ReconTotalsResultListType reconTotalsResultList;
    @XmlElement(name = "ReconTrxResultList")
    protected ReconTrxResultListType reconTrxResultList;
    @XmlElement(name = "NeedReversalTrxList")
    protected NeedReversalTrxListType needReversalTrxList;
    @XmlElement(name = "FailedBankList")
    protected FailedBankListType failedBankList;

    /**
     * Gets the value of the cspReconResultPrcInfo property.
     * 
     * @return
     *     possible object is
     *     {@link CspReconResultPrcInfoType }
     *     
     */
    public CspReconResultPrcInfoType getCspReconResultPrcInfo() {
        return cspReconResultPrcInfo;
    }

    /**
     * Sets the value of the cspReconResultPrcInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link CspReconResultPrcInfoType }
     *     
     */
    public void setCspReconResultPrcInfo(CspReconResultPrcInfoType value) {
        this.cspReconResultPrcInfo = value;
    }

    /**
     * Gets the value of the reconTotalsResultList property.
     * 
     * @return
     *     possible object is
     *     {@link ReconTotalsResultListType }
     *     
     */
    public ReconTotalsResultListType getReconTotalsResultList() {
        return reconTotalsResultList;
    }

    /**
     * Sets the value of the reconTotalsResultList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReconTotalsResultListType }
     *     
     */
    public void setReconTotalsResultList(ReconTotalsResultListType value) {
        this.reconTotalsResultList = value;
    }

    /**
     * Gets the value of the reconTrxResultList property.
     * 
     * @return
     *     possible object is
     *     {@link ReconTrxResultListType }
     *     
     */
    public ReconTrxResultListType getReconTrxResultList() {
        return reconTrxResultList;
    }

    /**
     * Sets the value of the reconTrxResultList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReconTrxResultListType }
     *     
     */
    public void setReconTrxResultList(ReconTrxResultListType value) {
        this.reconTrxResultList = value;
    }

    /**
     * Gets the value of the needReversalTrxList property.
     * 
     * @return
     *     possible object is
     *     {@link NeedReversalTrxListType }
     *     
     */
    public NeedReversalTrxListType getNeedReversalTrxList() {
        return needReversalTrxList;
    }

    /**
     * Sets the value of the needReversalTrxList property.
     * 
     * @param value
     *     allowed object is
     *     {@link NeedReversalTrxListType }
     *     
     */
    public void setNeedReversalTrxList(NeedReversalTrxListType value) {
        this.needReversalTrxList = value;
    }

    /**
     * Gets the value of the failedBankList property.
     * 
     * @return
     *     possible object is
     *     {@link FailedBankListType }
     *     
     */
    public FailedBankListType getFailedBankList() {
        return failedBankList;
    }

    /**
     * Sets the value of the failedBankList property.
     * 
     * @param value
     *     allowed object is
     *     {@link FailedBankListType }
     *     
     */
    public void setFailedBankList(FailedBankListType value) {
        this.failedBankList = value;
    }

}
