//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.fawry.adapter_template.model.fawryType;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ReconSvcRqType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="ReconSvcRqType">
 *   <complexContent>
 *     <extension base="{http://www.fawry-eg.com/ebpp/IFXMessages/}SvcCommonType">
 *       <choice>
 *         <element name="ReconCutOffRq" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}ReconCutOffType"/>
 *         <element name="ReconTotalsRq" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}ReconTotalsType"/>
 *         <element name="ReconTotalsResultRq" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}ReconTotalsResultType"/>
 *       </choice>
 *     </extension>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ReconSvcRqType", propOrder = {
    "reconCutOffRq",
    "reconTotalsRq",
    "reconTotalsResultRq"
})
public class ReconSvcRqType
    extends SvcCommonType
{

    @XmlElement(name = "ReconCutOffRq")
    protected ReconCutOffType reconCutOffRq;
    @XmlElement(name = "ReconTotalsRq")
    protected ReconTotalsType reconTotalsRq;
    @XmlElement(name = "ReconTotalsResultRq")
    protected ReconTotalsResultType reconTotalsResultRq;

    /**
     * Gets the value of the reconCutOffRq property.
     * 
     * @return
     *     possible object is
     *     {@link ReconCutOffType }
     *     
     */
    public ReconCutOffType getReconCutOffRq() {
        return reconCutOffRq;
    }

    /**
     * Sets the value of the reconCutOffRq property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReconCutOffType }
     *     
     */
    public void setReconCutOffRq(ReconCutOffType value) {
        this.reconCutOffRq = value;
    }

    /**
     * Gets the value of the reconTotalsRq property.
     * 
     * @return
     *     possible object is
     *     {@link ReconTotalsType }
     *     
     */
    public ReconTotalsType getReconTotalsRq() {
        return reconTotalsRq;
    }

    /**
     * Sets the value of the reconTotalsRq property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReconTotalsType }
     *     
     */
    public void setReconTotalsRq(ReconTotalsType value) {
        this.reconTotalsRq = value;
    }

    /**
     * Gets the value of the reconTotalsResultRq property.
     * 
     * @return
     *     possible object is
     *     {@link ReconTotalsResultType }
     *     
     */
    public ReconTotalsResultType getReconTotalsResultRq() {
        return reconTotalsResultRq;
    }

    /**
     * Sets the value of the reconTotalsResultRq property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReconTotalsResultType }
     *     
     */
    public void setReconTotalsResultRq(ReconTotalsResultType value) {
        this.reconTotalsResultRq = value;
    }

}
