//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.fawry.adapter_template.model.fawryType;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ReconSvcRsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="ReconSvcRsType">
 *   <complexContent>
 *     <extension base="{http://www.fawry-eg.com/ebpp/IFXMessages/}SvcRsCommonType">
 *       <sequence>
 *         <element name="ReconID">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               <maxLength value="36"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="ReconCutOffRs" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}ReconCutOffType" minOccurs="0"/>
 *       </sequence>
 *     </extension>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ReconSvcRsType", propOrder = {
    "reconID",
    "reconCutOffRs"
})
public class ReconSvcRsType
    extends SvcRsCommonType
{

    @XmlElement(name = "ReconID", required = true)
    protected String reconID;
    @XmlElement(name = "ReconCutOffRs")
    protected ReconCutOffType reconCutOffRs;

    /**
     * Gets the value of the reconID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReconID() {
        return reconID;
    }

    /**
     * Sets the value of the reconID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReconID(String value) {
        this.reconID = value;
    }

    /**
     * Gets the value of the reconCutOffRs property.
     * 
     * @return
     *     possible object is
     *     {@link ReconCutOffType }
     *     
     */
    public ReconCutOffType getReconCutOffRs() {
        return reconCutOffRs;
    }

    /**
     * Sets the value of the reconCutOffRs property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReconCutOffType }
     *     
     */
    public void setReconCutOffRs(ReconCutOffType value) {
        this.reconCutOffRs = value;
    }

}
