//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.fawry.adapter_template.model.fawryType;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ServiceTypeEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>{@code
 * <simpleType name="ServiceTypeEnum">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <enumeration value="CIP"/>
 *     <enumeration value="ELC"/>
 *     <enumeration value="PHN"/>
 *     <enumeration value="INS"/>
 *     <enumeration value="BKS"/>
 *     <enumeration value="GOV"/>
 *     <enumeration value="MED"/>
 *     <enumeration value="CCR"/>
 *     <enumeration value="UTL"/>
 *     <enumeration value="EXM"/>
 *     <enumeration value="TRV"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "ServiceTypeEnum")
@XmlEnum
public enum ServiceTypeEnum {

    CIP,
    ELC,
    PHN,
    INS,
    BKS,
    GOV,
    MED,
    CCR,
    UTL,
    EXM,
    TRV;

    public String value() {
        return name();
    }

    public static ServiceTypeEnum fromValue(String v) {
        return valueOf(v);
    }

}
