//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.fawry.adapter_template.model.fawryType;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ServiceRecType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="ServiceRecType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="ServiceType" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}Identifier_Type"/>
 *         <element name="ServiceName" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}Identifier_Type"/>
 *         <element name="BillersRec" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}BillersRecType" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ServiceRecType", propOrder = {
    "serviceType",
    "serviceName",
    "billersRec"
})
public class ServiceRecType {

    @XmlElement(name = "ServiceType", required = true)
    protected String serviceType;
    @XmlElement(name = "ServiceName", required = true)
    protected String serviceName;
    @XmlElement(name = "BillersRec")
    protected BillersRecType billersRec;

    /**
     * Gets the value of the serviceType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceType() {
        return serviceType;
    }

    /**
     * Sets the value of the serviceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceType(String value) {
        this.serviceType = value;
    }

    /**
     * Gets the value of the serviceName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceName() {
        return serviceName;
    }

    /**
     * Sets the value of the serviceName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceName(String value) {
        this.serviceName = value;
    }

    /**
     * Gets the value of the billersRec property.
     * 
     * @return
     *     possible object is
     *     {@link BillersRecType }
     *     
     */
    public BillersRecType getBillersRec() {
        return billersRec;
    }

    /**
     * Sets the value of the billersRec property.
     * 
     * @param value
     *     allowed object is
     *     {@link BillersRecType }
     *     
     */
    public void setBillersRec(BillersRecType value) {
        this.billersRec = value;
    }

}
