//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.fawry.adapter_template.model.fawryType;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SeverityEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>{@code
 * <simpleType name="SeverityEnum">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <enumeration value="Error"/>
 *     <enumeration value="Warning"/>
 *     <enumeration value="Info"/>
 *     <maxLength value="8"/>
 *     <minLength value="1"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "SeverityEnum")
@XmlEnum
public enum SeverityEnum {

    @XmlEnumValue("Error")
    @JsonProperty("Error")
    ERROR("Error"),
    @XmlEnumValue("Warning")
    @JsonProperty("Warning")

    WARNING("Warning"),
    @XmlEnumValue("Info")
    @JsonProperty("Info")

    INFO("Info");
    private final String value;

    SeverityEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }
    @JsonCreator
    public static SeverityEnum fromValue(String v) {
        for (SeverityEnum c : SeverityEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
