//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.fawry.adapter_template.model.fawryType;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;

import java.math.BigInteger;


/**
 * <p>Java class for ThreeDSecureType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="ThreeDSecureType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="ThreeDSECI" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         <element name="ThreeDSXID" minOccurs="0">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               <minLength value="0"/>
 *               <maxLength value="28"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="ThreeDSenrolled" minOccurs="0">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               <minLength value="1"/>
 *               <maxLength value="2"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="ThreeDSstatus" minOccurs="0">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               <minLength value="0"/>
 *               <maxLength value="2"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="VerToken" minOccurs="0">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               <minLength value="1"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="VerType" minOccurs="0">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               <minLength value="0"/>
 *               <maxLength value="3"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="VerSecurityLevel" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         <element name="VerStatus" minOccurs="0">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               <minLength value="1"/>
 *               <maxLength value="2"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="ThreeDSURL" minOccurs="0">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               <minLength value="0"/>
 *               <maxLength value="512"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ThreeDSecureType", propOrder = {
    "threeDSECI",
    "threeDSXID",
    "threeDSenrolled",
    "threeDSstatus",
    "verToken",
    "verType",
    "verSecurityLevel",
    "verStatus",
    "threeDSURL"
})
public class ThreeDSecureType {

    @XmlElement(name = "ThreeDSECI")
    protected BigInteger threeDSECI;
    @XmlElement(name = "ThreeDSXID")
    protected String threeDSXID;
    @XmlElement(name = "ThreeDSenrolled")
    protected String threeDSenrolled;
    @XmlElement(name = "ThreeDSstatus")
    protected String threeDSstatus;
    @XmlElement(name = "VerToken")
    protected String verToken;
    @XmlElement(name = "VerType")
    protected String verType;
    @XmlElement(name = "VerSecurityLevel")
    protected BigInteger verSecurityLevel;
    @XmlElement(name = "VerStatus")
    protected String verStatus;
    @XmlElement(name = "ThreeDSURL")
    protected String threeDSURL;

    /**
     * Gets the value of the threeDSECI property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getThreeDSECI() {
        return threeDSECI;
    }

    /**
     * Sets the value of the threeDSECI property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setThreeDSECI(BigInteger value) {
        this.threeDSECI = value;
    }

    /**
     * Gets the value of the threeDSXID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getThreeDSXID() {
        return threeDSXID;
    }

    /**
     * Sets the value of the threeDSXID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setThreeDSXID(String value) {
        this.threeDSXID = value;
    }

    /**
     * Gets the value of the threeDSenrolled property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getThreeDSenrolled() {
        return threeDSenrolled;
    }

    /**
     * Sets the value of the threeDSenrolled property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setThreeDSenrolled(String value) {
        this.threeDSenrolled = value;
    }

    /**
     * Gets the value of the threeDSstatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getThreeDSstatus() {
        return threeDSstatus;
    }

    /**
     * Sets the value of the threeDSstatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setThreeDSstatus(String value) {
        this.threeDSstatus = value;
    }

    /**
     * Gets the value of the verToken property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVerToken() {
        return verToken;
    }

    /**
     * Sets the value of the verToken property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVerToken(String value) {
        this.verToken = value;
    }

    /**
     * Gets the value of the verType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVerType() {
        return verType;
    }

    /**
     * Sets the value of the verType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVerType(String value) {
        this.verType = value;
    }

    /**
     * Gets the value of the verSecurityLevel property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getVerSecurityLevel() {
        return verSecurityLevel;
    }

    /**
     * Sets the value of the verSecurityLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setVerSecurityLevel(BigInteger value) {
        this.verSecurityLevel = value;
    }

    /**
     * Gets the value of the verStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVerStatus() {
        return verStatus;
    }

    /**
     * Sets the value of the verStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVerStatus(String value) {
        this.verStatus = value;
    }

    /**
     * Gets the value of the threeDSURL property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getThreeDSURL() {
        return threeDSURL;
    }

    /**
     * Sets the value of the threeDSURL property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setThreeDSURL(String value) {
        this.threeDSURL = value;
    }

}
