//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.fawry.adapter_template.model.fawryType;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;

import java.math.BigInteger;


/**
 * <p>Java class for TotalSpentPerBillTypeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="TotalSpentPerBillTypeType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="BillTypeCode" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         <element name="BillTypeName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         <element name="TtlSpent" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}CurAmtType"/>
 *         <element name="TtlSpentPer" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         <element name="SpentDetails" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}SpentDetailsType" minOccurs="0"/>
 *         <element name="Count" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TotalSpentPerBillTypeType", propOrder = {
    "billTypeCode",
    "billTypeName",
    "ttlSpent",
    "ttlSpentPer",
    "spentDetails",
    "count"
})
public class TotalSpentPerBillTypeType {

    @XmlElement(name = "BillTypeCode")
    protected long billTypeCode;
    @XmlElement(name = "BillTypeName")
    protected String billTypeName;
    @XmlElement(name = "TtlSpent", required = true)
    protected CurAmtType ttlSpent;
    @XmlElement(name = "TtlSpentPer")
    protected double ttlSpentPer;
    @XmlElement(name = "SpentDetails")
    protected SpentDetailsType spentDetails;
    @XmlElement(name = "Count")
    protected BigInteger count;

    /**
     * Gets the value of the billTypeCode property.
     * 
     */
    public long getBillTypeCode() {
        return billTypeCode;
    }

    /**
     * Sets the value of the billTypeCode property.
     * 
     */
    public void setBillTypeCode(long value) {
        this.billTypeCode = value;
    }

    /**
     * Gets the value of the billTypeName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillTypeName() {
        return billTypeName;
    }

    /**
     * Sets the value of the billTypeName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillTypeName(String value) {
        this.billTypeName = value;
    }

    /**
     * Gets the value of the ttlSpent property.
     * 
     * @return
     *     possible object is
     *     {@link CurAmtType }
     *     
     */
    public CurAmtType getTtlSpent() {
        return ttlSpent;
    }

    /**
     * Sets the value of the ttlSpent property.
     * 
     * @param value
     *     allowed object is
     *     {@link CurAmtType }
     *     
     */
    public void setTtlSpent(CurAmtType value) {
        this.ttlSpent = value;
    }

    /**
     * Gets the value of the ttlSpentPer property.
     * 
     */
    public double getTtlSpentPer() {
        return ttlSpentPer;
    }

    /**
     * Sets the value of the ttlSpentPer property.
     * 
     */
    public void setTtlSpentPer(double value) {
        this.ttlSpentPer = value;
    }

    /**
     * Gets the value of the spentDetails property.
     * 
     * @return
     *     possible object is
     *     {@link SpentDetailsType }
     *     
     */
    public SpentDetailsType getSpentDetails() {
        return spentDetails;
    }

    /**
     * Sets the value of the spentDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link SpentDetailsType }
     *     
     */
    public void setSpentDetails(SpentDetailsType value) {
        this.spentDetails = value;
    }

    /**
     * Gets the value of the count property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCount() {
        return count;
    }

    /**
     * Sets the value of the count property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCount(BigInteger value) {
        this.count = value;
    }

}
