//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.fawry.adapter_template.model.fawryType;

import jakarta.xml.bind.annotation.*;

import java.math.BigDecimal;


/**
 * <p>Java class for TotalsInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="TotalsInfoType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="TransStatus" type="{http://www.fawry-eg.com/ebpp/IFXMessages/}TransStatusEnum"/>
 *         <element name="TotalTrxCount" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         <element name="TotalTrxAmt" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         <element name="TotalTrxCustFees" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         <element name="TotalTrxHash" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TotalsInfoType", propOrder = {
    "transStatus",
    "totalTrxCount",
    "totalTrxAmt",
    "totalTrxCustFees",
    "totalTrxHash"
})
public class TotalsInfoType {

    @XmlElement(name = "TransStatus", required = true)
    @XmlSchemaType(name = "string")
    protected TransStatusEnum transStatus;
    @XmlElement(name = "TotalTrxCount", required = true)
    protected BigDecimal totalTrxCount;
    @XmlElement(name = "TotalTrxAmt", required = true)
    protected BigDecimal totalTrxAmt;
    @XmlElement(name = "TotalTrxCustFees", required = true)
    protected BigDecimal totalTrxCustFees;
    @XmlElement(name = "TotalTrxHash")
    protected String totalTrxHash;

    /**
     * Gets the value of the transStatus property.
     * 
     * @return
     *     possible object is
     *     {@link TransStatusEnum }
     *     
     */
    public TransStatusEnum getTransStatus() {
        return transStatus;
    }

    /**
     * Sets the value of the transStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransStatusEnum }
     *     
     */
    public void setTransStatus(TransStatusEnum value) {
        this.transStatus = value;
    }

    /**
     * Gets the value of the totalTrxCount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTotalTrxCount() {
        return totalTrxCount;
    }

    /**
     * Sets the value of the totalTrxCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTotalTrxCount(BigDecimal value) {
        this.totalTrxCount = value;
    }

    /**
     * Gets the value of the totalTrxAmt property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTotalTrxAmt() {
        return totalTrxAmt;
    }

    /**
     * Sets the value of the totalTrxAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTotalTrxAmt(BigDecimal value) {
        this.totalTrxAmt = value;
    }

    /**
     * Gets the value of the totalTrxCustFees property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTotalTrxCustFees() {
        return totalTrxCustFees;
    }

    /**
     * Sets the value of the totalTrxCustFees property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTotalTrxCustFees(BigDecimal value) {
        this.totalTrxCustFees = value;
    }

    /**
     * Gets the value of the totalTrxHash property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTotalTrxHash() {
        return totalTrxHash;
    }

    /**
     * Sets the value of the totalTrxHash property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTotalTrxHash(String value) {
        this.totalTrxHash = value;
    }

}
