adaptersConfigs:
  configs:
    DebitAddRq:
      - transformer: DebitAddRequestTransformerImpl
        connector: DebitAddConnectorImpl
    DebitRevRq:
      - transformer: DebitRevRequestTransformerImpl
        connector: DebitRevConnectorImpl



