<?xml version="1.0" encoding="UTF-8"?><xsd:schema targetNamespace="http:///AdapterResources/src/AdapterResource/configuration/xsd/errorCodesMapping.xsd" xmlns:this="http:///AdapterResources/src/AdapterResource/configuration/xsd/errorCodesMapping.xsd" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:element name="MessagesErrorCodes"
    	type="this:MessagesErrorCodesType">
    </xsd:element>
    
    <xsd:complexType name="MessagesErrorCodesType">
    	<xsd:sequence>
    		<xsd:element name="MessageErrorCode"
    			type="this:MessageErrorCodeType" maxOccurs="unbounded" minOccurs="0">
    		</xsd:element>
    	</xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="ErrorCodeType">
    	<xsd:sequence>
    		<xsd:element name="ErrorCode" type="xsd:string"
    			maxOccurs="1" minOccurs="1">
    		</xsd:element>
    		<xsd:element name="ErrorMessage" type="xsd:string"
    			maxOccurs="1" minOccurs="0">
    		</xsd:element>
    		<xsd:element name="ErrorSevirity" type="xsd:string" maxOccurs="1" minOccurs="0"></xsd:element>
    	</xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="MessageErrorCodeType">
    	<xsd:sequence>
    		<xsd:element name="FromErrorCode" type="this:ErrorCodeType"
    			maxOccurs="unbounded" minOccurs="1">
    		</xsd:element>
    		<xsd:element name="ToErrorCode" type="this:ErrorCodeType" maxOccurs="1" minOccurs="1"></xsd:element>
    	</xsd:sequence>
    </xsd:complexType>
</xsd:schema>